File: prices.ipynb\
Author: alexkobz\
Date: 08-10-2024\
Task: DSRFU-298

#### Шаг 0. Импорт и получение токена

In [1]:
import requests
import pandas as pd
import numpy as np
import nest_asyncio; nest_asyncio.apply()
from datetime import datetime as dt
from math import ceil
from src.utils.get_date import last_day_month, last_day_month_str, last_work_date_month, last_work_date_month_str

# последний день месяца
REPORT_DATE = last_day_month
REPORT_DATE_STR = last_day_month_str
# увеличиваем количество столбцов и строк для просмотра
pd.set_option('display.max_rows', 200, 'display.max_columns', 200)
REPORT_DATE

Unexpected Http Driver Exception

Error HTTPConnectionPool(host='host.docker.internal', port=8124): Max retries exceeded with url: /? (Caused by NameResolutionError("HTTPConnection(host='host.docker.internal', port=8124): Failed to resolve 'host.docker.internal' ([Errno 8] nodename nor servname provided, or not known)")) executing HTTP request attempt 1 (http://host.docker.internal:8124)

datetime.date(2026, 1, 31)

In [2]:
from src.sources.rudata.RuDataMethod import Account, FintoolReferenceData, EndOfDay, AccruedInterestOnDate, FloaterData, FloatersOnPeriod, RUPriceHistory, ExchangeTree, MoexSecurities, CurrencyRate, HistoryStockBonds, HistoryStockShares, HistoryStockNdm, HistoryStockCcp, CompanyGroupMembers
Account()

#### Шаг 1. RuData

##### Шаг 1.0. RuData stage

In [3]:
FintoolReferenceDataDF = FintoolReferenceData().df
FintoolReferenceDataDF.head()

,facevalue_m,faceftname_m,sumissuevol_m,summarketvol_m,numcoupons_m,nrdcode,regcode_m,regdate_m,regdistdate_m,begdistdate_m,enddistdate_m,endmtydate_m,daysall_m,fullname_nrd,rpregorg_nrd,rpstate_nrd,issuenumber,currentfacevalue_nrd,isqualified_nrd,bondseries,islombardcbr_nrd,numcoupons_nrd,facevalue_nrd,faceftname_nrd,summarketvol_nrd,regcode_nrd,regdate_nrd,regorg_nrd,begdistdate_nrd,daysall_nrd,enddistdate_nrd,endmtydate_nrd,regdistdate_nrd,sumissuevol_nrd,drqty,isincodebase_nrd,nrdcompcode,shqty,summarketvolorig_nrd,issuername_nrd,planmtydate_nrd,firstcoupondate_nrd,depositary_nrd,registrar_nrd,placeprice_nrd,micexlist_nrd,minlot_nrd,formarketbonds_nrd,registraracctype_nrd,registraracctypedate_nrd,facialacc_nrd,acc_open_date_nrd,fraction_nrd,specialized_depo_nrd,cmp_code_nsd_issuer_nrd,cmp_code_nsd_managing_nrd,ratetypenamerus_nrd,ratetypenameeng_nrd,coupontypename_nrd,base_month,base_year,basis_nrd,sectypenamerus_nrd,sectypenameeng_nrd,secformnamerus_nrd,secformnameeng_nrd,sectypenamebr_nrd,secstaterus_nrd,secstateeng_nrd,placementtype_nrd,share_category_name_nrd,share_category_name_en_nrd,dr_category_name_nrd,dr_category_name_en_nrd,company_state_name_nrd,rate_type_id,cp_type_id,coupon_period_base_id,sec_type_id,sec_form_id,sec_state_id,placement_type_id,share_category_id,dr_category_mn,company_state_mn,sector4212u,sna2008,fullname_en_nrd,seniorityname,fintoolid,moex_code,moex_name,fullname,isin144a,isincode,nickname,progfintoolid,regcode,regdate,regorg,amortisedmty,basis,bondstructuralpar,cfi,coupontype,fintooltype,guaranteeamount,guaranteetype,haveoffer,isconvertible,isguaranteed,maturitygroup,securitization,accruedintcalctype,country,couponperyear,faceftname,facevalue,guarantval,havedefault,numcoupons,status,sumissueval,sumissuevol,summarketval,summarketvol,borrowername,borrowerokpo,borrowersector,borroweruid,borrowerinn,borrowercountry,borrowerregionname,issuername,issuerokpo,issuersector,issueruid,issuerinn,issuercountry,issuerregionname,assetssector,numguarantors,begdistdate,begmtydate,daysall,enddistdate,endmtydate,privatedist,regdistdate,securitytype,securitykind,nominaltype,update_time,isregion,nsd_service,raterevisionsperyear,floatratename,issubordinated,note,listing_level,havecovenant,haverepayment,haveindexedfv,numdecimals,couponperiod,ismatched,firstcoupondate,couponrate,iscomplicated,available_for_unqualified,sec_type_br_code,original_country,qualified_test_id,qualified_test_id_tm,base_asset_fintoolid,isqualified,listing_level_spb,have_mm_moex,have_mm_spb,beg_book_date,seniority,tradesite,current_coupontype,profit_type,counter,rn
0,3.0,3.0,3.0,3.0,3.0,RU000A108TG4,3.0,3.0,3.0,3.0,3.0,3.0,3.0,Структурные процентные дисконтные неконвертиру...,Небанковская кредитная организация акционерное...,Зарегистрирован/Представлен,002,1000.0,1.0,001Р-02,0.0,1.0,1000.0,RUB,50000.0,6-02-00796-R-001P,2024-06-17T00:00:00,Центральный банк Российской Федерации,2024-06-27T00:00:00,1835.0,2024-06-27T00:00:00,2029-07-06T00:00:00,2024-06-28T00:00:00,50000.0,NaN,<NA>,MC0594300000,NaN,NaN,"ООО ""СФО АТОН Структурные Решения""",2029-07-06T00:00:00,<NA>,NDC000000000,<NA>,NaN,<NA>,NaN,0.0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,с фиксированной ставкой,fixed rate,Иной,A,365,A/365,<NA>,<NA>,Бездокументарная,Book-entry,Структурные долговые ценные бумаги прочих рези...,Размещен,Placed,Подписка закрытая,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,7.0,4.0,NaN,7.0,2.0,2.0,NaN,<NA>,<NA>,<NA>,S112,SFO ATON Structured Solutions 0.0001 06/07/29,Старшие обеспеченные,240540,<NA>,<NA>,"""Специализированное финансовое общество АТОН С...",<NA>,RU000A108TG4,СФО АТОН СтрРеш-001Р-02,239235.0,6-02-00796-R-001P,2024-06-17T00:00:00,ЦБ РФ,0.0,act/365,Структурные,DEXFXX,Прочий,Облигация,<NA>,Залог,0.0,0.0,0.0,Среднесрочные,Прочие активы,1.0,RU,1.0,RUB,1000.0,NaN,0.0,1.0,В обращении,50000000.0,50000.0,50000000.0,50000.0,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,<NA>,0.0,2024-06-27T00:00:00,<NA>,1835.0,2024-06-27T00:00:00,2029-07-06T00:00:00,1.0,2024-06-28T00:00:00,Корп,Классические,Структурный,2026-02-04T02:50:32,NaN,На обслуживании,1.0,<NA>,NaN,Облигации с допдоходом.,NaN,False,False,False,2.0,1835.0,True,2024-06-27T00:00:00,0.0001,True,0,SN2,RU,1000,1000,NaN,True,NaN,0,0,<NA>,430.0,NaN,Прочий,Фикс.+доп.доход,108645,98305
1,3.0,3.0,3.0,3.0,3.0,RU000A108TH2,3.0,3.0,3.0,3.0,3.0,3.0,3.0,Структурные процентные дисконтные неконвертиру...,Небанковская кредитная организация акционерное...,Зарегистрирован/Представлен,003,1000.0,1.0,001Р-03,0.0,1.0,1000.0,RUB,50000.0,6-03-00796-R-001P,2024-06-17T00:00:00,Центральный банк Российской Федерации,2024-06-27T00:00:00,1835.0,2024-06-27T00:00:00,2029-07-06T00:00:00,2024-06-28T00:00:00,50000.0,NaN,<NA>,MC0594300000,NaN,NaN,"ООО ""СФО АТОН Структурные Решения""",2029-07-06T00:00:00,<NA>,NDC000000000,<NA>,NaN,<NA>,NaN,0.0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,с фиксированной ставкой,fixed rate,Иной,A,365,A/365,<NA>,<NA>,Бездокументарная,Book-entry,Структурные долговые ценные бумаги прочих рези...,Размещен,Placed,Подписка закрытая,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,7.0,4.0,NaN,7.0,2.0,2.0,NaN,<NA>,<NA>,<NA>,S112,SFO ATON Structured Solutions 0.0001 06/07/29,Старшие обеспеченные,240541,<NA>,<NA>,"""Специализированное финансовое общество АТОН С...",<NA>,RU000A108TH2,СФО АТОН СтрРеш-001Р-03,239235.0,6-03-00796-R-001P,2024-06-17T00:00:00,ЦБ РФ,0.0,act/365,Структурные,DEXFXX,Прочий,Облигация,<NA>,Залог,0.0,0.0,0.0,Среднесрочные,Прочие активы,1.0,RU,1.0,RUB,1000.0,NaN,0.0,1.0,В обращении,50000000.0,50000.0,50000000.0,50000.0,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,<NA>,0.0,2024-06-27T00:00:00,<NA>,1835.0,2024-06-27T00:00:00,2029-07-06T00:00:00,1.0,2024-06-28T00:00:00,Корп,Классические,Структурный,2026-02-04T02:50:32,NaN,На обслуживании,1.0,<NA>,NaN,Облигации с допдоходом.,NaN,False,False,False,2.0,1835.0,True,2024-06-27T00:00:00,0.0001,True,0,SN2,RU,1000,1000,NaN,True,NaN,0,0,<NA>,430.0,NaN,Прочий,Фикс.+доп.доход,108645,98306
2,3.0,3.0,3.0,3.0,3.0,RU000A108TJ8,3.0,3.0,3.0,3.0,3.0,3.0,3.0,Структурные процентные дисконтные неконвертиру...,Небанковская кредитная организация акционерное...,Зарегистрирован/Представлен,004,1000.0,1.0,001Р-04,0.0,1.0,1000.0,RUB,50000.0,6-04-00796-R-001P,2024-06-17T00:00:00,Центральный банк Российской Федерации,2024-07-03T00:00:00,1836.0,2024-07-03T00:00:00,2029-07-13T00:00:00,2024-07-04T00:00:00,50000.0,NaN,<NA>,MC0594300000,NaN,NaN,"ООО ""СФО АТОН Структурные Решения""",2029-07-13T00:00:00,<NA>,NDC000000000,<NA>,NaN,<NA>,NaN,0.0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,с фиксированной ставкой,fixed rate,Иной,A,365,A/365,<NA>,<NA>,Бездокументарная,Book-entry,Структурные долговые ценные бумаги прочих рези...,Размещен,Placed,Подписка закрытая,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,7.0,4.0,NaN,7.0,2.0,2.0,NaN,<NA>,<NA>,<NA>,S112,SFO ATON Structured Solutions 0.0001 13/07/29,Старшие обеспеченные,240542,<NA>,<NA>,"""Специализированное финансовое общество АТОН С...",<NA>,RU000A108TJ8,СФО АТОН СтрРеш-001Р-04,239235.0,6-04-00796-R-001P,2024-06-17T00:00:00,ЦБ РФ,0.0,act/365,Структурные,DEXFXX,Прочий,Облигация,<NA>,Залог,0.0,0.0,0.0,Долгосрочные,Прочие активы,1.0,RU,1.0,RUB,1000.0,NaN,0.0,1.0,В обращении,50000000.0,50000.0,50000000.0,50000.0,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,<NA>,0.0,2024-07-03T00:00:00,<NA>,1836.0,2024-07-03T00:00:00,2029-07-13T00:00:00,1.0,2024-07-04T00:00:00,Корп,Классические,Структурный,2026-02-04T02:50:32,NaN,На обслуживании,1.0,<NA>,NaN,Облигации с Допдоходом.,NaN,False,False,False,2.0,1836.0,True,2024-07-03T00:00:00,0.0001,True,0,SN2,RU,1000,1000,NaN,True,NaN,0,0,<NA>,430.0,NaN,Прочий,Фикс.+доп.доход,108645,98307
3,3.0,3.0,3.0,3.0,3.0,RU000A108TK6,3.0,3.0,3.0,3.0,3.0,3.0,3.0,Структурные процентные дисконтные неконвертиру...,Небанковская кредитная организация акционерное...,Зарегистрирован/Представлен,005,1000.0,1.0,001Р-05,0.0,1.0,1000.0,RUB,50000.0,6-05-00796-R-001P,2024-06-17T00:00:00,Центральный банк Российской Федерации,2024-07-03T00:00:00,1836.0,2024-07-03T00:00:00,2029-07-13T00:00:00,2024-07-04T00:00:00,50000.0,NaN,<NA>,MC0594300000,NaN,NaN,"ООО ""СФО АТОН Структурные Решения""",2029-07-13T00:00:00,<NA>,NDC000000000,<NA>,NaN,<NA>,NaN,0.0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,с фиксированной ставкой,fixed rate,Иной,A,365,A/365,<NA>,<NA>,Бездокументарная,Book-entry,Структурные долговые ценные бумаги прочих рези...,Размещен,Placed,Подписка закрытая,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,7.0,4.0,NaN,7.0,2.0,2.0,NaN,<NA>,<NA>,<NA>,S112,SFO ATON Structured Solutions 0.0001 13/07/29,Старшие обеспеченные,240543,<NA>,<NA>,"""Специализированное финансовое общество АТОН С...",<NA>,RU000A108TK6,СФО АТОН СтрРеш-001Р-05,239235.0,6-05-00796-R-001P,2024-06-17T00:00:00,ЦБ РФ,0.0,act/365,Структурные,DEXFXX,Прочий,Облигация,<NA>,Залог,0.0,0.0,0.0,Долгосрочные,Прочие активы,1.0,RU,1.0,RUB,1000.0,NaN,0.0,1.0,В обращении,50000000.0,50000.0,50000000.0,50000.0,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,<NA>,0.0,2024-07-03T00:00:00,<NA>,1836.0,2024-07-03T00:00:00,2029-07-13T00:00:00,1.0,2024-07-04T00:00:00,Корп,Классические,Структурный,2026-02-04T02:50:32,NaN,На обслуживании,1.0,<NA>,NaN,Облигации с Допдоходом.,NaN,False,False,False,2.0,1836.0,True,2024-07-03T00:00:00,0.0001,True,0,SN2,RU,1000,1000,NaN,True,NaN,0,0,<NA>,430.0,NaN,Прочий,Фикс.+доп.доход,108645,98308
4,3.0,3.0,3.0,3.0,3.0,RU000A108TL4,3.0,3.0,3.0,3.0,3.0,3.0,3.0,Структурные процентные дисконтные неконвертиру...,Небанковская кредитная организация акционерное...,Зарегистрирован/Представлен,006,1000.0,1.0,001Р-06,0.0,1.0,1000.0,RUB,50000.0,6-06-00796-R-001P,2024-06-17T00:00:00,Центральный банк Российской Федерации,2024-07-03T00:00:00,1836.0,2024-07-03T00:00:00,2029-07-13T00:00:00,2024-07-04T00:00:00,50000.0,NaN,<NA>,MC0594300000,NaN,NaN,"ООО ""СФО АТОН Структурные Решения""",2029-07-13T00:00:00,<NA>,NDC000000000,<NA>,NaN,<NA>,NaN,0.0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,с фиксированной ставкой,fixed rate,Иной,A,365,A/365,<NA>,<NA>,Бездокументарная,Book-entry,Структурные долговые ценные бумаги прочих рези...,Размещен,Placed,Подписка закрытая,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,7.0,4.0,NaN,7.0,2.0,2.0,NaN,<NA>,<NA>,<NA>,S112,SFO ATON Structured Solutions 0.0001 13/07/29,Старшие обеспеченные,240544,<NA>,<NA>,"""Специализированное финансовое общество АТОН С...",<NA>,RU000A108TL4,СФО АТОН СтрРеш-001Р-06,239235.0,6-06-00796-R-001P,2024-06-17T00:00:00,ЦБ РФ,0.0,act/365,Структурные,DEXFXX,Прочий,Облигация,<NA>,Залог,0.0,0.0,0.0,Долгосрочные,Прочие активы,1.0,RU,1.0,RUB,1000.0,NaN,0.0,1.0,В обращении,50000000.0,50000.0,50000000.0,50000.0,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,<NA>,0.0,2024-07-03T00:00:00,<NA>,1836.0,2024-07-03T00:00:00,2029-07-13T00:00:00,1.0,2024-07-04T00:00:00,Корп,Классические,Структурный,2026-02-04T02:50:32,NaN,На обслуживании,1.0,<NA>,NaN,Облигации с ДопДоходом.,NaN,False,False,False,2.0,1836.0,True,2024-07-03T00:00:00,0.0001,True,0,SN2,RU,1000,1000,NaN,True,NaN,0,0,<NA>,430.0,NaN,Прочий,Фикс.+доп.доход,108645,98309

In [4]:
EndOfDayDF = EndOfDay().df
EndOfDayDF.head()

,ask,avge_prce,bid,boardid,boardname,close,convexity,deal_acc,duration,exch,high,isin,last,last_time,last_yield,low,mat_date,mprice,name,open,pvbp,seccode,secname,spread,val,val_usd,vol,vol_lots,yield_agg,yield_ask,yield_average_o12m,yield_average_o2w,yield_bid,yield_swa,currency,fintoolId,id_iss,id_trade_site,add_date,update_date
0,57.42,57.42,57.32,TQBR,T+ Акции и ДР,57.26,NaN,2914.0,NaN,MICEX,57.53,RU0009062285,57.35,2026-01-31T18:59:58,NaN,57.29,<NA>,57.45,AFLT.MICEX,57.37,NaN,AFLT,"Аэрофлот - российские авиалинии ОАО, АО - ФБ...",0.1,80540165.8,1063517.30,1402570.0,140257.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4200,35154,170,2026-01-31T23:55:01,2026-02-01T07:00:45
1,10.45,10.30,10.35,TQBR,T+ Акции и ДР,10.17,NaN,125.0,NaN,MICEX,10.48,RU0009100176,10.37,2026-01-31T18:58:02.0001,NaN,10.12,<NA>,10.19,BISVP.MICEX,10.18,NaN,BISVP,"Башинформсвязь ОАО, АП - ФБ ММВБ",0.1,1673346.0,22096.21,162400.0,1624.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4215,775000,170,2026-01-31T23:55:06,2026-02-01T07:00:45
2,1876.00,1871.00,1866.00,TQBR,T+ Акции и ДР,1852.00,NaN,171.0,NaN,MICEX,1882.00,RU0009288658,1870.00,2026-01-31T18:43:48,NaN,1846.00,<NA>,1870.00,BRZL.MICEX,1852.00,NaN,BRZL,"Бурятзолото ОАО, АО - ФБ ММВБ",10.0,2123150.0,28035.78,1135.0,1135.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4217,852973,170,2026-01-31T23:55:07,2026-02-01T07:00:45
3,77.60,77.00,77.40,TQBR,T+ Акции и ДР,77.80,NaN,9.0,NaN,MICEX,77.80,RU0009082291,77.80,2026-01-31T16:00:27,NaN,76.40,<NA>,77.80,CHGZ.MICEX,77.60,NaN,CHGZ,"Черногорнефть ОАО, АО - ФБ ММВБ",0.2,26176.0,345.64,340.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4223,853518,170,2026-01-31T23:55:08,2026-02-01T07:00:45
4,1000.60,1000.70,999.80,TQBR,T+ Акции и ДР,999.80,NaN,1891.0,NaN,MICEX,1005.00,RU0009046510,999.80,2026-01-31T18:59:30,NaN,998.00,<NA>,1000.40,CHMF.MICEX,999.00,NaN,CHMF,"Северсталь ОАО, АО - ФБ ММВБ T+2",0.8,41359409.4,546143.00,41330.0,41330.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4226,1069768,170,2026-01-31T23:55:06,2026-02-01T07:00:45

In [5]:
AccruedInterestOnDateDF = AccruedInterestOnDate().df
AccruedInterestOnDateDF.head()

,fintoolId,shiftDays,shiftTypeSource,typeCurrency,date,accruedInterest,accruedInterestPct,currentFaceValue,currentFaceValuePct,calculationType,error,faceValueCurrency,accruedInterestCurrency,faceValueLastKnownDate
0,4000,0,Calendar,<NA>,2026-01-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,<NA>,RUB,RUB,2026-01-31T00:00:00
1,4001,0,Calendar,<NA>,2026-01-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,<NA>,RUB,RUB,2026-01-31T00:00:00
2,4002,0,Calendar,<NA>,2026-01-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,<NA>,RUB,RUB,2026-01-31T00:00:00
3,4003,0,Calendar,<NA>,2026-01-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,<NA>,RUB,RUB,2026-01-31T00:00:00
4,4004,0,Calendar,<NA>,2026-01-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,<NA>,RUB,RUB,2026-01-31T00:00:00

In [6]:
FloaterDataDF = FloaterData().df
FloaterDataDF.head()

,fintoolId,beg_period,end_period,start_point,model_type,date_pub_n,date_pub_type,date_fix_n,date_fix_type,bases
0,11193,2000-12-01T00:00:00,2050-12-01T00:00:00,E,single,NaN,<NA>,10.0,W,"[{'base_no': 1, 'calc_type': 'FIX', 'base_fint..."
1,36325,2009-08-27T00:00:00,2028-09-15T00:00:00,B,single,NaN,<NA>,1.0,W,"[{'base_no': 1, 'calc_type': 'FIX', 'base_fint..."
2,57394,2011-11-21T00:00:00,2028-10-30T00:00:00,B,single,NaN,<NA>,5.0,W,"[{'base_no': 2, 'calc_type': 'PER', 'base_fint..."
3,59702,2013-12-11T00:00:00,2028-11-22T00:00:00,B,single,NaN,<NA>,5.0,C,"[{'base_no': 2, 'calc_type': 'FIX', 'base_fint..."
4,61946,2017-08-18T00:00:00,2044-08-11T00:00:00,B,single,NaN,<NA>,5.0,W,"[{'base_no': 1, 'calc_type': 'PER', 'base_fint..."

In [7]:
FloatersOnPeriodDF = FloatersOnPeriod().df
FloatersOnPeriodDF.head()

,fintoolId,date,accruedInterest,accruedInterestPct,currentFaceValue,currentFaceValuePct,faceValueCurrency,addDate,counter
0,164245,2026-01-31T00:00:00,16.45,1.65,1000.0,100.0,RUB,2026-01-30T06:02:22,2
1,164245,2026-01-31T00:00:00,16.45,1.65,1000.0,100.0,RUB,2026-01-30T06:02:22,316
2,165152,2026-01-31T00:00:00,16.45,1.65,1000.0,100.0,RUB,2026-01-30T06:02:32,2
3,165152,2026-01-31T00:00:00,16.45,1.65,1000.0,100.0,RUB,2026-01-30T06:02:32,316
4,170151,2026-01-31T00:00:00,4.32,0.43,1000.0,100.0,RUB,2026-01-30T06:03:03,2

In [8]:
RUPriceHistoryDF = RUPriceHistory().df
RUPriceHistoryDF.head()

,nickname,fintoolid,fininstid,isincode,regcode,nrdcode,calcdate,val_date,current_fv,faceftname,date_agg,avge_prce,yield_agg,z_wa_mb,durmod_agg,i_wa_mb,method_no,vp_pct,vp_pc,vp_pc_l,vp_pc_h,vp_m1,y_agg_m1,deal_250d,q_m1,r_m1,vp_m2,y_agg_m2,i_vp_m2,sigma_m2,index,beta1_m2,beta0_m2,alpha_m2,gamma_m2,sigma_nu,rho_m2,r_m2,vp_m3,y_agg_m3,dur_agg_m3,z_vp_m3,r_m3,factor1,beta1_m3,factor2,beta2_m3,level_pd,coef_b,risk_b,beta3_m3,is_ontherun,beta4_m3,hhi,beta5_m3,ind_liq,beta6_m3,ind_unliq,beta7_m3,sector,phi_sector,version,valuation_currency,security_type,source,wa_duration,duration_mod,lbound1,ubound1,lbound2,ubound2,lbound3,ubound3,acc_int,wap_ext_zspread,mp3_ext_zspread,id,no_history_found,not_valid_code,calcDateTime,counter,rn
0,Россия-2030-11т,6043,7080,XS0114288789,SK-0-CM-128,XS0114288789,2026-01-05T00:00:00,2026-01-05T00:00:00,0.045,USD,2030-03-31T00:00:00,0.0,0.0,0.0,<NA>,0.0,1.0,106.569775,0.047956,104.999723,108.139827,106.569775,4.378984,0.0,0.0,0.0,106.569775,4.378984,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,106.569775,4.378984,0.0,0.5216,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Государственные,0.0,2,USD,euro_bond,3,0.0,1.970507,104.999723,108.139827,104.999723,108.139827,104.999723,108.139827,0.000891,0.0,0.0,6043,<NA>,<NA>,<NA>,45817,1
1,Россия-2030-11т,6043,7080,XS0114288789,SK-0-CM-128,XS0114288789,2026-01-06T00:00:00,2026-01-06T00:00:00,0.045,USD,2030-03-31T00:00:00,0.0,0.0,0.0,<NA>,0.0,1.0,106.458266,0.047906,104.975477,107.941055,106.458266,4.427566,0.0,0.0,0.0,106.458266,4.427566,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,106.458266,4.427566,0.0,0.5811,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Государственные,0.0,2,USD,euro_bond,3,0.0,1.966236,104.975477,107.941055,104.975477,107.941055,104.975477,107.941055,0.000900,0.0,0.0,6043,<NA>,<NA>,<NA>,45817,2
2,Россия-2030-11т,6043,7080,XS0114288789,SK-0-CM-128,XS0114288789,2026-01-08T00:00:00,2026-01-08T00:00:00,0.045,USD,2030-03-31T00:00:00,0.0,0.0,0.0,<NA>,0.0,1.0,106.862613,0.048088,105.370649,108.354578,106.862613,4.231024,0.0,0.0,0.0,106.862613,4.231024,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,106.862613,4.231024,0.0,0.6273,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Государственные,0.0,2,USD,euro_bond,3,0.0,1.967653,105.370649,108.354578,105.370649,108.354578,105.370649,108.354578,0.000919,0.0,0.0,6043,<NA>,<NA>,<NA>,45817,3
3,Россия-2030-11т,6043,7080,XS0114288789,SK-0-CM-128,XS0114288789,2026-01-09T00:00:00,2026-01-09T00:00:00,0.045,USD,2030-03-31T00:00:00,0.0,0.0,0.0,<NA>,0.0,1.0,106.696623,0.048013,105.179766,108.213479,106.696623,4.304849,0.0,0.0,0.0,106.696623,4.304849,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,106.696623,4.304849,0.0,0.6176,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Государственные,0.0,2,USD,euro_bond,3,0.0,1.962519,105.179766,108.213479,105.179766,108.213479,105.179766,108.213479,0.000928,0.0,0.0,6043,<NA>,<NA>,<NA>,45817,4
4,Россия-2030-11т,6043,7080,XS0114288789,SK-0-CM-128,XS0114288789,2026-01-12T00:00:00,2026-01-12T00:00:00,0.045,USD,2030-03-31T00:00:00,0.0,0.0,0.0,<NA>,0.0,1.0,104.133067,0.046860,102.456242,105.809892,104.133067,5.525852,0.0,0.0,0.0,104.133067,5.525852,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,104.133067,5.525852,0.0,0.4888,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Государственные,0.0,2,USD,euro_bond,3,0.0,1.913945,102.456242,105.809892,102.456242,105.809892,102.456242,105.809892,0.000956,0.0,0.0,6043,<NA>,<NA>,<NA>,45817,5

In [9]:
ExchangeTreeDF = ExchangeTree().df
ExchangeTreeDF.head()

,id,id_parent,shortname_rus,shortname_eng,fullname_rus,fullname_eng,sort_order,update_date,counter,rn
0,1,0,РТС,RTS,Московская Биржа - РТС,RTS,12,2020-12-28T17:03:09,242,17
1,2,1,РТС,RTS,РТС индексы,RTS indexes,2,2020-12-28T17:03:09,242,4
2,8,1,ФОРТС,FORTS,FORTS,FORTS,8,2020-12-28T17:03:09,242,11
3,9,0,"ПАО ""СПБ""",PJSC «SPB»,"ПАО ""СПБ""",PJSC «SPB»,20,2020-12-28T17:03:09,242,21
4,11,0,МБ,MX,Московская Биржа,Moscow Exchange,11,2020-12-28T17:03:09,242,16

In [10]:
MoexSecuritiesDF = MoexSecurities().df
MoexSecuritiesDF.head()

,id_iss,secid,boardid,board_title,board_group,board_group_title,market,engine,short_name,isin,cfi_ifx,cfi_name,lot_size,expiration_date,currency,emitent_code,emitent_name,market_sector,min_price_increment,fintoolid,reg_code,update_date,counter,rn
0,3107707,A-RM,LIQB,Продажа обеспечения бирж.рынок - безадрес.,stock_mamc_liq,Безадресные сделки с ЦК,mamc,stock,<NA>,US00846U1016,ESXXXX,Акции / обыкновенные,1,<NA>,<NA>,<NA>,<NA>,<NA>,0.01,127649.0,<NA>,2021-11-01T05:02:21.84541,240365,101900
1,3107886,A-RM,PSSD,РПС: Ин.Акции (USD) - адрес.,stock_foreignndm_usd,РПС: Ин.Акции (USD) - адрес.,foreignndm,stock,<NA>,US00846U1016,ESXXXX,Акции / обыкновенные,1,<NA>,RUB,<NA>,<NA>,<NA>,0.01,127649.0,<NA>,2022-12-22T09:56:16.326722,240365,102079
2,3107946,A-RM,FTEQ,РПС с ЦК: Ин.Акции и ДР - адрес.,stock_foreign_ccp,РПС с ЦК: Ин.Акции и ДР - адрес.,foreignndm,stock,<NA>,US00846U1016,ESXXXX,Акции / обыкновенные,1,<NA>,<NA>,<NA>,<NA>,<NA>,1.00,127649.0,<NA>,2021-11-01T05:03:14.845768,240365,102139
3,3108028,A-RM,EQRE,РЕПО с ЦК 1 день (EUR) - безадрес.,stock_ccp_d_eur,РЕПО с ЦК 1 день (EUR) - безадрес.,ccp,stock,<NA>,US00846U1016,ESXXXX,Акции / обыкновенные,1,<NA>,<NA>,<NA>,<NA>,<NA>,0.01,127649.0,<NA>,2021-11-01T05:03:33.845899,240365,102221
4,3108069,A-RM,LIQR,РЕПО с ЦК: Урегулирование - безадрес.,stock_ccp_liq,РЕПО с ЦК: Урегулирование - безадрес.,ccp,stock,<NA>,US00846U1016,ESXXXX,Акции / обыкновенные,1,<NA>,<NA>,<NA>,<NA>,<NA>,0.01,127649.0,<NA>,2021-11-01T05:03:42.845958,240365,102262

In [11]:
CurrencyRateDF = CurrencyRate().df
CurrencyRateDF.head()

        rate  endOfDayRate error from   to
0  20.621600     20.621600  <NA>  AED  RUB
1        NaN           NaN  <NA>  AFN  RUB
2        NaN           NaN  <NA>  ALL  RUB
3   0.200012      0.200012  <NA>  AMD  RUB
4        NaN           NaN  <NA>  ANG  RUB

##### Шаг 1.1. RuData MOEX stage

In [12]:
HistoryStockBondsDF = HistoryStockBonds().df
HistoryStockBondsDF.head()

,boardname,regnumber,isin,matdate,listname,facevalue,currencyid,volume,value,numtrades,prev,prevlegalcloseprice,openperiod,legalopenprice,legalcloseprice,closeperiod,waprice,trendclose,trendclspr,trendwap,trendwappr,openval,closeval,highbid,lowoffer,bid,offer,yieldatwap,yieldclose,accint,duration,marketprice,marketprice2,admittedquote,issuesize,mpvaltrd,mp2valtrd,admittedvalue,marketprice3,marketprice3tradesvalue,type,lastprice,iricpiclose,beiclose,couponpercent,couponvalue,buybackdate,lasttradedate,cbrclose,yieldtooffer,yieldlastcoupon,offerdate,faceunit,engine,market,boardid,decimals,high,low,open,close,secid,shortname,tradedate,tradingsession,counter
0,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,10,774517.25,8,99.9999,99.6773,NaN,<NA>,99.5759,<NA>,99.0093,-0.4240,-0.42,-0.8067,-0.81,70404.50,233684.82,100.9017,99.0890,99.2033,99.8997,8.52,8.09,114.3932,NaN,<NA>,99.6910,<NA>,240419,0.0,5103404.50,<NA>,99.0938,928660.69,corporate_bond,99.5759,NaN,NaN,7.63,38.02,<NA>,2026-01-05T00:00:00,<NA>,NaN,NaN,<NA>,USD,stock,bonds,TQCB,4,100.9002,90.0006,90.0006,99.5759,BYM000001818,РесБел 331,2026-01-05T00:00:00,3,NaN
1,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,16,1223206.81,10,99.5759,99.5759,NaN,<NA>,98.5010,<NA>,97.7293,0.1241,0.12,-1.2800,-1.29,76067.41,77992.02,99.7000,97.2383,99.1810,100.2458,9.53,8.00,130.7350,NaN,<NA>,98.0984,<NA>,240419,0.0,1841740.10,<NA>,97.9207,1378802.69,corporate_bond,99.7000,NaN,NaN,7.63,38.02,<NA>,2026-01-06T00:00:00,<NA>,NaN,NaN,<NA>,USD,stock,bonds,TQCB,4,99.7000,97.2384,97.2397,99.7000,BYM000001818,РесБел 331,2026-01-06T00:00:00,3,NaN
2,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,67,5241207.06,13,99.7000,98.5010,NaN,<NA>,99.8194,<NA>,100.0003,0.1194,0.12,2.2710,2.32,78071.19,156170.85,100.3000,99.8000,99.8100,100.3996,7.77,7.90,163.4188,NaN,<NA>,100.0003,<NA>,240419,0.0,5241207.06,<NA>,100.0003,5241207.06,corporate_bond,99.8194,NaN,NaN,7.63,38.02,<NA>,2026-01-08T00:00:00,<NA>,NaN,NaN,<NA>,USD,stock,bonds,TQCB,4,100.3000,99.8000,99.8012,99.8194,BYM000001818,РесБел 331,2026-01-08T00:00:00,3,NaN
3,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,14,1095792.64,10,99.8194,99.8194,NaN,<NA>,100.0945,<NA>,100.0565,0.2747,0.28,0.0562,0.06,156453.24,78300.31,100.1500,99.8600,100.0946,100.3999,7.72,7.69,179.7607,NaN,<NA>,100.0090,<NA>,240419,0.0,6258699.39,<NA>,100.0224,1173663.18,corporate_bond,100.0941,NaN,NaN,7.63,38.02,<NA>,2026-01-09T00:00:00,<NA>,NaN,NaN,<NA>,USD,stock,bonds,TQCB,4,100.1500,99.8600,99.9999,100.0941,BYM000001818,РесБел 331,2026-01-09T00:00:00,3,NaN
4,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,95,7492926.80,31,100.0941,100.0945,NaN,<NA>,100.9200,<NA>,100.8261,0.5160,0.52,0.7696,0.77,156600.62,78703.96,101.0002,100.0941,100.6101,101.8988,7.14,7.30,228.7863,NaN,<NA>,100.7355,<NA>,240419,0.0,4806923.41,<NA>,100.7355,4806923.41,corporate_bond,100.6101,NaN,NaN,7.63,38.02,<NA>,2026-01-12T00:00:00,<NA>,NaN,NaN,<NA>,USD,stock,bonds,TQCB,4,101.0002,100.0941,100.0941,100.6101,BYM000001818,РесБел 331,2026-01-12T00:00:00,3,NaN

In [13]:
HistoryStockSharesDF = HistoryStockShares().df
HistoryStockSharesDF.head()

,boardname,regnumber,isin,listname,facevalue,currencyid,prevlegalcloseprice,prev,legalopenprice,openperiod,closeperiod,openval,closeval,legalcloseprice,trendclose,trendclspr,highbid,bid,offer,lowoffer,waprice,trendwap,trendwappr,volume,marketprice,marketprice2,mp2valtrd,mpvaltrd,value,numtrades,issuesize,admittedquote,admittedvalue,monthlycapitalization,dailycapitalization,marketprice3,marketprice3tradesvalue,type,closeauctionprice,waval,lastprice,engine,market,boardid,decimals,high,low,open,close,secid,shortname,tradedate,tradingsession,counter
0,Т+: Акции и ДР - безадрес.,1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,68.28,68.48,<NA>,NaN,<NA>,1369.6,13576.0,67.82,-0.60,-0.88,79.50,67.74,67.86,67.16,67.90,-0.40,-0.59,89520,<NA>,67.90,4954777.2,0.0,6079130.0,1207,92645451,<NA>,<NA>,6.323978e+09,6.290626e+09,67.90,4954777.2,common_share,67.82,0.0,67.88,stock,shares,TQBR,2,68.56,67.64,68.48,67.88,ABIO,iАРТГЕН ао,2026-01-05T00:00:00,3,NaN
1,Т+: Акции и ДР - безадрес.,1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,67.82,67.88,<NA>,NaN,<NA>,678.8,1360.0,68.00,0.12,0.18,68.86,68.00,68.08,67.30,68.00,0.10,0.15,39800,<NA>,68.08,984314.2,0.0,2706682.6,392,92645451,<NA>,<NA>,6.323978e+09,6.307302e+09,68.08,984314.2,common_share,68.00,0.0,68.00,stock,shares,TQBR,2,68.22,67.78,67.88,68.00,ABIO,iАРТГЕН ао,2026-01-06T00:00:00,3,NaN
2,Т+: Акции и ДР - безадрес.,1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,68.00,68.00,<NA>,NaN,<NA>,680.0,678.2,67.66,-0.18,-0.26,68.80,67.72,67.82,65.00,67.72,-0.28,-0.41,89090,<NA>,67.74,4423180.0,0.0,6032664.2,1041,92645451,<NA>,<NA>,6.323978e+09,6.275803e+09,67.74,4423180.0,common_share,67.66,0.0,67.82,stock,shares,TQBR,2,68.08,67.20,68.00,67.82,ABIO,iАРТГЕН ао,2026-01-08T00:00:00,3,NaN
3,Т+: Акции и ДР - безадрес.,1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,67.66,67.82,<NA>,NaN,<NA>,677.2,679.8,68.14,0.16,0.24,70.78,67.98,68.00,65.48,68.14,0.42,0.62,42310,<NA>,68.16,853246.0,0.0,2883348.4,517,92645451,<NA>,<NA>,6.323978e+09,6.314714e+09,68.16,853246.0,common_share,68.14,0.0,67.98,stock,shares,TQBR,2,68.46,67.70,67.72,67.98,ABIO,iАРТГЕН ао,2026-01-09T00:00:00,3,NaN
4,Т+: Акции и ДР - безадрес.,1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,68.14,67.98,<NA>,NaN,<NA>,2040.0,2716.0,67.92,-0.08,-0.12,72.00,67.90,67.98,67.34,68.06,-0.08,-0.12,80780,<NA>,68.06,2867942.2,0.0,5497470.0,798,92645451,<NA>,<NA>,6.323978e+09,6.305449e+09,68.06,2867942.2,common_share,67.92,0.0,67.90,stock,shares,TQBR,2,68.46,67.72,68.00,67.90,ABIO,iАРТГЕН ао,2026-01-12T00:00:00,3,NaN

In [14]:
HistoryStockNdmDF = HistoryStockNdm().df
HistoryStockNdmDF.head()

,boardname,closeval,currencyid,facevalue,isin,issuesize,listname,matdate,numtrades,openval,prev,regnumber,trendclose,trendclspr,trendwap,trendwappr,type,value,volume,waprice,yieldatwap,yieldclose,lastprice,iricpiclose,beiclose,couponpercent,couponvalue,buybackdate,lasttradedate,cbrclose,yieldtooffer,yieldlastcoupon,offerdate,faceunit,engine,market,boardid,decimals,high,low,open,close,secid,shortname,tradedate,tradingsession,counter
0,РПС: Акции - адрес.,5351.2,SUR,0.09,RU000A0DQZE3,9650000000,1,<NA>,1,5351.2,13.219,1-05-01669-A,0.159,NaN,-0.086,-0.64,common_share,5351.2,400,13.438,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,stock,ndm,PSEQ,3,13.378,13.378,13.378,13.378,AFKS,Система ао,2026-01-30T00:00:00,3,NaN
1,РПС с ЦК: Акции и ДР - адрес.,3851.4,SUR,0.09,RU000A0DQZE3,9650000000,1,<NA>,2,3851.4,13.267,1-05-01669-A,-0.429,NaN,0.129,1.01,common_share,7702.8,600,12.928,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,stock,ndm,PTEQ,3,12.838,12.838,12.838,12.838,AFKS,Система ао,2026-01-15T00:00:00,3,NaN
2,РПС с ЦК: Акции и ДР - адрес.,1302.0,SUR,0.09,RU000A0DQZE3,9650000000,1,<NA>,2,1302.0,12.838,1-05-01669-A,0.182,NaN,0.167,1.29,common_share,2604.0,200,13.095,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,stock,ndm,PTEQ,3,13.020,13.020,13.020,13.020,AFKS,Система ао,2026-01-16T00:00:00,3,NaN
3,РПС с ЦК: Акции и ДР - адрес.,9488855.1,SUR,0.09,RU000A0DQZE3,9650000000,1,<NA>,1,9488855.1,13.020,1-05-01669-A,0.117,NaN,0.111,0.85,common_share,9488855.1,722300,13.206,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,stock,ndm,PTEQ,3,13.137,13.137,13.137,13.137,AFKS,Система ао,2026-01-19T00:00:00,3,NaN
4,РПС с ЦК: Акции и ДР - адрес.,10745.6,SUR,0.09,RU000A0DQZE3,9650000000,1,<NA>,2,10745.6,13.137,1-05-01669-A,0.295,NaN,0.161,1.20,common_share,21491.2,1600,13.524,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,stock,ndm,PTEQ,3,13.432,13.432,13.432,13.432,AFKS,Система ао,2026-01-29T00:00:00,3,NaN

In [15]:
HistoryStockCcpDF = HistoryStockCcp().df
HistoryStockCcpDF.head()

,accint,admittedquote,admittedvalue,bid,boardname,closeperiod,closeval,currencyid,duration,facevalue,highbid,isin,issuesize,legalcloseprice,legalopenprice,listname,lowoffer,marketprice,marketprice2,marketprice3,marketprice3tradesvalue,matdate,mp2valtrd,mpvaltrd,numtrades,offer,openperiod,openval,prev,prevlegalcloseprice,regnumber,trendclose,trendclspr,trendwap,trendwappr,type,value,volume,waprice,yieldatwap,yieldclose,engine,market,boardid,decimals,high,low,open,close,secid,shortname,tradedate,tradingsession,counter
0,NaN,<NA>,<NA>,<NA>,РЕПО с ЦК 1 день - безадрес.,<NA>,99975.05,SUR,<NA>,0.1,NaN,RU000A0JNAB6,92645451,<NA>,<NA>,2,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,2,<NA>,<NA>,201608.59,8.13,<NA>,1-01-08902-A,NaN,<NA>,NaN,NaN,common_share,301583.64,5819,NaN,<NA>,<NA>,stock,ccp,EQRP,4,NaN,NaN,NaN,NaN,ABIO,iАРТГЕН ао,2026-01-05T00:00:00,3,NaN
1,NaN,<NA>,<NA>,<NA>,РЕПО с ЦК 1 день - безадрес.,<NA>,334515.37,SUR,<NA>,0.1,NaN,RU000A0JNAB6,92645451,<NA>,<NA>,2,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,2,<NA>,<NA>,105045.04,NaN,<NA>,1-01-08902-A,NaN,<NA>,NaN,NaN,common_share,439560.41,8528,0.40,<NA>,<NA>,stock,ccp,EQRP,4,0.53,NaN,NaN,0.53,ABIO,iАРТГЕН ао,2026-01-06T00:00:00,3,NaN
2,NaN,<NA>,<NA>,<NA>,РЕПО с ЦК 1 день - безадрес.,<NA>,290828.76,SUR,<NA>,0.1,NaN,RU000A0JNAB6,92645451,<NA>,<NA>,2,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,2,<NA>,<NA>,99975.62,0.53,<NA>,1-01-08902-A,-11.58,<NA>,-8.62,NaN,common_share,390804.38,7560,-8.22,<NA>,<NA>,stock,ccp,EQRP,4,NaN,-11.05,NaN,-11.05,ABIO,iАРТГЕН ао,2026-01-08T00:00:00,3,NaN
3,NaN,<NA>,<NA>,<NA>,РЕПО с ЦК 1 день - безадрес.,<NA>,161293.70,SUR,<NA>,0.1,NaN,RU000A0JNAB6,92645451,<NA>,<NA>,2,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,3,<NA>,<NA>,104996.00,-11.05,<NA>,1-01-08902-A,19.21,<NA>,15.67,NaN,common_share,467389.86,9041,7.45,<NA>,<NA>,stock,ccp,EQRP,4,8.16,5.00,5.0,8.16,ABIO,iАРТГЕН ао,2026-01-12T00:00:00,3,NaN
4,NaN,<NA>,<NA>,<NA>,РЕПО с ЦК 1 день - безадрес.,<NA>,200834.09,SUR,<NA>,0.1,NaN,RU000A0JNAB6,92645451,<NA>,<NA>,2,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,4,<NA>,<NA>,104960.33,8.16,<NA>,1-01-08902-A,-3.16,<NA>,-15.90,NaN,common_share,568066.19,11003,-8.45,<NA>,<NA>,stock,ccp,EQRP,4,5.00,-24.15,5.0,5.00,ABIO,iАРТГЕН ао,2026-01-13T00:00:00,3,NaN

##### Шаг 2. RuData transform

In [16]:
Prices = FintoolReferenceDataDF[['isincode', 'nickname', 'fintooltype', 'fintoolid', 'faceftname']]\
.rename(columns={
    "isincode": "isin",
    "nickname": "name",
    "fintoolid": "fintool",
    "fintooltype": "type",
    "faceftname": "currency_tmp"
})
Prices = Prices[~(Prices["isin"].isna() | (Prices["isin"].isin(['None', ''])))]
InterestDF = AccruedInterestOnDateDF[['fintoolId', 'accruedInterest', 'currentFaceValue']].set_index('fintoolId')
InterestDF.update(FloatersOnPeriodDF.groupby('fintoolId').last())
Prices = Prices.merge(
    InterestDF, how="left", left_on="fintool", right_index=True)
Prices = Prices.rename(columns={
    'accruedInterest': 'interest',
    'currentFaceValue': 'principal'})

###### Шаг 2.1.1. CBR

In [17]:
from src.sources.cbr.CBR_Soap import CBR_Soap

headers = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.6834.111 Safari/537.36',
           'Accept-Encoding': 'gzip, deflate',
           'Accept': '*/*',
           'Connection': 'keep-alive'}
cbr_disc = CBR_Soap()\
.get_discounts(date=last_work_date_month_str)[['ISIN', 'от 1 месяца до 180 дней_Beg']]\
.rename(columns={'от 1 месяца до 180 дней_Beg': 'cbr_discount_6d'})\
.groupby('ISIN')\
.last()\
.reset_index()

In [18]:
Prices = Prices.merge(cbr_disc, how='left', left_on='isin', right_on='ISIN')
Prices['cbr_discount_6d'] = Prices['cbr_discount_6d'].fillna(1.0)

###### Шаг 2.1.2. nationalclearingcentre Рыночные риски

In [19]:
import io

currMarketRatesResponse = requests.get(
    f'https://www.nationalclearingcentre.ru/api/v1/rates/fondMarketRates?action=xls&xls=1&lang=ru&date={last_work_date_month.strftime("%d.%m.%Y")}',
    headers=headers
)
currMarketRates = pd.read_excel(io.BytesIO(currMarketRatesResponse.content), header=2)
currMarketRates = currMarketRates[(currMarketRates['Диапазон']==1)&(currMarketRates['Ставка риска падения цены,%']!=100)].reset_index(drop=True)
currMarketRates = currMarketRates\
.merge(MoexSecuritiesDF[['secid', 'isin']], how='left', left_on='Инструмент', right_on='secid')\
.groupby('isin')\
.last()\
.reset_index()
currMarketRates = currMarketRates[currMarketRates['isin'].str.match('([A-Z]{2})([A-Z0-9]{9})([0-9]{1})$')]
currMarketRates = currMarketRates[
    (currMarketRates['Диапазон']==1) & (currMarketRates['Ставка риска падения цены,%'] != 100)
]
currMarketRates = currMarketRates[['isin', 'Ставка риска падения цены,%']]\
.rename(columns={'Ставка риска падения цены,%': 'Risk rate'})
# Формула из п.12.1 Методики НКЦ определения риск-параметров
currMarketRates['discount_ncc'] = currMarketRates['Risk rate'].apply(lambda x: min(30, ceil(x/np.sqrt(2)))/100)

In [20]:
Prices = Prices.merge(currMarketRates[['isin', 'discount_ncc']], how='left', on='isin')
Prices['discount_ncc'] = Prices['discount_ncc'].fillna(1.0)

###### Шаг 2.1.3. nationalclearingcentre Параметры ценных бумаг

In [21]:
import io

securInfoResponse = requests.get(
    f'https://www.nationalclearingcentre.ru/api/v1/rates/securInfo?action=xls&lang=ru&settleDate={last_work_date_month.strftime("%d.%m.%Y")}', headers=headers
)
securInfo = pd.read_excel(io.BytesIO(securInfoResponse.content), header=2)[['ISIN ЦБ', 'Принимается в обеспеч.']]\
.rename(columns={
    'ISIN ЦБ': 'isin',
    'Принимается в обеспеч.': 'ncc_collateral'
})\
.dropna()\
.groupby('isin')\
.last()\
.reset_index()
securInfo = securInfo[securInfo['ncc_collateral']=='Да']

In [22]:
Prices = Prices.merge(securInfo, how='left', on='isin')
Prices['ncc_collateral'] = Prices['ncc_collateral'].fillna('Нет')

##### Шаг 2.2. RuData transform

RU Data (ЦЦ НРД)

In [23]:
RUPriceHistoryLast = RUPriceHistoryDF.groupby('isincode').last().rename(columns={
    'vp_pct': 'clean_price_pct',
    'vp_pc': 'clean_price',
    'acc_int': 'InterestHistory'
}).reset_index()
ru_price = RUPriceHistoryLast[['isincode', 'clean_price_pct', 'clean_price', 'InterestHistory']].merge(
    Prices[['isin', 'type', 'interest']], left_on='isincode', right_on='isin')
ccnrd_bonds_idx = ru_price["type"]=='Облигация'
ru_price.loc[ccnrd_bonds_idx, "interest"] = ru_price.loc[ccnrd_bonds_idx, "interest"].combine_first(ru_price.loc[ccnrd_bonds_idx, "InterestHistory"])
ru_price.loc[ccnrd_bonds_idx, "price"] = ru_price.loc[ccnrd_bonds_idx, "clean_price"] + ru_price.loc[ccnrd_bonds_idx, "interest"].fillna(0)
ru_price.loc[~ccnrd_bonds_idx, "price"] = ru_price.loc[~ccnrd_bonds_idx, "clean_price"]
ru_price["source"] = 'RU Data (ЦЦ НРД)'

End of Day

In [24]:
exch_prices = EndOfDayDF.merge(
    ExchangeTreeDF[['id', 'fullname_rus']], how='left', left_on='id_trade_site', right_on='id')[['fintoolId', 'last', 'fullname_rus', 'currency']]
exch_prices["source"] = exch_prices['fullname_rus'].apply(lambda x: 'RU Data (' + str(x) + ')')
exch_prices = exch_prices\
.rename(columns={
    'fintoolId': 'fintool',
    'last': 'price_ex'
})
exch_prices = exch_prices.merge(Prices[["fintool", "isin", "type", "principal", "interest"]], how='inner')
exch_prices[['price_ex', 'principal', 'interest']] = exch_prices[['price_ex', 'principal', 'interest']].fillna(0)

exch_bonds = exch_prices['type']=='Облигация'
exch_prices.loc[exch_bonds, "clean_price_pct"] = exch_prices.loc[exch_bonds, "price_ex"]
exch_prices.loc[exch_bonds, "clean_price"] = exch_prices.loc[exch_bonds, "clean_price_pct"]/100 * exch_prices.loc[exch_bonds, "principal"]
exch_prices.loc[exch_bonds, "price"] = exch_prices.loc[exch_bonds, "clean_price"] + exch_prices.loc[exch_bonds, "interest"]

exch_prices.loc[~exch_bonds, 'clean_price'] = exch_prices.loc[~exch_bonds, 'price_ex']
exch_prices.loc[~exch_bonds, 'price'] = exch_prices.loc[~exch_bonds, 'price_ex']

exch_shares = exch_prices['type']=='Акция'
exch_prices.loc[~exch_shares, "currency"] = None

##### Шаг 3. Moex

In [25]:
TransformHistoryStockBonds = HistoryStockBondsDF.groupby("isin")['close'].last().rename("price").reset_index()
TransformHistoryStockShares = (
    HistoryStockSharesDF
    .groupby("isin")
    [['close', 'currencyid']]
    .last()
    .rename(columns={
        'close': 'price',
        'currencyid': 'currency'
    })
    .reset_index()
    .replace('SUR', 'RUB')
)
TransformHistoryStockNdm = HistoryStockNdmDF.groupby("isin")['close'].last().rename("price").reset_index()
TransformHistoryStockCcp = HistoryStockCcpDF.groupby("isin")['close'].last().rename("price").reset_index()
HistoryStock = pd.concat(
    [TransformHistoryStockBonds, TransformHistoryStockShares, TransformHistoryStockNdm, TransformHistoryStockCcp]
).groupby('isin').last().reset_index()
HistoryStock['source'] = 'RU Data (MOEX)'

#### Шаг 4. Finish

In [26]:
source_prices = pd.concat([
    ru_price[["isin", "clean_price_pct", "clean_price", "price", "source"]],
    exch_prices[["isin", "clean_price_pct", "clean_price", "price", "source", "currency"]],
    HistoryStock
])
result = Prices.merge(
    source_prices,
    how='inner',
    on='isin',
)

Currency

In [27]:
result['currency'] = result['currency'].combine_first(result['currency_tmp'])
result = result.merge(
    CurrencyRateDF[CurrencyRateDF['to']=='RUB'][['from', 'rate']], how='left', left_on='currency', right_on='from'
).drop(columns=['from'])

In [28]:
result['fx_rate'] = result['rate']
result.loc[result['currency']=='RUB', 'fx_rate'] = 1
result['export_timestamp'] = dt.now().replace(microsecond=0)
result['report_date'] = pd.to_datetime(last_day_month)
result['source'] = result['source'].replace('nan', '').fillna('')
result['name'] = result['name'].replace('nan', '').fillna('')
result['type'] = result['type'].replace('nan', '').fillna('')
result['currency'] = result['currency'].replace('nan', '').fillna('')
result['fintool'] = result['fintool'].astype(int)
result = result.sort_values('isin')[["isin", "name", "type", "fintool", "currency", "interest", "principal", "fx_rate", "cbr_discount_6d", "discount_ncc", "ncc_collateral", "clean_price_pct", "clean_price", "price", "source", "export_timestamp", "report_date"]]

##### Шаг 4.2. Write excel

In [29]:
result.to_csv('./data/output/prices.csv', index=False, sep='\t', header=True)

In [30]:
from src.utils.send_email import main
main("prices.csv")