File: prices.ipynb\
Author: alexkobz\
Date: 08-10-2024\
Task: DSRFU-298

#### Шаг 0. Импорт и получение токена

In [1]:
import requests
import pandas as pd
import numpy as np
import nest_asyncio; nest_asyncio.apply()
from datetime import datetime as dt
from math import ceil
from src.utils.get_date import last_day_month, last_day_month_str, last_work_date_month, last_work_date_month_str

# последний день месяца
REPORT_DATE = last_day_month
REPORT_DATE_STR = last_day_month_str
# увеличиваем количество столбцов и строк для просмотра
pd.set_option('display.max_rows', 200, 'display.max_columns', 200)
REPORT_DATE

Unexpected Http Driver Exception

Error HTTPConnectionPool(host='host.docker.internal', port=8124): Max retries exceeded with url: /? (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x162fbb5b0>: Failed to resolve 'host.docker.internal' ([Errno 8] nodename nor servname provided, or not known)")) executing HTTP request attempt 1 (http://host.docker.internal:8124)

datetime.date(2025, 12, 31)

In [2]:
from src.sources.rudata.RuDataMethod import Account, FintoolReferenceData, EndOfDay, AccruedInterestOnDate, FloaterData, FloatersOnPeriod, RUPriceHistory, ExchangeTree, MoexSecurities, CurrencyRate, HistoryStockBonds, HistoryStockShares, HistoryStockNdm, HistoryStockCcp
Acc = Account()

#### Шаг 1. RuData

##### Шаг 1.0. RuData stage

In [3]:
FintoolReferenceDataDF = FintoolReferenceData().df
FintoolReferenceDataDF.head()

,facevalue_m,faceftname_m,sumissuevol_m,summarketvol_m,numcoupons_m,nrdcode,regcode_m,regdate_m,regdistdate_m,begdistdate_m,enddistdate_m,endmtydate_m,daysall_m,fullname_nrd,rpregorg_nrd,rpstate_nrd,issuenumber,currentfacevalue_nrd,isqualified_nrd,bondseries,islombardcbr_nrd,numcoupons_nrd,facevalue_nrd,faceftname_nrd,summarketvol_nrd,regcode_nrd,regdate_nrd,regorg_nrd,begdistdate_nrd,daysall_nrd,enddistdate_nrd,endmtydate_nrd,regdistdate_nrd,sumissuevol_nrd,drqty,isincodebase_nrd,nrdcompcode,shqty,summarketvolorig_nrd,issuername_nrd,planmtydate_nrd,firstcoupondate_nrd,depositary_nrd,registrar_nrd,placeprice_nrd,micexlist_nrd,minlot_nrd,formarketbonds_nrd,registraracctype_nrd,registraracctypedate_nrd,facialacc_nrd,acc_open_date_nrd,fraction_nrd,specialized_depo_nrd,cmp_code_nsd_issuer_nrd,cmp_code_nsd_managing_nrd,ratetypenamerus_nrd,ratetypenameeng_nrd,coupontypename_nrd,base_month,base_year,basis_nrd,sectypenamerus_nrd,sectypenameeng_nrd,secformnamerus_nrd,secformnameeng_nrd,sectypenamebr_nrd,secstaterus_nrd,secstateeng_nrd,placementtype_nrd,share_category_name_nrd,share_category_name_en_nrd,dr_category_name_nrd,dr_category_name_en_nrd,company_state_name_nrd,rate_type_id,cp_type_id,coupon_period_base_id,sec_type_id,sec_form_id,sec_state_id,placement_type_id,share_category_id,dr_category_mn,company_state_mn,sector4212u,sna2008,fullname_en_nrd,seniorityname,fintoolid,moex_code,moex_name,fullname,isin144a,isincode,nickname,progfintoolid,regcode,regdate,regorg,amortisedmty,basis,bondstructuralpar,cfi,coupontype,fintooltype,guaranteeamount,guaranteetype,haveoffer,isconvertible,isguaranteed,maturitygroup,securitization,accruedintcalctype,country,couponperyear,faceftname,facevalue,guarantval,havedefault,numcoupons,status,sumissueval,sumissuevol,summarketval,summarketvol,borrowername,borrowerokpo,borrowersector,borroweruid,borrowerinn,borrowercountry,borrowerregionname,issuername,issuerokpo,issuersector,issueruid,issuerinn,issuercountry,issuerregionname,assetssector,numguarantors,begdistdate,begmtydate,daysall,enddistdate,endmtydate,privatedist,regdistdate,securitytype,securitykind,nominaltype,update_time,isregion,nsd_service,raterevisionsperyear,floatratename,issubordinated,note,listing_level,havecovenant,haverepayment,haveindexedfv,numdecimals,couponperiod,ismatched,firstcoupondate,couponrate,iscomplicated,available_for_unqualified,sec_type_br_code,original_country,qualified_test_id,qualified_test_id_tm,base_asset_fintoolid,isqualified,listing_level_spb,have_mm_moex,have_mm_spb,beg_book_date,seniority,tradesite,current_coupontype,profit_type,counter,rn
0,2.0,2.0,2.0,2.0,2.0,None,0.0,0.0,2.0,2.0,2.0,2.0,2.0,None,None,None,None,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None,None,None,NaN,None,None,None,NaN,NaN,None,None,NaN,NaN,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,520,S2,None,Старшие необеспеченные,226059,None,None,"Соединённые Штаты Америки, 5-летние ноты с пог...",None,US91282CGH88,США-2-280131-об,NaN,None,None,None,0.0,act/act,None,None,Постоянный,Облигация,None,Необеспеченные,0.0,0.0,0.0,Среднесрочные,None,1.0,US,2.0,USD,100.00,NaN,0.0,10.0,В обращении,4.400000e+10,4.400000e+08,4.300001e+10,4.300001e+08,Правительство США,None,Государственные,95111.0,None,US,None,Минфин США,None,Государственные,95112.0,None,US,None,None,0.0,2023-01-31T00:00:00,None,1826.0,2023-01-31T00:00:00,2028-01-31T00:00:00,0.0,2023-01-31T00:00:00,Гос,Классические,Постоянный,2025-08-15T10:20:36,NaN,Нет информации,2.0,None,NaN,None,NaN,False,False,False,2.0,184.0,True,2023-01-31T00:00:00,3.5,False,0,OTHER,US,1000,1000,NaN,False,NaN,0,0,None,416.0,NaN,Фиксированный,Постоянный,108206,90113
1,2.0,2.0,2.0,2.0,2.0,None,0.0,0.0,2.0,2.0,2.0,2.0,2.0,None,None,None,None,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None,None,None,NaN,None,None,None,NaN,NaN,None,None,NaN,NaN,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,520,S2,None,Старшие необеспеченные,226060,None,None,"Соединённые Штаты Америки, 7-летние ноты с пог...",None,US91282CGJ45,США-300131-об,NaN,None,None,None,0.0,act/act,None,None,Постоянный,Облигация,None,Необеспеченные,0.0,0.0,0.0,Среднесрочные,None,1.0,US,2.0,USD,100.00,NaN,0.0,14.0,В обращении,3.600000e+10,3.600000e+08,3.500001e+10,3.500001e+08,Правительство США,None,Государственные,95111.0,None,US,None,Минфин США,None,Государственные,95112.0,None,US,None,None,0.0,2023-01-31T00:00:00,None,2557.0,2023-01-31T00:00:00,2030-01-31T00:00:00,0.0,2023-01-31T00:00:00,Гос,Классические,Постоянный,2025-08-15T10:20:36,NaN,Нет информации,2.0,None,NaN,None,NaN,False,False,False,2.0,184.0,True,2023-01-31T00:00:00,3.5,False,0,OTHER,US,1000,1000,NaN,False,NaN,0,0,None,416.0,NaN,Фиксированный,Постоянный,108206,90114
2,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None,None,None,NaN,None,None,None,NaN,NaN,None,None,NaN,NaN,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,520,S2,None,Старшие необеспеченные,226061,None,None,"Германия, государственные облигации (Bubills) ...",None,DE000BU0E006,Германия-2-12-2023-об,NaN,None,None,None,0.0,act/360,None,None,Дисконтный,Облигация,None,Необеспеченные,0.0,0.0,0.0,Краткосрочные,None,1.0,DE,NaN,EUR,0.01,NaN,0.0,NaN,Погашен,1.300000e+10,1.300000e+12,1.300000e+10,1.300000e+12,Правительство Германии,None,Государственные,95093.0,None,DE,None,German Finance Agency,None,Государственные,95309.0,DE137223325,DE,None,None,0.0,2023-01-30T00:00:00,None,317.0,2023-01-30T00:00:00,2023-12-13T00:00:00,0.0,2023-01-30T00:00:00,Гос,Классические,Постоянный,2024-11-22T13:50:27,NaN,Нет информации,NaN,None,NaN,None,NaN,False,False,False,6.0,NaN,True,None,0.0,False,0,BON5,DE,1000,1000,NaN,False,NaN,0,0,None,416.0,NaN,None,Дисконтный,108206,90115
3,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None,None,None,NaN,None,None,None,NaN,NaN,None,None,NaN,NaN,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,S112,None,None,226062,None,None,"""Головной институт по проектированию предприят...",None,None,ГипроВТИ-1-ао,NaN,1-01-55176-D,2004-01-30T00:00:00,ФКЦБ,NaN,None,None,None,None,Акция,None,None,NaN,0.0,NaN,None,None,NaN,RU,NaN,RUB,10.00,NaN,NaN,NaN,В обращении,2.469297e+07,2.469297e+06,2.469297e+07,2.469297e+06,None,None,None,NaN,None,None,None,ГипроВТИ,27822049,Строительство,124634.0,1657028318,RU,Республика Татарстан,None,NaN,None,None,NaN,None,None,0.0,None,Обыкн-ая,Осн-ой,None,2023-01-21T00:25:00,NaN,Нет информации,NaN,None,NaN,None,NaN,None,None,None,NaN,NaN,None,None,NaN,None,0,SHS3,RU,1000,1000,NaN,None,NaN,0,0,None,NaN,NaN,None,None,108206,90116
4,2.0,2.0,NaN,NaN,NaN,None,2.0,2.0,2.0,0.0,0.0,NaN,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None,None,None,NaN,None,None,None,NaN,NaN,None,None,NaN,NaN,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,S112,None,None,226063,None,None,"""Рабочий"", ЗАО, акции обыкновенные бездокумент...",None,None,Рабочий-2-ао,NaN,1-02-55112-P,2005-04-19T00:00:00,ФСФР,NaN,None,None,None,None,Акция,None,None,NaN,0.0,NaN,None,None,NaN,RU,NaN,RUB,10.00,NaN,NaN,NaN,Погашен,2.456072e+07,2.456072e+06,NaN,NaN,None,None,None,NaN,None,None,None,Рабочий,00336548,Пищевая промышленность и с/х,124635.0,6167008311,RU,Ростовская область,None,NaN,None,None,NaN,None,2025-09-25T00:00:00,0.0,2005-07-15T00:00:00,Обыкн-ая,Осн-ой,None,2025-09-26T10:50:33,NaN,Нет информации,NaN,None,NaN,None,NaN,None,None,None,NaN,NaN,None,None,NaN,None,0,SHS3,RU,1000,1000,NaN,None,NaN,0,0,None,NaN,NaN,None,None,108206,90117

In [4]:
EndOfDayDF = EndOfDay().df
EndOfDayDF.head()

,ask,avge_prce,bid,boardid,boardname,close,convexity,deal_acc,duration,exch,high,isin,last,last_time,last_yield,low,mat_date,mprice,name,open,pvbp,seccode,secname,spread,val,val_usd,vol,vol_lots,yield_agg,yield_ask,yield_average_o12m,yield_average_o2w,yield_bid,yield_swa,currency,fintoolId,id_iss,id_trade_site,add_date,update_date
0,57.95,57.82,57.92,TQBR,T+ Акции и ДР,57.91,NaN,27282.0,NaN,MICEX,58.31,RU0009062285,57.95,2025-12-30T23:49:42,NaN,57.45,<NA>,57.76,AFLT.MICEX,57.91,NaN,AFLT,"Аэрофлот - российские авиалинии ОАО, АО - ФБ...",0.03,819429092.3,10580104.48,14172230.0,1417223.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4200,35154,170,2025-12-30T23:55:00,2025-12-31T07:05:45
1,11.59,11.61,11.42,TQBR,T+ Акции и ДР,11.21,NaN,554.0,NaN,MICEX,12.10,RU0009100176,11.59,2025-12-30T23:49:37,NaN,11.21,<NA>,11.56,BISVP.MICEX,11.21,NaN,BISVP,"Башинформсвязь ОАО, АП - ФБ ММВБ",0.17,4568225.0,58982.89,393500.0,3935.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4215,775000,170,2025-12-30T23:55:06,2025-12-31T07:05:46
2,1588.00,1582.00,1580.00,TQBR,T+ Акции и ДР,1602.00,NaN,306.0,NaN,MICEX,1602.00,RU0009288658,1588.00,2025-12-30T23:48:57.0003,NaN,1550.00,<NA>,1578.00,BRZL.MICEX,1602.00,NaN,BRZL,"Бурятзолото ОАО, АО - ФБ ММВБ",8.00,4899334.0,63258.02,3097.0,3097.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4217,852973,170,2025-12-30T23:55:09,2025-12-31T07:05:46
3,73.40,73.60,72.60,TQBR,T+ Акции и ДР,73.80,NaN,76.0,NaN,MICEX,74.20,RU0009082291,73.40,2025-12-30T23:34:58,NaN,72.40,<NA>,73.40,CHGZ.MICEX,73.40,NaN,CHGZ,"Черногорнефть ОАО, АО - ФБ ММВБ",0.80,422518.0,5455.36,5740.0,574.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4223,853518,170,2025-12-30T23:55:09,2025-12-31T07:05:46
4,962.00,964.50,961.80,TQBR,T+ Акции и ДР,967.60,NaN,24763.0,NaN,MICEX,973.00,RU0009046510,962.20,2025-12-30T23:49:56,NaN,960.40,<NA>,964.20,CHMF.MICEX,969.40,NaN,CHMF,"Северсталь ОАО, АО - ФБ ММВБ T+2",0.20,517712010.2,6684467.53,536742.0,536742.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4226,1069768,170,2025-12-30T23:55:07,2025-12-31T07:05:46

In [5]:
AccruedInterestOnDateDF = AccruedInterestOnDate().df
AccruedInterestOnDateDF.head()

,fintoolId,shiftDays,shiftTypeSource,typeCurrency,date,accruedInterest,accruedInterestPct,currentFaceValue,currentFaceValuePct,calculationType,error,faceValueCurrency,accruedInterestCurrency,faceValueLastKnownDate
0,4000,0,Calendar,<NA>,2025-12-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,<NA>,RUB,RUB,2025-12-31T00:00:00
1,4001,0,Calendar,<NA>,2025-12-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,<NA>,RUB,RUB,2025-12-31T00:00:00
2,4002,0,Calendar,<NA>,2025-12-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,<NA>,RUB,RUB,2025-12-31T00:00:00
3,4003,0,Calendar,<NA>,2025-12-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,<NA>,RUB,RUB,2025-12-31T00:00:00
4,4004,0,Calendar,<NA>,2025-12-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,<NA>,RUB,RUB,2025-12-31T00:00:00

In [6]:
FloaterDataDF = FloaterData().df
FloaterDataDF.head()

,fintoolId,beg_period,end_period,start_point,model_type,date_pub_n,date_pub_type,date_fix_n,date_fix_type,bases
0,11193,2000-12-01T00:00:00,2050-12-01T00:00:00,E,single,NaN,<NA>,10.0,W,"[{""base_no"": 1, ""calc_type"": ""FIX"", ""base_fint..."
1,36325,2009-08-27T00:00:00,2028-09-15T00:00:00,B,single,NaN,<NA>,1.0,W,"[{""base_no"": 1, ""calc_type"": ""FIX"", ""base_fint..."
2,57394,2011-11-21T00:00:00,2028-10-30T00:00:00,B,single,NaN,<NA>,5.0,W,"[{""base_no"": 2, ""calc_type"": ""PER"", ""base_fint..."
3,59702,2013-12-11T00:00:00,2028-11-22T00:00:00,B,single,NaN,<NA>,5.0,C,"[{""base_no"": 2, ""calc_type"": ""FIX"", ""base_fint..."
4,61946,2017-08-18T00:00:00,2044-08-11T00:00:00,B,single,NaN,<NA>,5.0,W,"[{""base_no"": 1, ""calc_type"": ""PER"", ""base_fint..."

In [7]:
FloatersOnPeriodDF = FloatersOnPeriod().df
FloatersOnPeriodDF.head()

,fintoolId,date,accruedInterest,accruedInterestPct,currentFaceValue,currentFaceValuePct,faceValueCurrency,addDate,counter
0,164245,2025-12-31T00:00:00,3.04,0.30,1000.0,100.0,RUB,2025-12-30T06:02:38,1
1,164245,2025-12-31T00:00:00,3.04,0.30,1000.0,100.0,RUB,2025-12-30T06:02:38,331
2,165152,2025-12-31T00:00:00,3.04,0.30,1000.0,100.0,RUB,2025-12-30T06:02:46,1
3,165152,2025-12-31T00:00:00,3.04,0.30,1000.0,100.0,RUB,2025-12-30T06:02:46,331
4,170151,2025-12-31T00:00:00,31.18,3.12,1000.0,100.0,RUB,2025-12-30T06:03:21,2

In [8]:
RUPriceHistoryDF = RUPriceHistory().df
RUPriceHistoryDF.head()

,nickname,fintoolid,fininstid,isincode,regcode,nrdcode,calcdate,val_date,current_fv,faceftname,date_agg,avge_prce,yield_agg,z_wa_mb,durmod_agg,i_wa_mb,method_no,vp_pct,vp_pc,vp_pc_l,vp_pc_h,vp_m1,y_agg_m1,deal_250d,q_m1,r_m1,vp_m2,y_agg_m2,i_vp_m2,sigma_m2,index,beta1_m2,beta0_m2,alpha_m2,gamma_m2,sigma_nu,rho_m2,r_m2,vp_m3,y_agg_m3,dur_agg_m3,z_vp_m3,r_m3,factor1,beta1_m3,factor2,beta2_m3,level_pd,coef_b,risk_b,beta3_m3,is_ontherun,beta4_m3,hhi,beta5_m3,ind_liq,beta6_m3,ind_unliq,beta7_m3,sector,phi_sector,version,valuation_currency,security_type,source,wa_duration,duration_mod,lbound1,ubound1,lbound2,ubound2,lbound3,ubound3,acc_int,wap_ext_zspread,mp3_ext_zspread,id,no_history_found,not_valid_code,calcDateTime,counter,rn
0,Россия-2030-11т,6043,7080,XS0114288789,SK-0-CM-128,XS0114288789,2025-12-01T00:00:00,2025-12-01T00:00:00,0.045,USD,2030-03-31T00:00:00,0.0,0.0,0.0,<NA>,0.0,1.0,102.105992,0.045948,101.096305,103.115680,102.105992,6.592308,0.0,0.0,0.0,102.105992,6.592308,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,102.105992,6.592308,0.0,-0.3770,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Государственные,0.0,2,USD,euro_bond,3,0.0,1.987325,101.096305,103.115680,101.096305,103.115680,101.096305,103.115680,0.000572,0.0,0.0,6043,<NA>,<NA>,<NA>,46061,7468
1,Россия-2030-11т,6043,7080,XS0114288789,SK-0-CM-128,XS0114288789,2025-12-02T00:00:00,2025-12-02T00:00:00,0.045,USD,2030-03-31T00:00:00,0.0,0.0,0.0,<NA>,0.0,1.0,102.219667,0.045999,101.468718,102.970615,102.219667,6.535773,0.0,0.0,0.0,102.219667,6.535773,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,102.219667,6.535773,0.0,-0.3941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Государственные,0.0,2,USD,euro_bond,3,0.0,1.986621,101.468718,102.970615,101.468718,102.970615,101.468718,102.970615,0.000581,0.0,0.0,6043,<NA>,<NA>,<NA>,46061,7469
2,Россия-2030-11т,6043,7080,XS0114288789,SK-0-CM-128,XS0114288789,2025-12-03T00:00:00,2025-12-03T00:00:00,0.045,USD,2030-03-31T00:00:00,0.0,0.0,0.0,<NA>,0.0,1.0,102.363843,0.046064,101.994474,102.733212,102.363843,6.464416,0.0,0.0,0.0,102.363843,6.464416,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,102.363843,6.464416,0.0,-0.3487,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Государственные,0.0,2,USD,euro_bond,3,0.0,1.986407,101.994474,102.733212,101.994474,102.733212,101.994474,102.733212,0.000591,0.0,0.0,6043,<NA>,<NA>,<NA>,46061,7470
3,Россия-2030-11т,6043,7080,XS0114288789,SK-0-CM-128,XS0114288789,2025-12-04T00:00:00,2025-12-04T00:00:00,0.045,USD,2030-03-31T00:00:00,0.0,0.0,0.0,<NA>,0.0,1.0,102.446578,0.046101,101.436442,103.456715,102.446578,6.422891,0.0,0.0,0.0,102.446578,6.422891,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,102.446578,6.422891,0.0,-0.3258,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Государственные,0.0,2,USD,euro_bond,3,0.0,1.985206,101.436442,103.456715,101.436442,103.456715,101.436442,103.456715,0.000600,0.0,0.0,6043,<NA>,<NA>,<NA>,46061,7471
4,Россия-2030-11т,6043,7080,XS0114288789,SK-0-CM-128,XS0114288789,2025-12-05T00:00:00,2025-12-05T00:00:00,0.045,USD,2030-03-31T00:00:00,0.0,0.0,0.0,<NA>,0.0,1.0,104.554851,0.047050,103.564887,105.544815,104.554851,5.415878,0.0,0.0,0.0,104.554851,5.415878,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,104.554851,5.415878,0.0,-0.4740,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Государственные,0.0,2,USD,euro_bond,3,0.0,2.016322,103.564887,105.544815,103.564887,105.544815,103.564887,105.544815,0.000609,0.0,0.0,6043,<NA>,<NA>,<NA>,46061,7472

In [9]:
ExchangeTreeDF = ExchangeTree().df
ExchangeTreeDF.head()

,id,id_parent,shortname_rus,shortname_eng,fullname_rus,fullname_eng,sort_order,update_date,counter,rn
0,1,0,РТС,RTS,Московская Биржа - РТС,RTS,12,2020-12-28T17:03:09,242,17
1,2,1,РТС,RTS,РТС индексы,RTS indexes,2,2020-12-28T17:03:09,242,4
2,8,1,ФОРТС,FORTS,FORTS,FORTS,8,2020-12-28T17:03:09,242,11
3,9,0,"ПАО ""СПБ""",PJSC «SPB»,"ПАО ""СПБ""",PJSC «SPB»,20,2020-12-28T17:03:09,242,21
4,11,0,МБ,MX,Московская Биржа,Moscow Exchange,11,2020-12-28T17:03:09,242,16

In [10]:
MoexSecuritiesDF = MoexSecurities().df
MoexSecuritiesDF.head()

,id_iss,secid,boardid,board_title,board_group,board_group_title,market,engine,short_name,isin,cfi_ifx,cfi_name,lot_size,expiration_date,currency,emitent_code,emitent_name,market_sector,min_price_increment,fintoolid,reg_code,update_date,counter,rn
0,3107707,A-RM,LIQB,Продажа обеспечения бирж.рынок - безадрес.,stock_mamc_liq,Безадресные сделки с ЦК,mamc,stock,<NA>,US00846U1016,ESXXXX,Акции / обыкновенные,1,<NA>,<NA>,<NA>,<NA>,<NA>,0.01,127649.0,<NA>,2021-11-01T05:02:21.84541,239384,101898
1,3107886,A-RM,PSSD,РПС: Ин.Акции (USD) - адрес.,stock_foreignndm_usd,РПС: Ин.Акции (USD) - адрес.,foreignndm,stock,<NA>,US00846U1016,ESXXXX,Акции / обыкновенные,1,<NA>,RUB,<NA>,<NA>,<NA>,0.01,127649.0,<NA>,2022-12-22T09:56:16.326722,239384,102077
2,3107946,A-RM,FTEQ,РПС с ЦК: Ин.Акции и ДР - адрес.,stock_foreign_ccp,РПС с ЦК: Ин.Акции и ДР - адрес.,foreignndm,stock,<NA>,US00846U1016,ESXXXX,Акции / обыкновенные,1,<NA>,<NA>,<NA>,<NA>,<NA>,1.00,127649.0,<NA>,2021-11-01T05:03:14.845768,239384,102137
3,3108028,A-RM,EQRE,РЕПО с ЦК 1 день (EUR) - безадрес.,stock_ccp_d_eur,РЕПО с ЦК 1 день (EUR) - безадрес.,ccp,stock,<NA>,US00846U1016,ESXXXX,Акции / обыкновенные,1,<NA>,<NA>,<NA>,<NA>,<NA>,0.01,127649.0,<NA>,2021-11-01T05:03:33.845899,239384,102219
4,3108069,A-RM,LIQR,РЕПО с ЦК: Урегулирование - безадрес.,stock_ccp_liq,РЕПО с ЦК: Урегулирование - безадрес.,ccp,stock,<NA>,US00846U1016,ESXXXX,Акции / обыкновенные,1,<NA>,<NA>,<NA>,<NA>,<NA>,0.01,127649.0,<NA>,2021-11-01T05:03:42.845958,239384,102260

In [11]:
CurrencyRateDF = CurrencyRate().df
CurrencyRateDF.head()

        rate  endOfDayRate error from   to
0  21.300700     21.300700  <NA>  AED  RUB
1        NaN           NaN  <NA>  AFN  RUB
2        NaN           NaN  <NA>  ALL  RUB
3   0.205126      0.205126  <NA>  AMD  RUB
4        NaN           NaN  <NA>  ANG  RUB

##### Шаг 1.1. RuData MOEX stage

In [12]:
HistoryStockBondsDF = HistoryStockBonds().df
HistoryStockBondsDF.head()

,boardname,regnumber,isin,matdate,listname,facevalue,currencyid,volume,value,numtrades,prev,prevlegalcloseprice,openperiod,legalopenprice,legalcloseprice,closeperiod,waprice,trendclose,trendclspr,trendwap,trendwappr,openval,closeval,highbid,lowoffer,bid,offer,yieldatwap,yieldclose,accint,duration,marketprice,marketprice2,admittedquote,issuesize,mpvaltrd,mp2valtrd,admittedvalue,marketprice3,marketprice3tradesvalue,type,lastprice,iricpiclose,beiclose,couponpercent,couponvalue,buybackdate,lasttradedate,cbrclose,yieldtooffer,yieldlastcoupon,offerdate,faceunit,engine,market,boardid,decimals,high,low,open,close,secid,shortname,tradedate,tradingsession,counter
0,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,511,39929503.27,13,99.8500,99.8500,NaN,<NA>,99.9986,<NA>,99.8869,0.1486,0.15,0.1231,0.12,78302.87,78227.30,100.0965,99.7993,99.7000,99.8000,7.84,7.77,2533.0463,NaN,<NA>,99.8869,<NA>,240419,0.0,39929503.27,<NA>,99.8869,39929503.27,corporate_bond,99.9986,NaN,NaN,7.63,38.23,<NA>,2025-12-01T00:00:00,<NA>,NaN,NaN,<NA>,USD,stock,bonds,TQCB,4,100.0952,99.8000,100.0952,99.9986,BYM000001818,РесБел 331,2025-12-01T00:00:00,3,NaN
1,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,6,465826.67,4,99.9986,99.9986,NaN,<NA>,99.9999,<NA>,99.9165,0.0013,NaN,0.0296,0.03,77314.42,155405.24,100.0003,99.5003,99.8628,99.9999,7.82,7.76,2532.2565,NaN,<NA>,99.8872,<NA>,240419,0.0,40395329.94,<NA>,99.9073,29539774.43,corporate_bond,99.9999,NaN,NaN,7.63,38.23,<NA>,2025-12-02T00:00:00,<NA>,NaN,NaN,<NA>,USD,stock,bonds,TQCB,4,99.9999,99.5003,99.5003,99.9999,BYM000001818,РесБел 331,2025-12-02T00:00:00,3,NaN
2,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,602,46527262.33,41,99.9999,99.9999,NaN,<NA>,99.4800,<NA>,99.7737,-0.4999,-0.50,-0.1428,-0.14,774631.00,308303.14,100.2326,99.3893,99.0180,99.5000,7.93,8.12,2540.6305,NaN,<NA>,99.7825,<NA>,240419,0.0,45140053.06,<NA>,99.7825,45140053.06,corporate_bond,99.5000,NaN,NaN,7.63,38.23,<NA>,2025-12-03T00:00:00,<NA>,NaN,NaN,<NA>,USD,stock,bonds,TQCB,4,100.2326,99.4000,100.0000,99.5000,BYM000001818,РесБел 331,2025-12-03T00:00:00,3,NaN
3,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,17,1311728.48,11,99.5000,99.4800,NaN,<NA>,98.9997,<NA>,98.9801,-0.5000,-0.50,-0.7936,-0.80,77190.39,77176.04,99.0262,98.5000,98.0200,98.9900,8.50,8.49,2573.0687,NaN,<NA>,99.7644,<NA>,240419,0.0,46220643.11,<NA>,99.2067,1851192.97,corporate_bond,99.0000,NaN,NaN,7.63,38.23,<NA>,2025-12-04T00:00:00,<NA>,NaN,NaN,<NA>,USD,stock,bonds,TQCB,4,99.0227,98.5003,99.0184,99.0000,BYM000001818,РесБел 331,2025-12-04T00:00:00,3,NaN
4,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,37,2837223.42,8,99.0000,98.9997,NaN,<NA>,99.6163,<NA>,99.6244,0.7629,0.77,0.6443,0.65,76678.39,76788.30,99.9001,99.6162,99.0000,99.8882,8.04,7.94,2556.6431,NaN,<NA>,99.4466,<NA>,240419,0.0,3764349.78,<NA>,99.5298,3146814.43,corporate_bond,99.7629,NaN,NaN,7.63,38.23,<NA>,2025-12-05T00:00:00,<NA>,NaN,NaN,<NA>,USD,stock,bonds,TQCB,4,99.7629,99.6162,99.6201,99.7629,BYM000001818,РесБел 331,2025-12-05T00:00:00,3,NaN

In [13]:
HistoryStockSharesDF = HistoryStockShares().df
HistoryStockSharesDF.head()

,boardname,regnumber,isin,listname,facevalue,currencyid,prevlegalcloseprice,prev,legalopenprice,openperiod,closeperiod,openval,closeval,legalcloseprice,trendclose,trendclspr,highbid,bid,offer,lowoffer,waprice,trendwap,trendwappr,volume,marketprice,marketprice2,mp2valtrd,mpvaltrd,value,numtrades,issuesize,admittedquote,admittedvalue,monthlycapitalization,dailycapitalization,marketprice3,marketprice3tradesvalue,type,closeauctionprice,waval,lastprice,engine,market,boardid,decimals,high,low,open,close,secid,shortname,tradedate,tradingsession,counter
0,Поставка по СК (акции),1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,NaN,72.50,<NA>,NaN,<NA>,769216.0,17675.0,NaN,-1.80,-2.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26660,<NA>,NaN,0.0,0.0,1884862.0,30,92645451,<NA>,<NA>,NaN,NaN,NaN,0.0,common_share,NaN,0.0,NaN,stock,shares,SPEQ,6,70.70,70.70,70.70,70.70,ABIO,iАРТГЕН ао,2025-12-19T00:00:00,3,NaN
1,Поставка по СК (акции),1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,NaN,72.50,<NA>,NaN,<NA>,769216.0,17675.0,NaN,-1.80,-2.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26660,<NA>,NaN,0.0,0.0,1884862.0,30,92645451,<NA>,<NA>,NaN,NaN,NaN,0.0,common_share,NaN,0.0,NaN,stock,shares,SPEQ,6,70.70,70.70,70.70,70.70,ABIO,iАРТГЕН ао,2025-12-19T00:00:00,1,NaN
2,Т+: Акции и ДР - безадрес.,1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,69.66,69.80,<NA>,NaN,<NA>,704.2,691.0,69.22,-0.70,-1.00,71.00,68.96,69.16,68.00,69.26,-0.36,-0.52,256420,<NA>,69.16,4248087.4,0.0,17758629.0,2329,92645451,<NA>,<NA>,6.442565e+09,6.407359e+09,69.16,4248087.4,common_share,69.22,0.0,69.10,stock,shares,TQBR,2,70.42,68.56,70.42,69.10,ABIO,iАРТГЕН ао,2025-12-01T00:00:00,3,NaN
3,Т+: Акции и ДР - безадрес.,1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,69.22,69.10,<NA>,NaN,<NA>,689.0,1376.8,68.64,-0.26,-0.38,69.62,68.68,68.82,66.88,68.80,-0.46,-0.66,93790,<NA>,68.82,4763044.8,0.0,6452833.4,1156,92645451,<NA>,<NA>,6.442565e+09,6.375860e+09,68.82,4763044.8,common_share,68.64,0.0,68.84,stock,shares,TQBR,2,69.34,68.46,68.90,68.84,ABIO,iАРТГЕН ао,2025-12-02T00:00:00,3,NaN
4,Т+: Акции и ДР - безадрес.,1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,68.64,68.84,<NA>,NaN,<NA>,1374.8,686.0,68.38,-0.24,-0.35,69.10,68.48,68.58,67.72,68.34,-0.46,-0.67,51380,<NA>,68.44,1932681.6,0.0,3511571.2,602,92645451,<NA>,<NA>,6.442565e+09,6.340655e+09,68.44,1932681.6,common_share,68.38,0.0,68.60,stock,shares,TQBR,2,68.76,68.00,68.74,68.60,ABIO,iАРТГЕН ао,2025-12-03T00:00:00,3,NaN

In [14]:
HistoryStockNdmDF = HistoryStockNdm().df
HistoryStockNdmDF.head()

,boardname,closeval,currencyid,facevalue,isin,issuesize,listname,matdate,numtrades,openval,prev,regnumber,trendclose,trendclspr,trendwap,trendwappr,type,value,volume,waprice,yieldatwap,yieldclose,lastprice,iricpiclose,beiclose,couponpercent,couponvalue,buybackdate,lasttradedate,cbrclose,yieldtooffer,yieldlastcoupon,offerdate,faceunit,engine,market,boardid,decimals,high,low,open,close,secid,shortname,tradedate,tradingsession,counter
0,РПС: Акции - адрес.,10575.20,SUR,0.09,RU000A0DQZE3,9650000000,1,<NA>,1,10575.20,12.532,1-05-01669-A,0.687,NaN,-0.083,-0.62,common_share,10575.20,800,13.203,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,stock,ndm,PSEQ,3,13.219,13.219,13.219,13.219,AFKS,Система ао,2025-12-02T00:00:00,3,NaN
1,РПС с ЦК: Акции и ДР - адрес.,125038.80,SUR,0.09,RU000A0DQZE3,9650000000,1,<NA>,1,125038.80,12.960,1-05-01669-A,0.342,NaN,0.169,1.29,common_share,125038.80,9400,13.286,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,stock,ndm,PTEQ,3,13.302,13.302,13.302,13.302,AFKS,Система ао,2025-12-01T00:00:00,3,NaN
2,РПС с ЦК: Акции и ДР - адрес.,11243.93,SUR,0.09,RU000A0DQZE3,9650000000,1,<NA>,2,11243.93,13.302,1-05-01669-A,-0.258,NaN,0.334,2.58,common_share,22487.86,1724,13.286,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,stock,ndm,PTEQ,3,13.044,13.044,13.044,13.044,AFKS,Система ао,2025-12-04T00:00:00,3,NaN
3,РПС с ЦК: Акции и ДР - адрес.,26626.00,SUR,0.09,RU000A0DQZE3,9650000000,1,<NA>,2,26626.00,13.044,1-05-01669-A,0.269,NaN,0.286,2.15,common_share,53252.00,4000,13.572,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,stock,ndm,PTEQ,3,13.313,13.313,13.313,13.313,AFKS,Система ао,2025-12-05T00:00:00,3,NaN
4,РПС с ЦК: Акции и ДР - адрес.,48261.50,SUR,0.09,RU000A0DQZE3,9650000000,1,<NA>,2,48261.50,13.313,1-05-01669-A,0.476,NaN,0.223,1.64,common_share,96523.00,7000,13.795,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,stock,ndm,PTEQ,3,13.789,13.789,13.789,13.789,AFKS,Система ао,2025-12-08T00:00:00,3,NaN

In [15]:
HistoryStockCcpDF = HistoryStockCcp().df
HistoryStockCcpDF.head()

,accint,admittedquote,admittedvalue,bid,boardname,closeperiod,closeval,currencyid,duration,facevalue,highbid,isin,issuesize,legalcloseprice,legalopenprice,listname,lowoffer,marketprice,marketprice2,marketprice3,marketprice3tradesvalue,matdate,mp2valtrd,mpvaltrd,numtrades,offer,openperiod,openval,prev,prevlegalcloseprice,regnumber,trendclose,trendclspr,trendwap,trendwappr,type,value,volume,waprice,yieldatwap,yieldclose,engine,market,boardid,decimals,high,low,open,close,secid,shortname,tradedate,tradingsession,counter
0,NaN,<NA>,<NA>,<NA>,РЕПО с ЦК 1 день - безадрес.,<NA>,99948.81,SUR,<NA>,0.1,NaN,RU000A0JNAB6,92645451,<NA>,<NA>,2,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,4,<NA>,<NA>,116809.55,15.0,<NA>,1-01-08902-A,NaN,<NA>,NaN,NaN,common_share,651860.72,12333,15.00,<NA>,<NA>,stock,ccp,EQRP,4,15.0,15.0,15.0,15.0,ABIO,iАРТГЕН ао,2025-12-01T00:00:00,3,NaN
1,NaN,<NA>,<NA>,<NA>,РЕПО с ЦК 1 день - безадрес.,<NA>,333255.13,SUR,<NA>,0.1,NaN,RU000A0JNAB6,92645451,<NA>,<NA>,2,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,2,<NA>,<NA>,116166.22,15.0,<NA>,1-01-08902-A,NaN,<NA>,NaN,NaN,common_share,449421.35,8550,15.00,<NA>,<NA>,stock,ccp,EQRP,4,15.0,15.0,15.0,15.0,ABIO,iАРТГЕН ао,2025-12-02T00:00:00,3,NaN
2,NaN,<NA>,<NA>,<NA>,РЕПО с ЦК 1 день - безадрес.,<NA>,100025.57,SUR,<NA>,0.1,NaN,RU000A0JNAB6,92645451,<NA>,<NA>,2,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,4,<NA>,<NA>,109981.22,15.0,<NA>,1-01-08902-A,NaN,<NA>,-1.72,NaN,common_share,638412.30,12248,13.28,<NA>,<NA>,stock,ccp,EQRP,4,15.0,5.0,5.0,15.0,ABIO,iАРТГЕН ао,2025-12-03T00:00:00,3,NaN
3,NaN,<NA>,<NA>,<NA>,РЕПО с ЦК 1 день - безадрес.,<NA>,139459.70,SUR,<NA>,0.1,NaN,RU000A0JNAB6,92645451,<NA>,<NA>,2,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,4,<NA>,<NA>,162876.44,15.0,<NA>,1-01-08902-A,0.2,<NA>,-0.44,NaN,common_share,730706.37,14042,12.84,<NA>,<NA>,stock,ccp,EQRP,4,15.2,5.0,5.0,15.2,ABIO,iАРТГЕН ао,2025-12-04T00:00:00,3,NaN
4,NaN,<NA>,<NA>,<NA>,РЕПО с ЦК 1 день - безадрес.,<NA>,100031.34,SUR,<NA>,0.1,NaN,RU000A0JNAB6,92645451,<NA>,<NA>,2,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,4,<NA>,<NA>,104998.92,15.2,<NA>,1-01-08902-A,-0.1,<NA>,2.26,NaN,common_share,698650.69,13361,15.10,<NA>,<NA>,stock,ccp,EQRP,4,15.1,15.1,15.1,15.1,ABIO,iАРТГЕН ао,2025-12-05T00:00:00,3,NaN

##### Шаг 2. RuData transform

In [18]:
Prices = FintoolReferenceDataDF[['isincode', 'nickname', 'fintooltype', 'fintoolid', 'faceftname']]\
.rename(columns={
    "isincode": "isin",
    "nickname": "name",
    "fintoolid": "fintool",
    "fintooltype": "type",
    "faceftname": "currency_tmp"
})
Prices = Prices[~(Prices["isin"].isna() | (Prices["isin"].isin(['None', ''])))]
InterestDF = AccruedInterestOnDateDF[['fintoolId', 'accruedInterest', 'currentFaceValue']].set_index('fintoolId')
InterestDF.update(FloatersOnPeriodDF.groupby('fintoolId').last())
Prices = Prices.merge(
    InterestDF, how="left", left_on="fintool", right_index=True)
Prices = Prices.rename(columns={
    'accruedInterest': 'interest',
    'currentFaceValue': 'principal'})

###### Шаг 2.1.1. CBR

In [19]:
from src.sources.cbr.CBR_Soap import CBR_Soap

headers = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.6834.111 Safari/537.36',
           'Accept-Encoding': 'gzip, deflate',
           'Accept': '*/*',
           'Connection': 'keep-alive'}
cbr_disc = CBR_Soap()\
.get_discounts(date=last_work_date_month_str)[['ISIN', 'от 1 месяца до 180 дней_Beg']]\
.rename(columns={'от 1 месяца до 180 дней_Beg': 'cbr_discount_6d'})\
.groupby('ISIN')\
.last()\
.reset_index()

GET http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx?wsdl using urllib2 3.10
GET http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx?wsdl using urllib2 3.10
GET http://www.cbr.ru/secinfo/secinfo.asmx?wsdl using urllib2 3.10
GET http://www.cbr.ru/secinfo/secinfo.asmx?wsdl using urllib2 3.10

/Users/alexander/PycharmProjects/insurance_mine/src/sources/cbr/CBR_Soap.py:212: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  disc = pd.concat([disc, pd.DataFrame(index=[0], data=d)], axis=0)

In [20]:
Prices = Prices.merge(cbr_disc, how='left', left_on='isin', right_on='ISIN')
Prices['cbr_discount_6d'] = Prices['cbr_discount_6d'].fillna(1.0)

###### Шаг 2.1.2. nationalclearingcentre Рыночные риски

In [21]:
currMarketRatesResponse = requests.get(f'https://www.nationalclearingcentre.ru/api/v1/rates/fondMarketRates?action=xls&xls=1&lang=ru&date={last_work_date_month.strftime("%d.%m.%Y")}', headers=headers)
currMarketRates = pd.read_excel(currMarketRatesResponse.content,header=2)
currMarketRates = currMarketRates[(currMarketRates['Диапазон']==1)&(currMarketRates['Ставка риска падения цены,%']!=100)].reset_index(drop=True)
currMarketRates = currMarketRates\
.merge(MoexSecuritiesDF[['secid', 'isin']], how='left', left_on='Инструмент', right_on='secid')\
.groupby('isin')\
.last()\
.reset_index()
currMarketRates = currMarketRates[currMarketRates['isin'].str.match('([A-Z]{2})([A-Z0-9]{9})([0-9]{1})$')]
currMarketRates = currMarketRates[
    (currMarketRates['Диапазон']==1) & (currMarketRates['Ставка риска падения цены,%'] != 100)
]
currMarketRates = currMarketRates[['isin', 'Ставка риска падения цены,%']]\
.rename(columns={'Ставка риска падения цены,%': 'Risk rate'})
# Формула из п.12.1 Методики НКЦ определения риск-параметров
currMarketRates['discount_ncc'] = currMarketRates['Risk rate'].apply(lambda x: min(30, ceil(x/np.sqrt(2)))/100)

/var/folders/g4/mpm4njl93p547kbhxbvqlm480000gn/T/ipykernel_8964/2665819705.py:2: FutureWarning: Passing bytes to 'read_excel' is deprecated and will be removed in a future version. To read from a byte string, wrap it in a `BytesIO` object.
  currMarketRates = pd.read_excel(currMarketRatesResponse.content,header=2)

In [22]:
Prices = Prices.merge(currMarketRates[['isin', 'discount_ncc']], how='left', on='isin')
Prices['discount_ncc'] = Prices['discount_ncc'].fillna(1.0)

###### Шаг 2.1.3. nationalclearingcentre Параметры ценных бумаг

In [23]:
securInfoResponse = requests.get(f'https://www.nationalclearingcentre.ru/api/v1/rates/securInfo?action=xls&lang=ru&settleDate={last_work_date_month.strftime("%d.%m.%Y")}', headers=headers)
securInfo = pd.read_excel(securInfoResponse.content, header=2)[['ISIN ЦБ', 'Принимается в обеспеч.']]\
.rename(columns={
    'ISIN ЦБ': 'isin',
    'Принимается в обеспеч.': 'ncc_collateral'
})\
.dropna()\
.groupby('isin')\
.last()\
.reset_index()
securInfo = securInfo[securInfo['ncc_collateral']=='Да']

/var/folders/g4/mpm4njl93p547kbhxbvqlm480000gn/T/ipykernel_8964/2374884689.py:2: FutureWarning: Passing bytes to 'read_excel' is deprecated and will be removed in a future version. To read from a byte string, wrap it in a `BytesIO` object.
  securInfo = pd.read_excel(securInfoResponse.content, header=2)[['ISIN ЦБ', 'Принимается в обеспеч.']]\

In [24]:
Prices = Prices.merge(securInfo, how='left', on='isin')
Prices['ncc_collateral'] = Prices['ncc_collateral'].fillna('Нет')

##### Шаг 2.2. RuData transform

RU Data (ЦЦ НРД)

In [25]:
RUPriceHistoryLast = RUPriceHistoryDF.groupby('isincode').last().rename(columns={
    'vp_pct': 'clean_price_pct',
    'vp_pc': 'clean_price',
    'acc_int': 'InterestHistory'
}).reset_index()
ru_price = RUPriceHistoryLast[['isincode', 'clean_price_pct', 'clean_price', 'InterestHistory']].merge(
    Prices[['isin', 'type', 'interest']], left_on='isincode', right_on='isin')
ccnrd_bonds_idx = ru_price["type"]=='Облигация'
ru_price.loc[ccnrd_bonds_idx, "InterestHistory"] = ru_price.loc[ccnrd_bonds_idx, "InterestHistory"].combine_first(ru_price.loc[ccnrd_bonds_idx, "interest"])
ru_price.loc[ccnrd_bonds_idx, "price"] = ru_price.loc[ccnrd_bonds_idx, "clean_price"] + ru_price.loc[ccnrd_bonds_idx, "InterestHistory"].fillna(0)
ru_price.loc[~ccnrd_bonds_idx, "price"] = ru_price.loc[~ccnrd_bonds_idx, "clean_price"]
ru_price["source"] = 'RU Data (ЦЦ НРД)'

End of Day

In [26]:
exch_prices = EndOfDayDF.merge(
    ExchangeTreeDF[['id', 'fullname_rus']], how='left', left_on='id_trade_site', right_on='id')[['fintoolId', 'last', 'fullname_rus', 'currency']]
exch_prices["source"] = exch_prices['fullname_rus'].apply(lambda x: 'RU Data (' + str(x) + ')')
exch_prices = exch_prices\
.rename(columns={
    'fintoolId': 'fintool',
    'last': 'price_ex'
})
exch_prices = exch_prices.merge(Prices[["fintool", "isin", "type", "principal", "interest"]], how='inner')
exch_prices[['price_ex', 'principal', 'interest']] = exch_prices[['price_ex', 'principal', 'interest']].fillna(0)

exch_bonds = exch_prices['type']=='Облигация'
exch_prices.loc[exch_bonds, "clean_price_pct"] = exch_prices.loc[exch_bonds, "price_ex"]
exch_prices.loc[exch_bonds, "clean_price"] = exch_prices.loc[exch_bonds, "clean_price_pct"]/100 * exch_prices.loc[exch_bonds, "principal"]
exch_prices.loc[exch_bonds, "price"] = exch_prices.loc[exch_bonds, "clean_price"] + exch_prices.loc[exch_bonds, "interest"]

exch_prices.loc[~exch_bonds, 'clean_price'] = exch_prices.loc[~exch_bonds, 'price_ex']
exch_prices.loc[~exch_bonds, 'price'] = exch_prices.loc[~exch_bonds, 'price_ex']

exch_shares = exch_prices['type']=='Акция'
exch_prices.loc[~exch_shares, "currency"] = None

##### Шаг 3. Moex

In [27]:
TransformHistoryStockBonds = HistoryStockBondsDF.groupby("isin")['close'].last().rename("price").reset_index()
TransformHistoryStockShares = (
    HistoryStockSharesDF
    .groupby("isin")
    [['close', 'currencyid']]
    .last()
    .rename(columns={
        'close': 'price',
        'currencyid': 'currency'
    })
    .reset_index()
    .replace('SUR', 'RUB')
)
TransformHistoryStockNdm = HistoryStockNdmDF.groupby("isin")['close'].last().rename("price").reset_index()
TransformHistoryStockCcp = HistoryStockCcpDF.groupby("isin")['close'].last().rename("price").reset_index()
HistoryStock = pd.concat(
    [TransformHistoryStockBonds, TransformHistoryStockShares, TransformHistoryStockNdm, TransformHistoryStockCcp]
).groupby('isin').last().reset_index()
HistoryStock['source'] = 'RU Data (MOEX)'

#### Шаг 4. Finish

In [28]:
source_prices = pd.concat([
    ru_price[["isin", "clean_price_pct", "clean_price", "price", "source"]],
    exch_prices[["isin", "clean_price_pct", "clean_price", "price", "source", "currency"]],
    HistoryStock
])
result = Prices.merge(
    source_prices,
    how='inner',
    on='isin',
)

Currency

In [29]:
result['currency'] = result['currency'].combine_first(result['currency_tmp'])
result = result.merge(
    CurrencyRateDF[CurrencyRateDF['to']=='RUB'][['from', 'rate']], how='left', left_on='currency', right_on='from'
).drop(columns=['from'])

In [30]:
result['fx_rate'] = result['rate']
result.loc[result['currency']=='RUB', 'fx_rate'] = 1
result['export_timestamp'] = dt.now().replace(microsecond=0)
result['report_date'] = pd.to_datetime(last_day_month)
result['source'] = result['source'].replace('nan', '').fillna('')
result['name'] = result['name'].replace('nan', '').fillna('')
result['type'] = result['type'].replace('nan', '').fillna('')
result['currency'] = result['currency'].replace('nan', '').fillna('')
result['fintool'] = result['fintool'].astype(int)
result = result.sort_values('isin')[["isin", "name", "type", "fintool", "currency", "interest", "principal", "fx_rate", "cbr_discount_6d", "discount_ncc", "ncc_collateral", "clean_price_pct", "clean_price", "price", "source", "export_timestamp", "report_date"]]

##### Шаг 4.2. Write excel

In [32]:
result.to_csv('./data/output/prices.csv', index=False, sep='\t', header=True)
CurrencyRateDF.to_csv('./data/output/currency.csv', index=False, sep='\t', header=True)

In [33]:
from src.utils.send_email import main
main("prices.csv", "currency.csv")