File: prices.ipynb\
Author: alexkobz\
Date: 08-10-2024\
Task: DSRFU-298

#### Шаг 0. Импорт и получение токена

In [2]:
import requests
import pandas as pd
import numpy as np
import nest_asyncio; nest_asyncio.apply()

# from src.utils.clickhouse_client import client

from datetime import datetime as dt
from math import ceil
from src.utils.get_date import last_day_month, last_day_month_str, last_work_date_month, last_work_date_month_str

# последний день месяца
REPORT_DATE = last_day_month
REPORT_DATE_STR = last_day_month_str
# увеличиваем количество столбцов и строк для просмотра
pd.set_option('display.max_rows', 200, 'display.max_columns', 200)
REPORT_DATE

Unexpected Http Driver Exception

Error HTTPConnectionPool(host='host.docker.internal', port=8124): Max retries exceeded with url: /? (Caused by NameResolutionError("HTTPConnection(host='host.docker.internal', port=8124): Failed to resolve 'host.docker.internal' ([Errno 8] nodename nor servname provided, or not known)")) executing HTTP request attempt 1 (http://host.docker.internal:8124)

datetime.date(2026, 3, 31)

In [3]:
from src.sources.rudata.RuDataMethod import Account, FintoolReferenceData, EndOfDay, AccruedInterestOnDate, FloaterData, FloatersOnPeriod, RUPriceHistory, ExchangeTree, MoexSecurities, CurrencyRate, HistoryStockBonds, HistoryStockShares, HistoryStockNdm
Account()

#### Шаг 1. RuData

##### Шаг 1.0. RuData stage

In [4]:
FintoolReferenceDataDF = FintoolReferenceData().df
FintoolReferenceDataDF.head()

,facevalue_m,faceftname_m,sumissuevol_m,summarketvol_m,numcoupons_m,nrdcode,regcode_m,regdate_m,regdistdate_m,begdistdate_m,enddistdate_m,endmtydate_m,daysall_m,fullname_nrd,rpregorg_nrd,rpstate_nrd,issuenumber,currentfacevalue_nrd,isqualified_nrd,bondseries,islombardcbr_nrd,numcoupons_nrd,facevalue_nrd,faceftname_nrd,summarketvol_nrd,regcode_nrd,regdate_nrd,regorg_nrd,begdistdate_nrd,daysall_nrd,enddistdate_nrd,endmtydate_nrd,regdistdate_nrd,sumissuevol_nrd,drqty,isincodebase_nrd,nrdcompcode,shqty,summarketvolorig_nrd,issuername_nrd,planmtydate_nrd,firstcoupondate_nrd,depositary_nrd,registrar_nrd,placeprice_nrd,micexlist_nrd,minlot_nrd,formarketbonds_nrd,registraracctype_nrd,registraracctypedate_nrd,facialacc_nrd,acc_open_date_nrd,fraction_nrd,specialized_depo_nrd,cmp_code_nsd_issuer_nrd,cmp_code_nsd_managing_nrd,ratetypenamerus_nrd,ratetypenameeng_nrd,coupontypename_nrd,base_month,base_year,basis_nrd,sectypenamerus_nrd,sectypenameeng_nrd,secformnamerus_nrd,secformnameeng_nrd,sectypenamebr_nrd,secstaterus_nrd,secstateeng_nrd,placementtype_nrd,share_category_name_nrd,share_category_name_en_nrd,dr_category_name_nrd,dr_category_name_en_nrd,company_state_name_nrd,rate_type_id,cp_type_id,coupon_period_base_id,sec_type_id,sec_form_id,sec_state_id,placement_type_id,share_category_id,dr_category_mn,company_state_mn,sector4212u,sna2008,fullname_en_nrd,seniorityname,fintoolid,moex_code,moex_name,fullname,isin144a,isincode,nickname,progfintoolid,regcode,regdate,regorg,amortisedmty,basis,bondstructuralpar,cfi,coupontype,fintooltype,guaranteeamount,guaranteetype,haveoffer,isconvertible,isguaranteed,maturitygroup,securitization,accruedintcalctype,country,couponperyear,faceftname,facevalue,guarantval,havedefault,numcoupons,status,sumissueval,sumissuevol,summarketval,summarketvol,borrowername,borrowerokpo,borrowersector,borroweruid,borrowerinn,borrowercountry,borrowerregionname,issuername,issuerokpo,issuersector,issueruid,issuerinn,issuercountry,issuerregionname,assetssector,numguarantors,begdistdate,begmtydate,daysall,enddistdate,endmtydate,privatedist,regdistdate,securitytype,securitykind,nominaltype,update_time,isregion,nsd_service,raterevisionsperyear,floatratename,issubordinated,note,listing_level,havecovenant,haverepayment,haveindexedfv,numdecimals,couponperiod,ismatched,firstcoupondate,couponrate,iscomplicated,available_for_unqualified,sec_type_br_code,original_country,qualified_test_id,qualified_test_id_tm,base_asset_fintoolid,isqualified,listing_level_spb,have_mm_moex,have_mm_spb,beg_book_date,seniority,tradesite,current_coupontype,profit_type,counter,rn
0,3.0,3.0,3.0,3.0,3.0,RU000A108TK6,3.0,3.0,3.0,3.0,3.0,3.0,3.0,Структурные процентные дисконтные неконвертиру...,Небанковская кредитная организация акционерное...,Зарегистрирован/Представлен,005,1000.0,1.0,001Р-05,0.0,1.0,1000.0,RUB,50000.0,6-05-00796-R-001P,2024-06-17T00:00:00,Центральный банк Российской Федерации,2024-07-03T00:00:00,1836.0,2024-07-03T00:00:00,2029-07-13T00:00:00,2024-07-04T00:00:00,50000.0,NaN,<NA>,MC0594300000,NaN,NaN,"ООО ""СФО АТОН Структурные Решения""",2029-07-13T00:00:00,<NA>,NDC000000000,<NA>,NaN,<NA>,NaN,0.0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,с фиксированной ставкой,fixed rate,Иной,A,365,A/365,<NA>,<NA>,Бездокументарная,Book-entry,Структурные долговые ценные бумаги прочих рези...,Размещен,Placed,Подписка закрытая,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,7.0,4.0,NaN,7.0,2.0,2.0,NaN,<NA>,<NA>,<NA>,S112,SFO ATON Structured Solutions 0.0001 13/07/29,Старшие обеспеченные,240543,<NA>,<NA>,"""Специализированное финансовое общество АТОН С...",<NA>,RU000A108TK6,СФО АТОН СтрРеш-001Р-05,239235.0,6-05-00796-R-001P,2024-06-17T00:00:00,ЦБ РФ,0.0,act/365,Структурные,DEXFXX,Прочий,Облигация,<NA>,Залог,0.0,0.0,0.0,Долгосрочные,Прочие активы,1.0,RU,1.0,RUB,1000.0,NaN,0.0,1.0,В обращении,50000000.0,50000.0,50000000.0,50000.0,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,<NA>,0.0,2024-07-03T00:00:00,<NA>,1836.0,2024-07-03T00:00:00,2029-07-13T00:00:00,1.0,2024-07-04T00:00:00,Корп,Классические,Структурный,2026-02-04T02:50:32,NaN,На обслуживании,1.0,<NA>,NaN,Облигации с Допдоходом.,NaN,False,False,False,2.0,1836.0,True,2024-07-03T00:00:00,0.0001,True,0,SN2,RU,1000,1000,NaN,True,NaN,0,0,<NA>,430.0,NaN,Прочий,Фикс.+доп.доход,109320,98305
1,3.0,3.0,3.0,3.0,3.0,RU000A108TL4,3.0,3.0,3.0,3.0,3.0,3.0,3.0,Структурные процентные дисконтные неконвертиру...,Небанковская кредитная организация акционерное...,Зарегистрирован/Представлен,006,1000.0,1.0,001Р-06,0.0,1.0,1000.0,RUB,50000.0,6-06-00796-R-001P,2024-06-17T00:00:00,Центральный банк Российской Федерации,2024-07-03T00:00:00,1836.0,2024-07-03T00:00:00,2029-07-13T00:00:00,2024-07-04T00:00:00,50000.0,NaN,<NA>,MC0594300000,NaN,NaN,"ООО ""СФО АТОН Структурные Решения""",2029-07-13T00:00:00,<NA>,NDC000000000,<NA>,NaN,<NA>,NaN,0.0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,с фиксированной ставкой,fixed rate,Иной,A,365,A/365,<NA>,<NA>,Бездокументарная,Book-entry,Структурные долговые ценные бумаги прочих рези...,Размещен,Placed,Подписка закрытая,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,7.0,4.0,NaN,7.0,2.0,2.0,NaN,<NA>,<NA>,<NA>,S112,SFO ATON Structured Solutions 0.0001 13/07/29,Старшие обеспеченные,240544,<NA>,<NA>,"""Специализированное финансовое общество АТОН С...",<NA>,RU000A108TL4,СФО АТОН СтрРеш-001Р-06,239235.0,6-06-00796-R-001P,2024-06-17T00:00:00,ЦБ РФ,0.0,act/365,Структурные,DEXFXX,Прочий,Облигация,<NA>,Залог,0.0,0.0,0.0,Долгосрочные,Прочие активы,1.0,RU,1.0,RUB,1000.0,NaN,0.0,1.0,В обращении,50000000.0,50000.0,50000000.0,50000.0,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,<NA>,0.0,2024-07-03T00:00:00,<NA>,1836.0,2024-07-03T00:00:00,2029-07-13T00:00:00,1.0,2024-07-04T00:00:00,Корп,Классические,Структурный,2026-02-04T02:50:32,NaN,На обслуживании,1.0,<NA>,NaN,Облигации с ДопДоходом.,NaN,False,False,False,2.0,1836.0,True,2024-07-03T00:00:00,0.0001,True,0,SN2,RU,1000,1000,NaN,True,NaN,0,0,<NA>,430.0,NaN,Прочий,Фикс.+доп.доход,109320,98306
2,3.0,3.0,3.0,3.0,3.0,RU000A108TM2,3.0,3.0,3.0,3.0,3.0,3.0,3.0,Структурные процентные дисконтные неконвертиру...,Небанковская кредитная организация акционерное...,Зарегистрирован/Представлен,007,0.0,1.0,001Р-07,0.0,1.0,1000.0,RUB,12617.0,6-07-00796-R-001P,2024-06-17T00:00:00,Центральный банк Российской Федерации,2024-07-11T00:00:00,383.0,2024-07-11T00:00:00,2025-07-29T00:00:00,2024-07-12T00:00:00,50000.0,NaN,<NA>,MC0594300000,NaN,NaN,"ООО ""СФО АТОН Структурные Решения""",2025-07-29T00:00:00,<NA>,NDC000000000,<NA>,NaN,<NA>,NaN,0.0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,с фиксированной ставкой,fixed rate,Иной,A,365,A/365,<NA>,<NA>,Бездокументарная,Book-entry,Структурные долговые ценные бумаги прочих рези...,Погашен,Redeemed,Подписка закрытая,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,7.0,4.0,NaN,7.0,3.0,2.0,NaN,<NA>,<NA>,<NA>,S112,SFO ATON Structured Solutions 0.0001 29/07/25,Старшие обеспеченные,240545,<NA>,<NA>,"""Специализированное финансовое общество АТОН С...",<NA>,RU000A108TM2,СФО АТОН СтрРеш-001Р-07,239235.0,6-07-00796-R-001P,2024-06-17T00:00:00,ЦБ РФ,0.0,act/365,Структурные,DEXFXX,Прочий,Облигация,<NA>,Залог,0.0,0.0,0.0,Краткосрочные,Прочие активы,1.0,RU,1.0,RUB,1000.0,NaN,0.0,1.0,Погашен,50000000.0,50000.0,12617000.0,12617.0,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,<NA>,0.0,2024-07-11T00:00:00,<NA>,383.0,2024-07-11T00:00:00,2025-07-29T00:00:00,1.0,2024-07-12T00:00:00,Корп,Классические,Структурный,2025-10-22T17:50:42,NaN,Снят с обслуживания,1.0,<NA>,NaN,Облигации с ДопДоходом.,NaN,False,False,False,2.0,NaN,True,2024-07-11T00:00:00,0.0000,True,0,SN2,RU,1000,1000,NaN,True,NaN,0,0,<NA>,430.0,NaN,<NA>,Фикс.+доп.доход,109320,98307
3,3.0,3.0,3.0,3.0,3.0,RU000A108TN0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,Структурные процентные дисконтные неконвертиру...,Небанковская кредитная организация акционерное...,Зарегистрирован/Представлен,008,1000.0,1.0,001Р-08,0.0,1.0,1000.0,RUB,40058.0,6-08-00796-R-001P,2024-06-17T00:00:00,Центральный банк Российской Федерации,2024-07-11T00:00:00,1113.0,2024-07-11T00:00:00,2027-07-29T00:00:00,2024-07-12T00:00:00,50000.0,NaN,<NA>,MC0594300000,NaN,NaN,"ООО ""СФО АТОН Структурные Решения""",2027-07-29T00:00:00,<NA>,NDC000000000,<NA>,NaN,<NA>,NaN,0.0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,с фиксированной ставкой,fixed rate,Иной,A,365,A/365,<NA>,<NA>,Бездокументарная,Book-entry,Структурные долговые ценные бумаги прочих рези...,Размещен,Placed,Подписка закрытая,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,7.0,4.0,NaN,7.0,2.0,2.0,NaN,<NA>,<NA>,<NA>,S112,SFO ATON Structured Solutions 0.0001 29/07/27,Старшие обеспеченные,240546,<NA>,<NA>,"""Специализированное финансовое общество АТОН С...",<NA>,RU000A108TN0,СФО АТОН СтрРеш-001Р-08,239235.0,6-08-00796-R-001P,2024-06-17T00:00:00,ЦБ РФ,0.0,act/365,Структурные,DEXFXX,Прочий,Облигация,<NA>,Залог,0.0,0.0,0.0,Среднесрочные,Прочие активы,1.0,RU,1.0,RUB,1000.0,NaN,0.0,1.0,В обращении,50000000.0,50000.0,40058000.0,40058.0,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,<NA>,0.0,2024-07-11T00:00:00,<NA>,1113.0,2024-07-11T00:00:00,2027-07-29T00:00:00,1.0,2024-07-12T00:00:00,Корп,Классические,Структурный,2025-10-22T17:50:42,NaN,На обслуживании,1.0,<NA>,NaN,Облигации с ДопДоходом.,NaN,False,False,False,2.0,1113.0,True,2024-07-11T00:00:00,0.0001,True,0,SN2,RU,1000,1000,NaN,True,NaN,0,0,<NA>,430.0,NaN,Прочий,Фикс.+доп.доход,109320,98308
4,3.0,3.0,3.0,3.0,3.0,RU000A108TP5,3.0,3.0,3.0,3.0,3.0,3.0,3.0,Структурные процентные дисконтные неконвертиру...,Небанковская кредитная организация акционерное...,Зарегистрирован/Представлен,009,1000.0,1.0,001Р-09,0.0,1.0,1000.0,RUB,50000.0,6-09-00796-R-001P,2024-06-17T00:00:00,Центральный банк Российской Федерации,2024-07-25T00:00:00,743.0,2024-07-25T00:00:00,2026-08-07T00:00:00,2024-07-26T00:00:00,50000.0,NaN,<NA>,MC0594300000,NaN,NaN,"ООО ""СФО АТОН Структурные Решения""",2026-08-07T00:00:00,<NA>,NDC000000000,<NA>,NaN,<NA>,NaN,0.0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,с фиксированной ставкой,fixed rate,Иной,A,365,A/365,<NA>,<NA>,Бездокументарная,Book-entry,Структурные долговые ценные бумаги прочих рези...,Размещен,Placed,Подписка закрытая,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,7.0,4.0,NaN,7.0,2.0,2.0,NaN,<NA>,<NA>,<NA>,S112,SFO ATON Structured Solutions 0.0001 07/08/26,Старшие обеспеченные,240547,<NA>,<NA>,"""Специализированное финансовое общество АТОН С...",<NA>,RU000A108TP5,СФО АТОН СтрРеш-001Р-09,239235.0,6-09-00796-R-001P,2024-06-17T00:00:00,ЦБ РФ,0.0,act/365,Структурные,DEXFXX,Прочий,Облигация,<NA>,Залог,0.0,0.0,0.0,Краткосрочные,Прочие активы,1.0,RU,1.0,RUB,1000.0,NaN,0.0,1.0,В обращении,50000000.0,50000.0,50000000.0,50000.0,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,СФО АТОН СтруктРеш,71451143,Финанс.сервисы,127223.0,9705218108,RU,г.Москва,<NA>,0.0,2024-07-25T00:00:00,<NA>,743.0,2024-07-25T00:00:00,2026-08-07T00:00:00,1.0,2024-07-26T00:00:00,Корп,Классические,Структурный,2025-10-22T17:50:42,NaN,На обслуживании,1.0,<NA>,NaN,Облигации с ДопДоходом.,NaN,False,False,False,2.0,743.0,True,2024-07-25T00:00:00,0.0001,True,0,SN2,RU,1000,1000,NaN,True,NaN,0,0,<NA>,430.0,NaN,Прочий,Фикс.+доп.доход,109320,98309

In [5]:
EndOfDayDF = EndOfDay().df
EndOfDayDF.head()

,ask,avge_prce,bid,boardid,boardname,close,convexity,deal_acc,duration,exch,high,isin,last,last_time,last_yield,low,mat_date,mprice,name,open,pvbp,seccode,secname,spread,val,val_usd,vol,vol_lots,yield_agg,yield_ask,yield_average_o12m,yield_average_o2w,yield_bid,yield_swa,currency,fintoolId,id_iss,id_trade_site,add_date,update_date
0,47.45,47.56,47.43,TQBR,T+ Акции и ДР,47.98,NaN,23354.0,NaN,MICEX,48.13,RU0009062285,47.45,2026-03-31T23:49:47,NaN,47.21,<NA>,47.55,AFLT.MICEX,47.98,NaN,AFLT,"Аэрофлот - российские авиалинии ОАО, АО - ФБ...",0.02,611036605.2,7515825.40,12848430.0,1284843.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4200,35154,170,2026-03-31T23:55:01,2026-04-01T07:05:08
1,10.06,9.98,9.97,TQBR,T+ Акции и ДР,9.97,NaN,28.0,NaN,MICEX,10.05,RU0009100176,10.04,2026-03-31T23:33:14,NaN,9.89,<NA>,10.02,BISVP.MICEX,9.89,NaN,BISVP,"Башинформсвязь ОАО, АП - ФБ ММВБ",0.09,89813.0,1104.71,9000.0,90.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4215,775000,170,2026-03-31T23:55:06,2026-04-01T07:05:09
2,1644.00,1631.00,1632.00,TQBR,T+ Акции и ДР,1608.00,NaN,259.0,NaN,MICEX,1658.00,RU0009288658,1638.00,2026-03-31T23:40:37,NaN,1610.00,<NA>,1628.00,BRZL.MICEX,1610.00,NaN,BRZL,"Бурятзолото ОАО, АО - ФБ ММВБ",12.00,4352122.0,53531.63,2668.0,2668.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4217,852973,170,2026-03-31T23:55:09,2026-04-01T07:05:10
3,195.00,187.00,195.00,TQBR,T+ Акции и ДР,178.00,NaN,3952.0,NaN,MICEX,195.00,RU0009082291,195.00,2026-03-31T23:31:52,NaN,170.00,<NA>,188.80,CHGZ.MICEX,177.80,NaN,CHGZ,"Черногорнефть ОАО, АО - ФБ ММВБ",0.00,84905754.0,1044351.21,453980.0,45398.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4223,853518,170,2026-03-31T23:55:09,2026-04-01T07:05:10
4,843.40,847.50,842.20,TQBR,T+ Акции и ДР,859.80,NaN,24370.0,NaN,MICEX,866.60,RU0009046510,842.40,2026-03-31T23:49:58.0002,NaN,837.20,<NA>,846.60,CHMF.MICEX,860.00,NaN,CHMF,"Северсталь ОАО, АО - ФБ ММВБ T+2",1.20,794530944.0,9772828.33,937552.0,937552.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4226,1069768,170,2026-03-31T23:55:07,2026-04-01T07:05:10

In [6]:
AccruedInterestOnDateDF = AccruedInterestOnDate().df
AccruedInterestOnDateDF.head()

,fintoolId,shiftDays,shiftTypeSource,typeCurrency,date,accruedInterest,accruedInterestPct,currentFaceValue,currentFaceValuePct,calculationType,error,faceValueCurrency,accruedInterestCurrency,faceValueLastKnownDate
0,4000,0,Calendar,<NA>,2026-03-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,<NA>,RUB,RUB,2026-03-31T00:00:00
1,4001,0,Calendar,<NA>,2026-03-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,<NA>,RUB,RUB,2026-03-31T00:00:00
2,4002,0,Calendar,<NA>,2026-03-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,<NA>,RUB,RUB,2026-03-31T00:00:00
3,4003,0,Calendar,<NA>,2026-03-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,<NA>,RUB,RUB,2026-03-31T00:00:00
4,4004,0,Calendar,<NA>,2026-03-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,<NA>,RUB,RUB,2026-03-31T00:00:00

In [7]:
FloaterDataDF = FloaterData().df
FloaterDataDF.head()

Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 1
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 1
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 2
Chunk done 3
Chunk done 2
Chunk done 5
Chunk done 3
Chunk done 0
Chunk done 10
Chunk done 6
Chunk done 0
Chunk done 2
Chunk done 7
Chunk done 9
Chunk done 0
Chunk done 4
Chunk done 4
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 1
Chunk done 5
Chunk done 0
Chunk done 1
Chunk done 2
Chunk done 1
Chunk done 0
Chunk done 14
Chunk done 9
Chunk done 6
Chunk done 1
Chunk done 0
Chunk done 4
Chunk done 4
Chunk done 6
Chunk done 16
Chunk done 19
Chunk done 14
Chunk done 11
Chunk done 6
Chunk done 4
Chunk done 5
Chunk done 7
Chunk done 2
Chunk done 3
Chunk done 2
Chunk done 3
Chunk done 9
Chunk done 7
Chunk done 1
Chunk done 3
Chunk done 2
Chunk done 0
Chunk done 0
Chunk done 2
Chunk done 6
Chunk done 14
Chunk done 2
Chunk done 4
Chunk done 10
Chunk done 3
Chunk done 21
Chunk done 11
Chunk done 1
Chunk done 7
Chunk done 10
Chunk done 4
Chunk done 3
Chunk done 0
Chunk done 4
Chunk done 10
Chunk done 3
Chunk done 0
Chunk done 6
Chunk done 2
Chunk done 5
Chunk done 23
Chunk done 20
Chunk done 16
Chunk done 2
Chunk done 1
Chunk done 6
Chunk done 2
Chunk done 1
Chunk done 3
Chunk done 11
Chunk done 13
Chunk done 1
Chunk done 7
Chunk done 6
Chunk done 2
Chunk done 4
Chunk done 4
Chunk done 10
Chunk done 0
Chunk done 11
Chunk done 14
Chunk done 6
Chunk done 10
Chunk done 13
Chunk done 18
Chunk done 2
Chunk done 1
Chunk done 12
Chunk done 1
Chunk done 9
Chunk done 10
Chunk done 2
Chunk done 2
Chunk done 7
Chunk done 1
Chunk done 4
Chunk done 11
Chunk done 3
Chunk done 1
Chunk done 17
Chunk done 7
Chunk done 14
Chunk done 10
Chunk done 12
Chunk done 4
Chunk done 6
Chunk done 3
Chunk done 5
Chunk done 6
Chunk done 0
Chunk done 7
Chunk done 16
Chunk done 1
Chunk done 16
Chunk done 0
Chunk done 6
Chunk done 26
Chunk done 6
Chunk done 35
Chunk done 20
Chunk done 46
Chunk done 20
Chunk done 5
Chunk done 16
Chunk done 1
Chunk done 0
Chunk done 0
Chunk done 22
Chunk done 8
Chunk done 0
Chunk done 7
Chunk done 3
Chunk done 6
Chunk done 6
Chunk done 209
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 2
Chunk done 6
Chunk done 6
Chunk done 13
Chunk done 0
Chunk done 2
Chunk done 1
Chunk done 6
Chunk done 11
Chunk done 2
Chunk done 15
Chunk done 2
Chunk done 29
Chunk done 12
Chunk done 16
Chunk done 18
Chunk done 15
Chunk done 26
Chunk done 16
Chunk done 22
Chunk done 21
Chunk done 20
Chunk done 24
Chunk done 32
Chunk done 24
Chunk done 37
Chunk done 19
Chunk done 23
Chunk done 12
Chunk done 29
Chunk done 20
Chunk done 25
Chunk done 8
Chunk done 18
Chunk done 13
Chunk done 9
Chunk done 14
Chunk done 36
Chunk done 28
Chunk done 23
Chunk done 18
Chunk done 29
Chunk done 17

,fintoolId,beg_period,end_period,start_point,model_type,date_pub_n,date_pub_type,date_fix_n,date_fix_type,bases
0,11193,2000-12-01T00:00:00,2050-12-01T00:00:00,E,single,NaN,<NA>,10.0,W,"[{'base_no': 1, 'calc_type': 'FIX', 'base_fint..."
1,36325,2009-08-27T00:00:00,2028-09-15T00:00:00,B,single,NaN,<NA>,1.0,W,"[{'base_no': 1, 'calc_type': 'FIX', 'base_fint..."
2,57394,2011-11-21T00:00:00,2028-10-30T00:00:00,B,single,NaN,<NA>,5.0,W,"[{'base_no': 2, 'calc_type': 'PER', 'base_fint..."
3,59702,2013-12-11T00:00:00,2028-11-22T00:00:00,B,single,NaN,<NA>,5.0,C,"[{'base_no': 2, 'calc_type': 'FIX', 'base_fint..."
4,61946,2017-08-18T00:00:00,2044-08-11T00:00:00,B,single,NaN,<NA>,5.0,W,"[{'base_no': 1, 'calc_type': 'PER', 'base_fint..."

In [8]:
FloatersOnPeriodDF = FloatersOnPeriod().df
FloatersOnPeriodDF.head()

Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 3
Chunk done 4
Chunk done 0
Chunk done 1
Chunk done 0
Chunk done 0
Chunk done 0
Chunk done 4
Chunk done 11
Chunk done 27
Chunk done 17
Chunk done 23
Chunk done 26
Chunk done 34
Chunk done 23
Chunk done 36
Chunk done 33
Chunk done 24
Chunk done 45
Chunk done 36
Chunk done 30
Chunk done 211

,fintoolId,date,accruedInterest,accruedInterestPct,currentFaceValue,currentFaceValuePct,faceValueCurrency,addDate,counter
0,164245,2026-03-31T00:00:00,2.43,0.24,1000.0,100.0,RUB,2026-03-30T06:00:16,1
1,170151,2026-03-31T00:00:00,28.99,2.90,1000.0,100.0,RUB,2026-03-30T06:00:18,2
2,170152,2026-03-31T00:00:00,2.43,0.24,1000.0,100.0,RUB,2026-03-30T06:00:18,2
3,170785,2026-03-31T00:00:00,11.15,1.12,1000.0,100.0,RUB,2026-03-30T06:00:19,4
4,171186,2026-03-31T00:00:00,11.15,1.12,1000.0,100.0,RUB,2026-03-30T06:00:20,4

In [9]:
RUPriceHistoryDF = RUPriceHistory().df
RUPriceHistoryDF.head()

Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 2742
Chunk done 0

,nickname,fintoolid,fininstid,isincode,regcode,nrdcode,calcdate,val_date,current_fv,faceftname,date_agg,avge_prce,yield_agg,z_wa_mb,durmod_agg,i_wa_mb,method_no,vp_pct,vp_pc,vp_pc_l,vp_pc_h,vp_m1,y_agg_m1,deal_250d,q_m1,r_m1,vp_m2,y_agg_m2,i_vp_m2,sigma_m2,index,beta1_m2,beta0_m2,alpha_m2,gamma_m2,sigma_nu,rho_m2,r_m2,vp_m3,y_agg_m3,dur_agg_m3,z_vp_m3,r_m3,factor1,beta1_m3,factor2,beta2_m3,level_pd,coef_b,risk_b,beta3_m3,is_ontherun,beta4_m3,hhi,beta5_m3,ind_liq,beta6_m3,ind_unliq,beta7_m3,sector,phi_sector,version,valuation_currency,security_type,source,wa_duration,duration_mod,lbound1,ubound1,lbound2,ubound2,lbound3,ubound3,acc_int,wap_ext_zspread,mp3_ext_zspread,id,no_history_found,not_valid_code,calcDateTime,counter,rn
0,ДОМ.РФ-15-об,36325,86707,RU000A0JQAM6,4-15-00739-A,RU000A0JQAM6,2026-03-02T00:00:00,2026-03-02T00:00:00,1000.0,RUB,2028-09-15T00:00:00,0.0,0.0,0.0,<NA>,0.0,2.0,105.529104,1055.29104,100.883856,106.222511,0.0,0.0,0.0,0.0,0.0,105.529104,15.697420,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,105.529104,15.697420,0.0,0.9823,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Финанс.сервисы,0.0,2,RUB,floating_bond,3,0.0,0.50137,0.0,0.0,100.883856,106.222511,100.883856,106.222511,92.054795,0.0,0.0,36325,<NA>,<NA>,<NA>,52742,1
1,ДОМ.РФ-15-об,36325,86707,RU000A0JQAM6,4-15-00739-A,RU000A0JQAM6,2026-03-03T00:00:00,2026-03-03T00:00:00,1000.0,RUB,2028-09-15T00:00:00,0.0,0.0,0.0,<NA>,0.0,2.0,105.529284,1055.29284,101.647856,106.197875,0.0,0.0,0.0,0.0,0.0,105.529284,15.695230,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,105.529284,15.695230,0.0,1.0104,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Финанс.сервисы,0.0,2,RUB,floating_bond,3,0.0,0.50137,0.0,0.0,101.647856,106.197875,101.647856,106.197875,92.602740,0.0,0.0,36325,<NA>,<NA>,<NA>,52742,2
2,ДОМ.РФ-15-об,36325,86707,RU000A0JQAM6,4-15-00739-A,RU000A0JQAM6,2026-03-04T00:00:00,2026-03-04T00:00:00,1000.0,RUB,2028-09-15T00:00:00,0.0,0.0,0.0,<NA>,0.0,2.0,105.342386,1053.42386,99.325846,105.879399,0.0,0.0,0.0,0.0,0.0,105.342386,15.777754,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,105.342386,15.777754,0.0,1.1408,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Финанс.сервисы,0.0,2,RUB,floating_bond,3,0.0,0.50137,0.0,0.0,99.325846,105.879399,99.325846,105.879399,93.150685,0.0,0.0,36325,<NA>,<NA>,<NA>,52742,3
3,ДОМ.РФ-15-об,36325,86707,RU000A0JQAM6,4-15-00739-A,RU000A0JQAM6,2026-03-05T00:00:00,2026-03-05T00:00:00,1000.0,RUB,2028-09-15T00:00:00,0.0,0.0,0.0,<NA>,0.0,2.0,105.237721,1052.37721,99.255161,105.788228,0.0,0.0,0.0,0.0,0.0,105.237721,15.817340,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,105.237721,15.817340,0.0,1.1705,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Финанс.сервисы,0.0,2,RUB,floating_bond,3,0.0,0.50137,0.0,0.0,99.255161,105.788228,99.255161,105.788228,93.698630,0.0,0.0,36325,<NA>,<NA>,<NA>,52742,4
4,ДОМ.РФ-15-об,36325,86707,RU000A0JQAM6,4-15-00739-A,RU000A0JQAM6,2026-03-06T00:00:00,2026-03-06T00:00:00,1000.0,RUB,2028-09-15T00:00:00,0.0,0.0,0.0,<NA>,0.0,2.0,105.097453,1050.97453,100.273835,105.548090,0.0,0.0,0.0,0.0,0.0,105.097453,15.870571,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,105.097453,15.870571,0.0,1.1982,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Финанс.сервисы,0.0,2,RUB,floating_bond,3,0.0,0.50137,0.0,0.0,100.273835,105.548090,100.273835,105.548090,94.246575,0.0,0.0,36325,<NA>,<NA>,<NA>,52742,5

In [10]:
ExchangeTreeDF = ExchangeTree().df
ExchangeTreeDF.head()

Chunk done 242
Chunk done 0

,id,id_parent,shortname_rus,shortname_eng,fullname_rus,fullname_eng,sort_order,update_date,counter,rn
0,144,63,Нал,Cash,Наличная валюта,Cash,0,2020-12-28T17:03:09,242,1
1,270,63,RUDIP 2,RUDIP 2,RUDIP 2,RUDIP 2,1,2022-10-31T19:41:24,242,2
2,84,83,США,US,Макроиндикаторы США,USA macroindicators,1,2020-12-28T17:03:09,242,3
3,2,1,РТС,RTS,РТС индексы,RTS indexes,2,2020-12-28T17:03:09,242,4
4,85,83,РФ,RU,Макроиндикаторы Россия,Russia macroindicators,2,2020-12-28T17:03:09,242,5

In [11]:
MoexSecuritiesDF = MoexSecurities().df
MoexSecuritiesDF.head()

Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 1500
Chunk done 117
Chunk done 0

,id_iss,secid,boardid,board_title,board_group,board_group_title,market,engine,short_name,isin,cfi_ifx,cfi_name,lot_size,expiration_date,currency,emitent_code,emitent_name,market_sector,min_price_increment,fintoolid,reg_code,update_date,counter,rn
0,2501,EUR_RUB__TOM,CETS,Системные сделки - безадрес.,currency,Системные сделки - безадрес.,selt,currency,Евро/Рубль-Том,<NA>,YCRSXX,Валютные пары / Тип пары / Кросс-курс,1000,<NA>,RUB,<NA>,<NA>,<NA>,0.0025,NaN,<NA>,2021-02-28T23:56:16.686054,244617,1
1,2502,EUR_RUB__TOD,CETS,Системные сделки - безадрес.,currency,Системные сделки - безадрес.,selt,currency,Евро/Рубль-Тод,<NA>,YCRSXX,Валютные пары / Тип пары / Кросс-курс,1000,<NA>,RUB,<NA>,<NA>,<NA>,0.0025,NaN,<NA>,2021-02-28T23:56:16.686053,244617,2
2,2840,KZT000000TOM,CETS,Системные сделки - безадрес.,currency,Системные сделки - безадрес.,selt,currency,Тенге/Рубль-Тод,<NA>,YCRXXX,Валютные пары / Тип пары / Кросс-курс,10000,<NA>,RUB,<NA>,<NA>,<NA>,0.0025,NaN,<NA>,2023-03-23T18:16:31.385678,244617,3
3,3691,UAH000000TOM,CETS,Системные сделки - безадрес.,currency,Системные сделки - безадрес.,selt,currency,Гривна/Рубль-Тод,<NA>,YCRSXX,Валютные пары / Тип пары / Кросс-курс,1000,<NA>,RUB,<NA>,<NA>,<NA>,0.0025,NaN,<NA>,2018-09-17T09:17:51.410715,244617,4
4,3752,USD000000TOD,CETS,Системные сделки - безадрес.,currency,Системные сделки - безадрес.,selt,currency,Доллар/Рубль-Тод,<NA>,YCRSXX,Валютные пары / Тип пары / Кросс-курс,1000,<NA>,RUB,<NA>,<NA>,<NA>,0.0025,NaN,<NA>,2021-02-28T23:56:17.686097,244617,5

In [12]:
CurrencyRateDF = CurrencyRate().df
CurrencyRateDF.head()

        rate  endOfDayRate error from   to
0        NaN           NaN  <NA>  ALL  RUB
1   0.610816      0.609855  <NA>  DZD  RUB
2        NaN           NaN  <NA>  ARS  RUB
3  55.841900     55.615900  <NA>  AUD  RUB
4        NaN           NaN  <NA>  BSD  RUB

##### Шаг 1.1. RuData MOEX stage

In [13]:
HistoryStockBondsDF = HistoryStockBonds().df
HistoryStockBondsDF.head()

Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 560
Chunk done 0

,boardname,regnumber,isin,matdate,listname,facevalue,currencyid,volume,value,numtrades,prev,prevlegalcloseprice,openperiod,legalopenprice,legalcloseprice,closeperiod,waprice,trendclose,trendclspr,trendwap,trendwappr,openval,closeval,highbid,lowoffer,bid,offer,yieldatwap,yieldclose,accint,duration,marketprice,marketprice2,admittedquote,issuesize,mpvaltrd,mp2valtrd,admittedvalue,marketprice3,marketprice3tradesvalue,type,lastprice,iricpiclose,beiclose,couponpercent,couponvalue,buybackdate,lasttradedate,cbrclose,yieldtooffer,yieldlastcoupon,offerdate,faceunit,engine,market,boardid,decimals,high,low,open,close,secid,shortname,tradedate,tradingsession,counter
0,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,0,0.00,0,102.001,102.001,NaN,<NA>,102.0010,<NA>,NaN,NaN,NaN,NaN,NaN,0.00,0.00,102.0175,102.2917,102.0001,102.3487,NaN,NaN,1016.9947,NaN,<NA>,102.1842,<NA>,240419,0.0,26006068.44,<NA>,102.1233,21265026.28,corporate_bond,NaN,NaN,NaN,7.63,38.02,<NA>,2026-02-27T00:00:00,<NA>,NaN,NaN,<NA>,USD,stock,bonds,TQCB,4,NaN,NaN,NaN,NaN,BYM000001818,РесБел 331,2026-03-02T00:00:00,1,200560.0
1,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,0,0.00,0,102.001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,0.00,0.00,102.0081,102.2485,102.0036,102.2485,NaN,NaN,1016.9947,NaN,<NA>,NaN,<NA>,240419,0.0,0.00,<NA>,NaN,0.00,corporate_bond,NaN,NaN,NaN,7.63,38.02,<NA>,2026-02-27T00:00:00,<NA>,NaN,NaN,<NA>,USD,stock,bonds,TQCB,4,NaN,NaN,NaN,NaN,BYM000001818,РесБел 331,2026-03-02T00:00:00,2,200560.0
2,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,0,0.00,0,102.001,102.001,NaN,<NA>,102.0010,<NA>,NaN,NaN,NaN,NaN,NaN,0.00,0.00,102.0175,102.2485,102.0036,102.2485,NaN,NaN,1016.9947,NaN,<NA>,102.1842,<NA>,240419,0.0,26006068.44,<NA>,102.1233,21265026.28,corporate_bond,NaN,NaN,NaN,7.63,38.02,<NA>,2026-02-27T00:00:00,<NA>,NaN,NaN,<NA>,USD,stock,bonds,TQCB,4,NaN,NaN,NaN,NaN,BYM000001818,РесБел 331,2026-03-02T00:00:00,3,200560.0
3,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,105,8274167.67,16,102.001,102.001,NaN,<NA>,102.0062,<NA>,102.1098,0.0052,0.01,-0.0744,-0.07,79017.23,78721.65,107.2131,102.0865,102.0301,102.3464,6.02,6.10,1031.7978,NaN,<NA>,102.1098,<NA>,240419,0.0,8274167.67,<NA>,102.1098,8274167.67,corporate_bond,102.0062,NaN,NaN,7.63,38.02,<NA>,2026-03-03T00:00:00,<NA>,NaN,NaN,<NA>,USD,stock,bonds,TQCB,4,102.40,102.0003,102.3892,102.0062,BYM000001818,РесБел 331,2026-03-03T00:00:00,1,200560.0
4,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,9,710131.57,6,102.001,NaN,NaN,<NA>,NaN,<NA>,102.2418,0.3490,0.34,0.0576,0.06,78740.10,78986.97,102.3500,101.9781,102.0543,102.3868,5.91,5.82,1031.7978,NaN,<NA>,NaN,<NA>,240419,0.0,0.00,<NA>,NaN,0.00,corporate_bond,102.3500,NaN,NaN,7.63,38.02,<NA>,2026-03-03T00:00:00,<NA>,NaN,NaN,<NA>,USD,stock,bonds,TQCB,4,102.35,102.0301,102.0301,102.3500,BYM000001818,РесБел 331,2026-03-03T00:00:00,2,200560.0

In [14]:
HistoryStockSharesDF = HistoryStockShares().df
HistoryStockSharesDF.head()

Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 5000
Chunk done 1519
Chunk done 0

,boardname,regnumber,isin,listname,facevalue,currencyid,prevlegalcloseprice,prev,legalopenprice,openperiod,closeperiod,openval,closeval,legalcloseprice,trendclose,trendclspr,highbid,bid,offer,lowoffer,waprice,trendwap,trendwappr,volume,marketprice,marketprice2,mp2valtrd,mpvaltrd,value,numtrades,issuesize,admittedquote,admittedvalue,monthlycapitalization,dailycapitalization,marketprice3,marketprice3tradesvalue,type,closeauctionprice,waval,lastprice,engine,market,boardid,decimals,high,low,open,close,secid,shortname,tradedate,tradingsession,counter
0,Т+: Неполные лоты (акции) - безадрес.,1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,NaN,78.88,<NA>,NaN,<NA>,78.28,78.28,NaN,-0.60,-0.76,78.28,64.02,78.30,78.14,67.10,-0.44,-0.65,1,<NA>,NaN,0.0,0.0,78.28,1,92645451,<NA>,<NA>,NaN,NaN,NaN,0.0,common_share,NaN,0.0,78.28,stock,shares,SMAL,2,78.28,78.28,78.28,78.28,ABIO,iАРТГЕН ао,2026-03-12T00:00:00,1,31519.0
1,Т+: Неполные лоты (акции) - безадрес.,1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,NaN,78.88,<NA>,NaN,<NA>,58.00,78.28,NaN,-0.60,-0.76,78.28,64.02,78.30,58.00,67.12,-0.42,-0.62,2,<NA>,NaN,0.0,0.0,136.28,2,92645451,<NA>,<NA>,NaN,NaN,NaN,0.0,common_share,NaN,0.0,78.28,stock,shares,SMAL,2,78.28,58.00,58.00,78.28,ABIO,iАРТГЕН ао,2026-03-12T00:00:00,3,31519.0
2,Поставка по СК (акции),1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,NaN,70.70,<NA>,NaN,<NA>,32438.00,628900.00,NaN,-4.50,-6.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39360,<NA>,NaN,0.0,0.0,2605632.00,23,92645451,<NA>,<NA>,NaN,NaN,NaN,0.0,common_share,NaN,0.0,NaN,stock,shares,SPEQ,6,66.20,66.20,66.20,66.20,ABIO,iАРТГЕН ао,2026-03-20T00:00:00,1,31519.0
3,Поставка по СК (акции),1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,NaN,70.70,<NA>,NaN,<NA>,32438.00,628900.00,NaN,-4.50,-6.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39360,<NA>,NaN,0.0,0.0,2605632.00,23,92645451,<NA>,<NA>,NaN,NaN,NaN,0.0,common_share,NaN,0.0,NaN,stock,shares,SPEQ,6,66.20,66.20,66.20,66.20,ABIO,iАРТГЕН ао,2026-03-20T00:00:00,3,31519.0
4,Т+: Акции и ДР - безадрес.,1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,67.48,67.38,<NA>,NaN,<NA>,1993.20,660.60,66.04,-1.32,-1.96,78.80,66.04,66.06,63.00,66.62,-1.04,-1.54,291670,<NA>,66.62,19430062.6,0.0,19430062.60,5619,92645451,<NA>,<NA>,6.279509e+09,6.172040e+09,66.62,19430062.6,common_share,66.04,0.0,66.06,stock,shares,TQBR,2,67.48,65.74,66.44,66.06,ABIO,iАРТГЕН ао,2026-03-02T00:00:00,1,31519.0

In [15]:
HistoryStockNdmDF = HistoryStockNdm().df
HistoryStockNdmDF.head()

Chunk done 5000
Chunk done 5000
Chunk done 46
Chunk done 0

,boardname,closeval,currencyid,facevalue,isin,issuesize,listname,matdate,numtrades,openval,prev,regnumber,trendclose,trendclspr,trendwap,trendwappr,type,value,volume,waprice,yieldatwap,yieldclose,lastprice,iricpiclose,beiclose,couponpercent,couponvalue,buybackdate,lasttradedate,cbrclose,yieldtooffer,yieldlastcoupon,offerdate,faceunit,engine,market,boardid,decimals,high,low,open,close,secid,shortname,tradedate,tradingsession,counter
0,РПС с ЦК: Акции и ДР - адрес.,43647386.4,SUR,0.09,RU000A0DQZE3,9650000000,1,<NA>,1,43647386.4,14.178,1-05-01669-A,-0.804,NaN,-0.213,-1.56,common_share,43647386.4,3263600,13.437,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,stock,ndm,PTEQ,3,13.374,13.374,13.374,13.374,AFKS,Система ао,2026-03-03T00:00:00,1,10046.0
1,РПС с ЦК: Акции и ДР - адрес.,43647386.4,SUR,0.09,RU000A0DQZE3,9650000000,1,<NA>,1,43647386.4,14.178,1-05-01669-A,-0.804,NaN,-0.203,-1.49,common_share,43647386.4,3263600,13.447,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,stock,ndm,PTEQ,3,13.374,13.374,13.374,13.374,AFKS,Система ао,2026-03-03T00:00:00,3,10046.0
2,РПС с ЦК: Акции и ДР - адрес.,13262000.0,SUR,0.09,RU000A0DQZE3,9650000000,1,<NA>,2,26524000.0,13.374,1-05-01669-A,-0.112,NaN,-0.074,-0.55,common_share,39786000.0,3000000,13.280,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,stock,ndm,PTEQ,3,13.262,13.262,13.262,13.262,AFKS,Система ао,2026-03-06T00:00:00,1,10046.0
3,РПС с ЦК: Акции и ДР - адрес.,13262000.0,SUR,0.09,RU000A0DQZE3,9650000000,1,<NA>,2,26524000.0,13.374,1-05-01669-A,-0.112,NaN,-0.072,-0.54,common_share,39786000.0,3000000,13.282,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,stock,ndm,PTEQ,3,13.262,13.262,13.262,13.262,AFKS,Система ао,2026-03-06T00:00:00,3,10046.0
4,РПС с ЦК: Акции и ДР - адрес.,13740000.0,SUR,0.09,RU000A0DQZE3,9650000000,1,<NA>,1,13740000.0,13.262,1-05-01669-A,0.478,NaN,0.125,0.92,common_share,13740000.0,1000000,13.667,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,stock,ndm,PTEQ,3,13.740,13.740,13.740,13.740,AFKS,Система ао,2026-03-10T00:00:00,1,10046.0

##### Шаг 2. RuData transform

In [40]:
##### Шаг 2. RuData transform
FintoolDF = FintoolReferenceDataDF[['isincode', 'nickname', 'fintooltype', 'fintoolid', 'faceftname']] \
    .rename(columns={
    "isincode": "isin",
    "nickname": "name",
    "fintoolid": "fintool",
    "fintooltype": "type",
    "faceftname": "currency"
})
FintoolDF = FintoolDF[~(FintoolDF["isin"].isna() | (FintoolDF["isin"].isin(['None', ''])))]
InterestDF = AccruedInterestOnDateDF[['fintoolId', 'accruedInterest', 'currentFaceValue']].set_index('fintoolId')
updates = FloatersOnPeriodDF.groupby('fintoolId')[[
    'accruedInterest', 'currentFaceValue'
]].last()
InterestDF = updates.combine_first(InterestDF)

In [24]:
FintoolDF = FintoolReferenceDataDF[['isincode', 'nickname', 'fintooltype', 'fintoolid', 'faceftname']]\
.rename(columns={
    "isincode": "isin",
    "nickname": "name",
    "fintoolid": "fintool",
    "fintooltype": "type",
    "faceftname": "currency"
})
FintoolDF = FintoolDF[~(FintoolDF["isin"].isna() | (FintoolDF["isin"].isin(['None', ''])))]
InterestDF = AccruedInterestOnDateDF[['fintoolId', 'accruedInterest', 'currentFaceValue']].set_index('fintoolId')
updates = FloatersOnPeriodDF.groupby('fintoolId')[[
    'accruedInterest', 'currentFaceValue'
]].last()
InterestDF = updates.combine_first(InterestDF)
FintoolDF = FintoolDF.merge(
    InterestDF, how="left", left_on="fintool", right_index=True)
FintoolDF = FintoolDF.rename(columns={
    'accruedInterest': 'interest',
    'currentFaceValue': 'principal'})

###### Шаг 2.1.1. CBR

In [25]:
from src.sources.cbr.CBR_Soap import CBR_Soap

headers = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.6834.111 Safari/537.36',
           'Accept-Encoding': 'gzip, deflate',
           'Accept': '*/*',
           'Connection': 'keep-alive'}
cbr_disc = CBR_Soap()\
.get_discounts(date=last_work_date_month_str)[['ISIN', 'от 1 месяца до 180 дней_Beg']]\
.rename(columns={'от 1 месяца до 180 дней_Beg': 'cbr_discount_6d'})\
.groupby('ISIN')\
.last()\
.reset_index()

In [26]:
FintoolDF = FintoolDF.merge(cbr_disc, how='left', left_on='isin', right_on='ISIN')
FintoolDF['cbr_discount_6d'] = FintoolDF['cbr_discount_6d'].fillna(1.0)

###### Шаг 2.1.2. nationalclearingcentre Рыночные риски

In [27]:
import io

currMarketRatesResponse = requests.get(
    f'https://www.nationalclearingcentre.ru/api/v1/rates/fondMarketRates?action=xls&xls=1&lang=ru&date={last_work_date_month.strftime("%d.%m.%Y")}',
    headers=headers
)
currMarketRates = pd.read_excel(io.BytesIO(currMarketRatesResponse.content), header=2)
currMarketRates = currMarketRates[(currMarketRates['Диапазон']==1)&(currMarketRates['Ставка риска падения цены,%']!=100)].reset_index(drop=True)
currMarketRates = currMarketRates\
.merge(MoexSecuritiesDF[['secid', 'isin']], how='left', left_on='Инструмент', right_on='secid')\
.groupby('isin')\
.last()\
.reset_index()
currMarketRates = currMarketRates[currMarketRates['isin'].str.match('([A-Z]{2})([A-Z0-9]{9})([0-9]{1})$')]
currMarketRates = currMarketRates[
    (currMarketRates['Диапазон']==1) & (currMarketRates['Ставка риска падения цены,%'] != 100)
]
currMarketRates = currMarketRates[['isin', 'Ставка риска падения цены,%']]\
.rename(columns={'Ставка риска падения цены,%': 'Risk rate'})
# Формула из п.12.1 Методики НКЦ определения риск-параметров
currMarketRates['discount_ncc'] = currMarketRates['Risk rate'].apply(lambda x: min(30, ceil(x/np.sqrt(2)))/100)

In [28]:
FintoolDF = FintoolDF.merge(currMarketRates[['isin', 'discount_ncc']], how='left', on='isin')
FintoolDF['discount_ncc'] = FintoolDF['discount_ncc'].fillna(1.0)

###### Шаг 2.1.3. nationalclearingcentre Параметры ценных бумаг

In [29]:
import io

securInfoResponse = requests.get(
    f'https://www.nationalclearingcentre.ru/api/v1/rates/securInfo?action=xls&lang=ru&settleDate={last_work_date_month.strftime("%d.%m.%Y")}',
    headers=headers
)
securInfo = pd.read_excel(io.BytesIO(securInfoResponse.content), header=2)[['ISIN ЦБ', 'Принимается в обеспеч.']]\
.rename(columns={
    'ISIN ЦБ': 'isin',
    'Принимается в обеспеч.': 'ncc_collateral'
})\
.dropna()\
.groupby('isin')\
.last()\
.reset_index()
securInfo = securInfo[securInfo['ncc_collateral']=='Да']

In [30]:
FintoolDF = FintoolDF.merge(securInfo, how='left', on='isin')
FintoolDF['ncc_collateral'] = FintoolDF['ncc_collateral'].fillna('Нет')

##### Шаг 2.2. RuData transform

RU Data (ЦЦ НРД)

In [31]:
RUPriceHistoryLast = RUPriceHistoryDF.groupby(
    'isincode'
).last().reset_index().rename(columns={
    'isincode': 'isin',
    'vp_pct': 'clean_price_pct',
    'vp_pc': 'clean_price',
    'acc_int': 'InterestHistory'
})
RUPriceHistoryLast["source"] = 'RU Data (ЦЦ НРД)'

End of Day

In [32]:
EndOfDayLast = EndOfDayDF.merge(
    ExchangeTreeDF[['id', 'fullname_rus']],
    how='left',
    left_on='id_trade_site',
    right_on='id'
)
EndOfDayLast["source"] = EndOfDayLast['fullname_rus'].apply(lambda x: 'RU Data (' + str(x) + ')')

##### Шаг 3. Moex

In [33]:
TransformHistoryStockBonds = HistoryStockBondsDF.groupby("isin")['close'].last().reset_index()
TransformHistoryStockShares = HistoryStockSharesDF.groupby("isin")['close'].last().reset_index()
TransformHistoryStockNdm = HistoryStockNdmDF.groupby("isin")['close'].last().reset_index()
HistoryStockMoex = pd.concat([
    TransformHistoryStockBonds,
    TransformHistoryStockShares,
    TransformHistoryStockNdm,
]).groupby('isin').first().reset_index()
HistoryStockMoex['source'] = 'RU Data (MOEX)'

In [34]:
Prices = pd.concat([
    RUPriceHistoryLast[['isin', 'clean_price_pct', 'clean_price', 'InterestHistory', 'source']],
    EndOfDayLast[['isin', 'last', 'source']].rename(columns={'last': 'close'}),
    HistoryStockMoex[['isin', 'close', 'source']],
]).merge(
    FintoolDF,
    how='inner',
)
Prices[['close', 'principal', 'interest']] = Prices[['close', 'principal', 'interest']].fillna(0)
Prices['interest'] = Prices['interest'].combine_first(Prices['interest'])

bonds_idx = Prices["type"]=='Облигация'
Prices.loc[bonds_idx, "price"] = Prices.loc[bonds_idx, "clean_price"] + Prices.loc[bonds_idx, "interest"]
Prices.loc[~bonds_idx, "price"] = Prices.loc[~bonds_idx, "clean_price"]

prices_na = Prices['price'].isna()
Prices.loc[prices_na & bonds_idx, "clean_price_pct"] = Prices.loc[prices_na, "close"]
Prices.loc[prices_na & bonds_idx, "clean_price"] = Prices.loc[prices_na, "clean_price_pct"]/100 * Prices.loc[prices_na, "principal"]
Prices.loc[prices_na & bonds_idx, "price"] = Prices.loc[prices_na, "clean_price"] + Prices.loc[prices_na, "interest"].fillna(0)
Prices.loc[prices_na & ~bonds_idx, 'clean_price'] = Prices.loc[prices_na & ~bonds_idx, 'close']
Prices.loc[prices_na & ~bonds_idx, 'price'] = Prices.loc[prices_na & ~bonds_idx, 'close']

Prices = Prices[Prices['clean_price']>1e-9]

#### Шаг 4. Finish

Currency

In [36]:
result = Prices.merge(
    CurrencyRateDF[CurrencyRateDF['to']=='RUB'][['from', 'rate']],
    how='left',
    left_on='currency',
    right_on='from'
).drop(columns=['from'])
result['fx_rate'] = result['rate']
result.loc[result['currency']=='RUB', 'fx_rate'] = 1

In [37]:
result['export_timestamp'] = dt.now().replace(microsecond=0)
result['report_date'] = pd.to_datetime(last_day_month)
result['source'] = result['source'].replace('nan', '').fillna('')
result['name'] = result['name'].replace('nan', '').fillna('')
result['type'] = result['type'].replace('nan', '').fillna('')
result['currency'] = result['currency'].replace('nan', '').fillna('')
result['fintool'] = result['fintool'].astype(int)
result = result.sort_values('isin')[["isin", "name", "type", "fintool", "currency", "interest", "principal", "fx_rate", "cbr_discount_6d", "discount_ncc", "ncc_collateral", "clean_price_pct", "clean_price", "price", "source", "export_timestamp", "report_date"]]

##### Шаг 4.2. Write excel

In [38]:
result.to_csv('./data/output/prices.csv', index=False, sep='\t', header=True)

In [39]:
from src.utils.send_email import main
main("prices.csv")