File: ratings.ipynb\
Author: alexkobz\
Date: 07.05.2024\
Task: DSRFU-275

#### Шаг 0. Импорт и получение токена

In [5]:
import pandas as pd
import numpy as np
import nest_asyncio; nest_asyncio.apply()
from src.utils.get_date import last_day_month, last_day_month_str
from src.utils.clickhouse_client import client, prepare_for_clickhouse

# последний день месяца
REPORT_DATE = last_day_month
REPORT_DATE_STR = last_day_month_str
# увеличиваем количество столбцов и строк для просмотра
pd.set_option('display.max_rows', 200, 'display.max_columns', 200)

In [6]:
from src.sources.rudata.RuDataMethod import Account, FintoolReferenceData, SecurityRatingTable, ExchangeTree, ListScaleValues, ListRatings, Emitents, OfferorsGuarants, CompanyRatingsTable
Acc = Account()

#### Шаг 1. Загрузка stage таблиц

[FintoolReferenceData](https://docs.efir-net.ru/dh2/#/Info/FintoolReferenceData?id=post-fintoolreferencedata) - Получить расширенный справочник по финансовым инструментам.

In [7]:
FintoolReferenceDataDF = FintoolReferenceData().df
FintoolReferenceDataDF.head()

,facevalue_m,faceftname_m,sumissuevol_m,summarketvol_m,numcoupons_m,nrdcode,regcode_m,regdate_m,regdistdate_m,begdistdate_m,enddistdate_m,endmtydate_m,daysall_m,fullname_nrd,rpregorg_nrd,rpstate_nrd,issuenumber,currentfacevalue_nrd,isqualified_nrd,bondseries,islombardcbr_nrd,numcoupons_nrd,facevalue_nrd,faceftname_nrd,summarketvol_nrd,regcode_nrd,regdate_nrd,regorg_nrd,begdistdate_nrd,daysall_nrd,enddistdate_nrd,endmtydate_nrd,regdistdate_nrd,sumissuevol_nrd,drqty,isincodebase_nrd,nrdcompcode,shqty,summarketvolorig_nrd,issuername_nrd,planmtydate_nrd,firstcoupondate_nrd,depositary_nrd,registrar_nrd,placeprice_nrd,micexlist_nrd,minlot_nrd,formarketbonds_nrd,registraracctype_nrd,registraracctypedate_nrd,facialacc_nrd,acc_open_date_nrd,fraction_nrd,specialized_depo_nrd,cmp_code_nsd_issuer_nrd,cmp_code_nsd_managing_nrd,ratetypenamerus_nrd,ratetypenameeng_nrd,coupontypename_nrd,base_month,base_year,basis_nrd,sectypenamerus_nrd,sectypenameeng_nrd,secformnamerus_nrd,secformnameeng_nrd,sectypenamebr_nrd,secstaterus_nrd,secstateeng_nrd,placementtype_nrd,share_category_name_nrd,share_category_name_en_nrd,dr_category_name_nrd,dr_category_name_en_nrd,company_state_name_nrd,rate_type_id,cp_type_id,coupon_period_base_id,sec_type_id,sec_form_id,sec_state_id,placement_type_id,share_category_id,dr_category_mn,company_state_mn,sector4212u,sna2008,fullname_en_nrd,seniorityname,fintoolid,moex_code,moex_name,fullname,isin144a,isincode,nickname,progfintoolid,regcode,regdate,regorg,amortisedmty,basis,bondstructuralpar,cfi,coupontype,fintooltype,guaranteeamount,guaranteetype,haveoffer,isconvertible,isguaranteed,maturitygroup,securitization,accruedintcalctype,country,couponperyear,faceftname,facevalue,guarantval,havedefault,numcoupons,status,sumissueval,sumissuevol,summarketval,summarketvol,borrowername,borrowerokpo,borrowersector,borroweruid,borrowerinn,borrowercountry,borrowerregionname,issuername,issuerokpo,issuersector,issueruid,issuerinn,issuercountry,issuerregionname,assetssector,numguarantors,begdistdate,begmtydate,daysall,enddistdate,endmtydate,privatedist,regdistdate,securitytype,securitykind,nominaltype,update_time,isregion,nsd_service,raterevisionsperyear,floatratename,issubordinated,note,listing_level,havecovenant,haverepayment,haveindexedfv,numdecimals,couponperiod,ismatched,firstcoupondate,couponrate,iscomplicated,available_for_unqualified,sec_type_br_code,original_country,qualified_test_id,qualified_test_id_tm,base_asset_fintoolid,isqualified,listing_level_spb,have_mm_moex,have_mm_spb,beg_book_date,seniority,tradesite,current_coupontype,profit_type,counter,rn
0,2.0,2.0,2.0,2.0,2.0,<NA>,2.0,0.0,2.0,2.0,2.0,2.0,2.0,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,NaN,NaN,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,S111,<NA>,Старшие необеспеченные,4000,<NA>,<NA>,"МинФин РФ, государственные краткосрочные беску...",<NA>,<NA>,ГКО-21134,NaN,21134RMFS,<NA>,МинФин,0.0,act/365,<NA>,<NA>,Дисконтный,Облигация,<NA>,Необеспеченные,0.0,0.0,0.0,Краткосрочные,<NA>,1.0,RU,0.0,RUB,1000.0,NaN,0.0,0.0,Погашен,2.500000e+09,2500000.0,2.500000e+09,2500000.0,Минфин РФ,00013474,Государственные,6874.0,7710168360,RU,г.Москва,Минфин РФ,00013474,Государственные,6874.0,7710168360,RU,г.Москва,<NA>,0.0,1999-12-17T00:00:00,<NA>,110.0,1999-12-17T00:00:00,2000-04-05T00:00:00,0.0,1999-12-17T00:00:00,Гос,Классические,Постоянный,2023-04-19T15:55:00,NaN,Нет информации,0.0,<NA>,NaN,<NA>,NaN,False,False,False,2.0,NaN,True,<NA>,0.0,False,0,<NA>,RU,1000,1000,NaN,False,NaN,0,0,<NA>,416.0,NaN,<NA>,<NA>,108426,1
1,3.0,3.0,3.0,4.0,3.0,SU21135RMFS7,3.0,1.0,2.0,3.0,2.0,3.0,2.0,Государственные краткосрочные бескупонные обли...,Финансовые органы,<NA>,135,0.0,0.0,<NA>,0.0,0.0,1000.0,RUB,1500000.0,21135RMFS,1999-12-10T00:00:00,Финансовые органы,1999-12-21T00:00:00,NaN,<NA>,2000-05-17T00:00:00,<NA>,1500000.0,NaN,<NA>,MS0003000000,NaN,NaN,Минфин России,2000-05-17T00:00:00,1999-12-21T00:00:00,NDC000000000,<NA>,NaN,<NA>,NaN,0.0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Документарная именная,certificated registered,Облигации федеральных органов исполнительной в...,Погашен,Redeemed,Аукцион,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,1.0,3.0,4.0,NaN,<NA>,<NA>,<NA>,S111,Minfin Rossii ... 17/05/00,Старшие необеспеченные,4001,<NA>,<NA>,"МинФин РФ, государственные краткосрочные беску...",<NA>,RU0004525088,ГКО-21135,NaN,21135RMFS,<NA>,МинФин,0.0,act/365,<NA>,<NA>,Дисконтный,Облигация,<NA>,Необеспеченные,0.0,0.0,0.0,Краткосрочные,<NA>,1.0,RU,0.0,RUB,1000.0,NaN,0.0,0.0,Погашен,1.500000e+09,1500000.0,1.497796e+09,1497796.0,Минфин РФ,00013474,Государственные,6874.0,7710168360,RU,г.Москва,Минфин РФ,00013474,Государственные,6874.0,7710168360,RU,г.Москва,<NA>,0.0,1999-12-21T00:00:00,<NA>,148.0,1999-12-21T00:00:00,2000-05-17T00:00:00,0.0,1999-12-21T00:00:00,Гос,Классические,Постоянный,2026-01-24T22:20:30,NaN,Нет информации,0.0,<NA>,NaN,<NA>,NaN,False,False,False,2.0,NaN,True,<NA>,0.0,False,0,BON1,RU,1000,1000,NaN,False,NaN,0,0,<NA>,416.0,NaN,<NA>,<NA>,108426,2
2,3.0,3.0,3.0,3.0,3.0,SU21136RMFS5,3.0,1.0,2.0,3.0,2.0,3.0,2.0,Государственные краткосрочные бескупонные обли...,Финансовые органы,<NA>,136,0.0,0.0,<NA>,0.0,0.0,1000.0,RUB,2500000.0,21136RMFS,1999-12-10T00:00:00,Финансовые органы,1999-12-21T00:00:00,NaN,<NA>,2000-07-05T00:00:00,<NA>,2500000.0,NaN,<NA>,MS0003000000,NaN,NaN,Минфин России,2000-07-05T00:00:00,1999-12-21T00:00:00,NDC000000000,<NA>,NaN,<NA>,NaN,0.0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Документарная именная,certificated registered,Облигации федеральных органов исполнительной в...,Погашен,Redeemed,Аукцион,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,1.0,3.0,4.0,NaN,<NA>,<NA>,<NA>,S111,Minfin Rossii ... 05/07/00,Старшие необеспеченные,4002,<NA>,<NA>,"МинФин РФ, государственные краткосрочные беску...",<NA>,RU0001073017,ГКО-21136,NaN,21136RMFS,<NA>,МинФин,0.0,act/365,<NA>,<NA>,Дисконтный,Облигация,<NA>,Необеспеченные,0.0,0.0,0.0,Краткосрочные,<NA>,1.0,RU,0.0,RUB,1000.0,NaN,0.0,0.0,Погашен,2.500000e+09,2500000.0,2.500000e+09,2500000.0,Минфин РФ,00013474,Государственные,6874.0,7710168360,RU,г.Москва,Минфин РФ,00013474,Государственные,6874.0,7710168360,RU,г.Москва,<NA>,0.0,1999-12-21T00:00:00,<NA>,197.0,1999-12-21T00:00:00,2000-07-05T00:00:00,0.0,1999-12-21T00:00:00,Гос,Классические,Постоянный,2026-01-24T22:20:30,NaN,Нет информации,0.0,<NA>,NaN,<NA>,NaN,False,False,False,2.0,NaN,True,<NA>,0.0,False,0,BON1,RU,1000,1000,NaN,False,NaN,0,0,<NA>,416.0,NaN,<NA>,<NA>,108426,3
3,2.0,2.0,2.0,2.0,2.0,<NA>,2.0,0.0,2.0,2.0,2.0,2.0,2.0,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,NaN,NaN,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,S111,<NA>,Старшие необеспеченные,4003,<NA>,<NA>,"МинФин РФ, государственные краткосрочные беску...",<NA>,<NA>,ГКО-21137,NaN,21137RMFS,<NA>,МинФин,0.0,act/365,<NA>,<NA>,Дисконтный,Облигация,<NA>,Необеспеченные,0.0,0.0,0.0,Краткосрочные,<NA>,1.0,RU,0.0,RUB,1000.0,NaN,0.0,0.0,Погашен,2.500000e+09,2500000.0,2.500000e+09,2500000.0,Минфин РФ,00013474,Государственные,6874.0,7710168360,RU,г.Москва,Минфин РФ,00013474,Государственные,6874.0,7710168360,RU,г.Москва,<NA>,0.0,2000-04-19T00:00:00,<NA>,210.0,2000-04-19T00:00:00,2000-11-15T00:00:00,0.0,2000-04-19T00:00:00,Гос,Классические,Постоянный,2023-04-19T15:55:00,NaN,Нет информации,0.0,<NA>,NaN,Выпуск предназначен для нерезидентов.,NaN,False,False,False,2.0,NaN,True,<NA>,0.0,False,0,<NA>,RU,1000,1000,NaN,False,NaN,0,0,<NA>,416.0,NaN,<NA>,<NA>,108426,4
4,3.0,3.0,3.0,3.0,3.0,SU21138RMFS1,3.0,1.0,2.0,3.0,2.0,3.0,2.0,Государственные краткосрочные бескупонные обли...,Финансовые органы,<NA>,138,0.0,0.0,<NA>,0.0,0.0,1000.0,RUB,2500000.0,21138RMFS,2000-02-14T00:00:00,Финансовые органы,2000-02-23T00:00:00,NaN,<NA>,2000-09-06T00:00:00,<NA>,2500000.0,NaN,<NA>,MS0003000000,NaN,NaN,Минфин России,2000-09-06T00:00:00,2000-02-23T00:00:00,NDC000000000,<NA>,NaN,<NA>,NaN,0.0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Документарная именная,certificated registered,Облигации федеральных органов исполнительной в...,Погашен,Redeemed,Аукцион,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,1.0,3.0,4.0,NaN,<NA>,<NA>,<NA>,S111,Minfin Rossii ... 06/09/00,Старшие необеспеченные,4004,<NA>,<NA>,"МинФин РФ, государственные краткосрочные беску...",<NA>,RU0004532530,ГКО-21138,NaN,21138RMFS,<NA>,МинФин,0.0,act/365,<NA>,<NA>,Дисконтный,Облигация,<NA>,Необеспеченные,0.0,0.0,0.0,Краткосрочные,<NA>,1.0,RU,0.0,RUB,1000.0,NaN,0.0,0.0,Погашен,2.500000e+09,2500000.0,2.500000e+09,2500000.0,Минфин РФ,00013474,Государственные,6874.0,7710168360,RU,г.Москва,Минфин РФ,00013474,Государственные,6874.0,7710168360,RU,г.Москва,<NA>,0.0,2000-02-23T00:00:00,<NA>,196.0,2000-02-23T00:00:00,2000-09-06T00:00:00,0.0,2000-02-23T00:00:00,Гос,Классические,Постоянный,2026-01-24T22:20:30,NaN,Нет информации,0.0,<NA>,NaN,<NA>,NaN,False,False,False,2.0,NaN,True,<NA>,0.0,False,0,BON1,RU,1000,1000,NaN,False,NaN,0,0,<NA>,416.0,NaN,<NA>,<NA>,108426,5

[SecurityRatingTable](https://docs.efir-net.ru/dh2/#/Rating/SecurityRatingTable?id=post-securityratingtable) - Получить рейтинги нескольких бумаг и связанных с ними компаний на заданную дату.

In [8]:
%%time
SecurityRatingTableDF = SecurityRatingTable().df
SecurityRatingTableDF.head()

CPU times: user 245 ms, sys: 7.64 ms, total: 253 ms
Wall time: 289 ms

,id,hid,code_name,id_value,forecast,change,date_award,role,okpo,fininstid,fintoolid,isin,id_rating,code,shortname_rus
0,0,912,IFX-Bnd-Nsc,Снят,<NA>,снят,2003-07-22T00:00:00,0,<NA>,6805.0,4121.0,RU0007200291,73,RU0007200291,Лукойл-1-об
1,0,914,IFX-Bnd-Nsc-max,Снят,<NA>,снят,2003-07-22T00:00:00,0,<NA>,6805.0,4121.0,RU0007200291,80,RU0007200291,Лукойл-1-об
2,0,141,JCR-I-Cr&D-LT-Isc,BB+,Негативный,Подтвержден,2016-08-01T00:00:00,1,<NA>,6874.0,NaN,<NA>,224,<NA>,Минфин РФ
3,0,142,JCR-I-Cr&D-LT-Isc-Icur,Снят,<NA>,снят,2022-04-14T00:00:00,1,<NA>,6874.0,NaN,<NA>,249,<NA>,Минфин РФ
4,0,143,JCR-I-Cr&D-LT-Isc-Ncur,Снят,<NA>,снят,2022-04-14T00:00:00,1,<NA>,6874.0,NaN,<NA>,250,<NA>,Минфин РФ

[ExchangeTree](https://docs.efir-net.ru/dh2/#/Info/ExchangeTree?id=post-exchangetree) - Получить иерархию торговых площадок/источников, используемых Интерфакс

In [9]:
ExchangeTreeDF = ExchangeTree().df
ExchangeTreeDF.head()

,id,id_parent,shortname_rus,shortname_eng,fullname_rus,fullname_eng,sort_order,update_date,counter,rn
0,1,0,РТС,RTS,Московская Биржа - РТС,RTS,12,2020-12-28T17:03:09,242,17
1,2,1,РТС,RTS,РТС индексы,RTS indexes,2,2020-12-28T17:03:09,242,4
2,8,1,ФОРТС,FORTS,FORTS,FORTS,8,2020-12-28T17:03:09,242,11
3,9,0,"ПАО ""СПБ""",PJSC «SPB»,"ПАО ""СПБ""",PJSC «SPB»,20,2020-12-28T17:03:09,242,21
4,11,0,МБ,MX,Московская Биржа,Moscow Exchange,11,2020-12-28T17:03:09,242,16

[ListScaleValues](https://docs.efir-net.ru/dh2/#/Rating/ListScaleValues?id=post-listscalevalues) - Список шкал значений рейтингов

In [10]:
ListScaleValuesDF = ListScaleValues().df
ListScaleValuesDF.head()

,id,scale_id,rating_value,rating_level,fullname_rus,description,aggregation_type,aggregation_level
0,1,1,AAA(rus),1,Наивысший уровень кредитоспособности,Национальные рейтинги категории «ААА» обознача...,<NA>,NaN
1,2,1,AA+(rus),2,<NA>,<NA>,<NA>,NaN
2,3,1,AA(rus),3,Очень высокая кредитоспособность,Национальные рейтинги категории «AA» обозначаю...,<NA>,NaN
3,4,1,AA-(rus),4,<NA>,<NA>,<NA>,NaN
4,5,1,A+(rus),5,<NA>,<NA>,<NA>,NaN

[ListRatings](https://docs.efir-net.ru/dh2/#/Dictionary/ListRatings?id=post-listratings) - Список рейтингов

In [11]:
ListRatingsDF = ListRatings().df
ListRatingsDF.head()

,id,rating_id,code_name,agency,fullname_rus,fullname_eng,for_instrument,for_company,agency_eng,official_name,is_credit,term_type,term_type_name,currency_type,currency_type_name,scale_type,scale_type_name,is_archive,is_accred_br,doc_511p,doc_421p,doc_180i,agency_id,usedInAgg,scale_id,aggregation_type
0,4,23,MDS-I-Corp-LT-Isc-Icur,Мудиз,"Корпоративный рейтинг эмитента, долгосрочный, ...","Сorporate family rating, long-term, internatio...",0,1,Moody's,LT Corporate Family Ratings (Foreign),1,L,Долгосрочный,F,Иностранная,I,Международная,0,1.0,1,1,1,2,1,5,BIG3
1,5,83,MDS-I-Corp-LT-Isc-Ncur,Мудиз,"Корпоративный рейтинг эмитента, долгосрочный, ...","Сorporate family rating, long-term, internatio...",0,1,Moody's,LT Corporate Family Ratings (Domestic),1,L,Долгосрочный,L,Локальная,I,Международная,0,1.0,1,1,1,2,1,5,BIG3
2,6,116,MIRA-I-Corp-LT-Nsc,Мудис Интерфакс,"Корпоративный рейтинг эмитента, долгосрочный, ...","Сorporate family rating, long-term, national s...",0,1,Moody's Interfax,NSR LT Corporate Family Ratings (Domestic),1,L,Долгосрочный,L,Локальная,N,Национальная,1,NaN,0,0,0,7,0,2,<NA>
3,7,129,MDS-I-Corp-LT-UAsc,Мудиз,"Корпоративный рейтинг эмитента, долгосрочный, ...","Сorporate family rating, long-term, ukrainian ...",0,1,Moody's,LT Corporate Family Ratings (ukr),1,L,Долгосрочный,L,Локальная,U,Укр.национальная,0,1.0,0,0,0,2,0,23,<NA>
4,8,234,EXP-Bnd-Isc,Эксперт РА,"Рейтинг надежности облигационных займов, между...","Reliability ratings for bond loans, internatio...",1,0,Expert RA,Рейтинги надежности облигационных займов,1,L,Долгосрочный,N,Не определена,I,Международная,1,1.0,0,0,0,4,0,32,BIG3

[Emitents](https://docs.efir-net.ru/dh2/#/Info/Emitents?id=post-emitents) - Получить краткий справочник по эмитентам.

In [12]:
EmitentsDF = Emitents().df
EmitentsDF.head()

,id_emitent,fininstid,shortname_rus,shortname_eng,inn,okpo,ogrn,code,sector,legal_address,phone,www,update_date,fullname_rus_nrd,fullname_eng_nrd,shortname_rus_nrd,shortname_eng_nrd,company_type_short_name,state_reg_num,state_reg_date,state_reg_name,egrul_date,egrul_organ_name,country,lei_code,bik,fax,e_mail,credit_cmp,is_bank_4_non_resident,swift,country_oksm,country_oksm_cbr,country_name_rus,country_name_eng,region_inn,region_soato,region_name,fullname_rus,sparkid,br_fcsm_reg_code,capital,capital_unit,okved,oecd_lvl,oktmo,okato,post_address,okopf,okogu,have_rating,have_risk,is_finorg,is_control_by_finorg,is_gov_or_cb,on_behalf_of_state,is_subjectrf,is_cis_reg,issuer_nrd,tin,kpp,state_reg_number,market_id_nrd,market_name_rus_nrd,market_name_eng_nrd,sp_rx_entity_id,sp_shortname,mds_shortname,mds_org_id,fch_id,fch_shortname,is_monopoly,is_strategic,ifo_list,isregion,sic,sector4212u,sna2008,reg_code,reg_date,reg_org,note,primary_reg_date,inn_fle,other_tin,other_tin_name,okfs_id,okfs_name,is_branch,counter,rn
0,24128,7962,Элара,ELARA,2129017646,24322961,1022101269123,ELAR,Машиностроение,"428017,Чувашская Республика - Чувашия, г. Чебо...",(903)3582649; (8352)425303; (8352)453650,www.elara.ru,2022-11-24T16:45:21.469925,<NA>,<NA>,<NA>,<NA>,НАО,<NA>,<NA>,<NA>,<NA>,<NA>,RUS,<NA>,<NA>,<NA>,audit@elara.ru,<NA>,<NA>,<NA>,643.0,643.0,РОССИЯ,Russia,21,97,Чувашская Республика,"""Научно-производственный комплекс ""ЭЛАРА"" имен...",212225.0,55813-D,105368.0,RUB,26.51.1,7,97701000001,97401000000,"428017,Чувашская Республика - Чувашия, г. Чебо...",12267,4210008,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,213001001,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0,1,<NA>,0.0,3810,<NA>,S112,1022101269123,2002-08-16T00:00:00,Администрация Московского Района Города Чебокс...,<NA>,1992-05-13T00:00:00,<NA>,<NA>,ДопИНН,16,Частная собственность,0,44334,886
1,24129,66181,Элсиб,NPO ELSIB,5403102702,05757937,1025401300748,ELIB,Машиностроение,"630088,Новосибирская обл., г. Новосибирск, ул....",(383)2278150; (383)2278152; (383)2278153,http://www.elsib.ru/,2025-01-29T14:51:43,"Научно-производственное объединение ""ЭЛСИБ"" пу...",ELSIB,"НПО ""ЭЛСИБ"" ПАО",ELSIB,ПАО,ГР 1110,1994-05-11T00:00:00,Новосибирская городская регистрационная палата...,2002-09-12T00:00:00,Инспекция Министерства РФ по налогам и сборам ...,RUS,<NA>,<NA>,(383) 298-92-94,elsib@elsib.ru,0,0,<NA>,643.0,643.0,РОССИЯ,Russia,54,50,Новосибирская область,"Научно-производственное объединение ""ЭЛСИБ"", ПАО",80607.0,10917-F,112000000.0,RUB,27.11.1,7,50701000001,50401374000,"630088,Новосибирская обл., г. Новосибирск, ул....",12247,4210008,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,ELIB,<NA>,540301001,ГР 1110,2.0,Корпоративный,corporate,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0,0,<NA>,0.0,3510,<NA>,S112,1025401300748,<NA>,<NA>,<NA>,1992-12-25T00:00:00,<NA>,<NA>,ДопИНН,16,Частная собственность,0,44334,1278
2,24131,98136,Элпа НИИ,Elpa,7735064772,07628061,1027739098760,ELPA,Технологии,"124460, г. Москва, г. Зеленоград, проспект Пан...",(903)7114552; (495)5301302; (499)5351310,www.elpapiezo.ru,2025-01-29T14:51:44,"Акционерное общество ""Научно-исследовательский...","""Elpa"" Research institute and pilot line"" (joi...","АО ""НИИ ""Элпа""","""Elpa"" Research institute"" (jsc)",АО,<NA>,<NA>,<NA>,2002-08-21T00:00:00,Межрайонная инспекция МНС России № 39 по г. Мо...,RUS,<NA>,<NA>,(499) 710-13-02,elpalaw@elpapiezo.ru,0,0,<NA>,643.0,643.0,РОССИЯ,Russia,77,45,г.Москва,"""Научно-исследовательский институт ""Элпа"" с оп...",84848.0,02540-A,20543500.0,RUB,72.19,7,45331000000,45272562000,"124460, г. Москва, г. Зеленоград, проспект Пан...",12267,4210008,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,ELPA,<NA>,773501001,<NA>,2.0,Корпоративный,corporate,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0,0,<NA>,0.0,8730,<NA>,S112,1027739098760,<NA>,<NA>,<NA>,1993-06-10T00:00:00,<NA>,<NA>,ДопИНН,16,Частная собственность,0,44334,12333
3,24132,97866,Электропривод,Elektroprivod,7708012528,00216390,1027700022228,ELPD,Машиностроение,"107078, г. Москва, ул. Садовая-Спасская, д. 1 ...",(495)6082160; (495)6082181; (495)6082514,<NA>,2025-07-02T13:25:22.980783,<NA>,<NA>,<NA>,<NA>,ПАО,<NA>,<NA>,<NA>,<NA>,<NA>,RUS,<NA>,<NA>,<NA>,gevorkyan@el-privod.ru,<NA>,<NA>,<NA>,643.0,643.0,РОССИЯ,Russia,77,45,г.Москва,"""Электропривод"", ОАО",2825.0,04600-A,19728.0,RUB,<NA>,7,45378000000,45286565000,"107078, г. Москва, ул. Садовая-Спасская, д. 1/...",12247,4210008,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,770801001,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0,0,<NA>,0.0,<NA>,<NA>,S112,1027700022228,<NA>,<NA>,<NA>,1993-03-05T00:00:00,<NA>,<NA>,ДопИНН,16,Частная собственность,0,44334,12063
4,24133,92706,Электроприбор-ВоронежНПО,Elektropribor,3650000821,07515210,1023602241321,ELPV,Машиностроение,"394071,Воронежская обл., г. Воронеж, ул. 20-Ле...",(473)2578542; (473)2578501; (473)2578503,www.epribor.ru,2025-01-29T14:51:43,Акционерное общество Научно-производственное о...,Joint stock company Research and Production Co...,"АО НПО ""Электроприбор-Воронеж""","JSC ""Electropribor-Voronezh R&P Corp.""",АО,3664/112180,1996-11-21T00:00:00,Администрация г. Воронежа,2002-07-10T00:00:00,Инспекция Министерства РФ по налогам и сборам ...,RUS,<NA>,<NA>,<NA>,amaideniukov@priborvrn.ru,0,0,<NA>,643.0,643.0,РОССИЯ,Russia,36,20,Воронежская область,"Научно-производственное объединение ""Электропр...",83973.0,40057-A,20437740.0,RUB,26.51.1,7,20701000001,20401000000,"394071,Воронежская обл., г. Воронеж, ул. 20-Ле...",12267,4210008,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,ELPV,<NA>,366401001,3664/112180,2.0,Корпоративный,corporate,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0,0,<NA>,0.0,3810,<NA>,S112,1023602241321,2002-07-10T00:00:00,Инспекция МНС России по Ленинскому Району г. В...,"Прежнее наименование: ""Электроприбор"", АО",1993-06-23T00:00:00,<NA>,<NA>,ДопИНН,16,Частная собственность,0,44334,7494

[OfferorsGuarants](https://docs.efir-net.ru/dh2/#/Bond/OfferorsGuarants?id=post-offerorsguarants) - Возвращает список гарантов/оферентов для инструмента

In [13]:
OfferorsGuarantsDF = OfferorsGuarants().df
OfferorsGuarantsDF.head()

   fintoolId  fininstid_guarant  fininstid_offeror  counter  rn
0      30319               6805                NaN     5598   1
1      36324               6874                NaN     5598   2
2      36325               6874                NaN     5598   3
3      53479               6874                NaN     5598   4
4      56915              88767                NaN     5598   5

[CompanyRatingsTable](https://docs.efir-net.ru/dh2/#/Rating/CompanyRatingsTable?id=post-companyratingstable) - Получить рейтинги нескольких компаний на заданную дату.

In [14]:
CompanyRatingsTableDF = CompanyRatingsTable().df
CompanyRatingsTableDF.head()

,name_ra,dt,last,last_dt,change,forecast,advanced,prev,prev_dt,id_rating,code,code_type,company_name
0,Рейтинг отозван,2016-03-18T00:00:00,Снят,2016-03-18T00:00:00,снят,<NA>,Основной,Aa3.ru,2016-03-10T00:00:00,6,6666,FININSTID,Яковлев
1,Рейтинг отозван,2016-03-18T00:00:00,Снят,2016-03-18T00:00:00,снят,<NA>,Основной,Aa3.ru,2015-04-16T00:00:00,6,6971,FININSTID,Нижнекамскнефтехим
2,Рейтинг отозван,2016-03-18T00:00:00,Снят,2016-03-18T00:00:00,снят,<NA>,Основной,Aa1.ru,2016-03-10T00:00:00,6,6981,FININSTID,НЛМК
3,Рейтинг отозван,2016-03-18T00:00:00,Снят,2016-03-18T00:00:00,снят,<NA>,Основной,Aa2.ru,2016-03-10T00:00:00,6,43888,FININSTID,Уралкалий
4,Рейтинг отозван,2016-03-18T00:00:00,Снят,2016-03-18T00:00:00,снят,<NA>,Основной,Aa3.ru,2016-03-10T00:00:00,6,87397,FININSTID,НМТП

#### Шаг 2. Предобработка таблиц до экспорта в excel

In [15]:
#добавляем информацию из справочника в нашу таблицу с компаниями
ExtendedSecurityRatingTable = SecurityRatingTableDF.merge(ListRatingsDF[['rating_id','agency','official_name','term_type_name','scale_type_name','scale_id']], how='left', left_on='id_rating', right_on='rating_id')
ExtendedSecurityRatingTable = ExtendedSecurityRatingTable.merge(ListScaleValuesDF, how='left', left_on=['scale_id', 'id_value'], right_on=['scale_id', 'rating_value'])
ExtendedSecurityRatingTable = ExtendedSecurityRatingTable[[
    'id_x', 'hid', 'code_name', 'id_value', 'forecast', 'change',
    'date_award', 'role', 'okpo', 'fininstid', 'fintoolid', 'isin',
    'id_rating', 'code', 'shortname_rus', 'rating_id', 'agency',
    'official_name', 'term_type_name', 'scale_type_name', 'scale_id',
    'aggregation_level', 'aggregation_type']].rename(
    columns={
    'id_x': 'id', 'aggregation_level': 'level', 'aggregation_type': 'agg_type'
    }
)
agencies = ['АКРА', 'Эксперт РА', 'НКР', 'НРА', 'Мудис Интерфакс']
ExtendedSecurityRatingTable = ExtendedSecurityRatingTable[ExtendedSecurityRatingTable['agency'].isin(agencies)]
ExtendedSecurityRatingTable = ExtendedSecurityRatingTable[ExtendedSecurityRatingTable['term_type_name'] != 'Краткосрочный']
ExtendedSecurityRatingTable = ExtendedSecurityRatingTable[~ExtendedSecurityRatingTable['id_value'].isin(['****','Приостановлен','Снят'])]
ExtendedSecurityRatingTable = ExtendedSecurityRatingTable[~ExtendedSecurityRatingTable['isin'].isna()]

In [16]:
akra_list = [
    'Старший необеспеченный рейтинг эмиссии',
    # 'Оценка собственной кредитоспособности, национальная шкала',
    # 'Оценка ESG',
    'Кредитный рейтинг Банков и Банковских групп по Национальной шкале',
    'Кредитный рейтинг Нефинансовых компаний по Национальной шкале',
    'Кредитный рейтинг Лизинговых компаний по Национальной шкале',
    'Кредитный рейтинг не Банковских Финансовых организаций по Национальной шкале',
    # 'Оценка собственной кредитоспособности, международная шкала',
    # 'Кредитный рейтинг Международных финансовых институтов по Национальной шкале',
    'Кредитный рейтинг международных финансовых институтов по Международной шкале',
    'Старший обеспеченный рейтинг эмиссии',
    'Кредитный рейтинг субъектов и муниципальных образований по Национальной шкале',
    'Кредитный рейтинг Страховых организаций по Национальной шкале',
    'Субординированный рейтинг эмиссии',
    'Кредитный рейтинг страны, долгосрочный, международная шкала, иностранная валюта',
    'Кредитный рейтинг страны, долгосрочный, международная шкала, национальная валюта',
    'Structured Finance Instrument Rating',
    'Кредитный рейтинг Микрофинансовых организаций по Национальной шкале',
    'Кредитный рейтинг Эмитентов Проектного финансирования по Национальной шкале',
    'Кредитный рейтинг Страховых организаций по Международной шкале',
    # 'Кредитный рейтинг Банков и Банковских групп по Международной шкале',
    # 'Рейтинг эмиссии, международная шкала',
]
expert_list = [
    'Кредитный рейтинг долговых инструментов',
    'Рейтинги кредитоспособности нефинансовых компаний',
    'Рейтинги кредитоспособности банков',
    'Рейтинги кредитоспособности финансовых компаний',
    'Рейтинги кредитоспособности лизинговых компаний',
    # 'Рейтинг ESG',
    # 'Оценка собственной кредитоспособности',
    # 'Рейтинги качества управления',
    'Рейтинги кредитоспособности холдинговых компаний',
    'Рейтинги кредитоспособности микрофинансовых организаций',
    # 'Рейтинги надежности и качества услуг управляющих компаний',
    'Рейтинги кредитоспособности факторинговых компаний',
    'Рейтинги кредитоспособности субъектов федерации и муниципальных образований',
    'Рейтинги финансовой надежности страховых компаний',
    # 'Рейтинг финансовой надежности страховым компаниям по международной шкале',
    # 'Оценка собственной финансовой надежности (ОСФН) по международной шкале',
    # 'Рейтинг кредитоспособности суверенных правительств',
    'Кредитные рейтинги обязательств структурированного финансирования',
    # 'Рейтинги финансовой надежности негосударственных пенсионных фондов',
    # 'Оценка собственной финансовой надежности (ОСФН)',
    # 'Рейтинги кредитоспособности банка Республики Беларусь',
    # 'Оценка собственной кредитоспособности, белорусская шкала',
    # 'Рейтинг кредитоспособности банка-нерезидента по нац. рейтинговой шкале РФ',
    # 'Рейтинги качества паевых инвестиционных фондов',
    # 'Рейтинги надежности облигационных займов',
    'Рейтинг кредитоспособности проектных компаний',
    'Рейтинги кредитоспособности депозитариев',
    # 'Рейтинги кредитоспособности нефинансовых компаний Республики Беларусь',
]
nkr_list = [
    # 'Оценка собственной кредитоспособности, национальная шкала',
    'Кредитный рейтинг НКР по Национальной шкале, Нефинансовые компании',
    # 'ESG-рейтинг',
    'Кредитный рейтинг НКР по Национальной шкале, Банки',
    # 'Кредитный рейтинг НКР по национальной шкале, финансовые компании',
    'Кредитный рейтинг долговых обязательств',
    # 'Кредитный рейтинг НКР по Национальной шкале, Страховые',
    # 'Кредитный рейтинг Холдинговых компаний по Национальной шкале',
]
nra_list = [
    # 'ESG рейтинг',
    'Кредитный рейтинг кредитных организаций',
    # 'Оценка собственной кредитоспособности',
    # 'Рейтинг кредитоспособности холдинговых и финансовых компаний',
    'Кредитный рейтинг нефинансовых компаний, national scale',
    # 'Рейтинг кредитоспособности предприятий Индивидуальный',
    # 'Рейтинг финансовой устойчивости страховых компаний Индивидуальный',
    # 'Рейтинги надежности и качества услуг ИК',
    # 'Кредитные рейтинги страховых компаний',
    # 'Рейтинг кредитоспособности банков Индивидуальный',
    # 'Рейтинг кредитоспособности лизинговых компаний Индивидуальный',
    # 'Рейтинг кредитоспособности микрофинансовых компаний Индивидуальный',
    # 'Кредитный рейтинг лизинговых компаний',
    # 'Рейтинги надежности и качества услуг НПФ',
    # 'Кредитный рейтинг отдельных выпусков облигаций',
    # 'Рейтинг кредитоспособности выпусков облигаций Индивидуальный',
    # 'Рейтинг кредитоспособности инвестиционных компаний Индивидуальный',
    # 'Рейтинг финансовой надежности управляющих компаний Индивидуальный',
    # 'Рейтинги надежности и качества услуг УК',
    # 'Рейтинг финансовой устойчивости компаний по страхованию жизни Индивидуальный',
    # 'Рейтинг кредитоспособности ипотечных компаний Индивидуальный',
    # 'Рейтинг надежности и качества услуг НПФ',
    # 'Рейтинг надежности инвестиционных компаний Индивидуальный',
    # 'Рейтинг надежности регистраторов Индивидуальный',
    # 'Рейтинги надежности и качества услуг регистраторов',
    # 'Рейтинг ESG',
]
moodys_list = [
    # 'NSR Senior Unsecured (Domestic)'
]

ExtendedSecurityRatingTable = ExtendedSecurityRatingTable[
((ExtendedSecurityRatingTable['agency']=='АКРА') & (ExtendedSecurityRatingTable['official_name'].isin(akra_list))) |
((ExtendedSecurityRatingTable['agency']=='Эксперт РА') & (ExtendedSecurityRatingTable['official_name'].isin(expert_list))) |
((ExtendedSecurityRatingTable['agency']=='НКР') & (ExtendedSecurityRatingTable['official_name'].isin(nkr_list))) |
((ExtendedSecurityRatingTable['agency']=='НРА') & (ExtendedSecurityRatingTable['official_name'].isin(nra_list))) |
((ExtendedSecurityRatingTable['agency']=='Мудис Интерфакс') & (ExtendedSecurityRatingTable['official_name'].isin(moodys_list)))
 ]

ExtendedSecurityRatingTable = ExtendedSecurityRatingTable\
.dropna(subset=['isin'])\
.drop_duplicates(subset=["isin", "agency"])\
.reset_index(drop=True)

In [17]:
ExtendedSecurityRatingTablePivot = ExtendedSecurityRatingTable.drop_duplicates().pivot(index='isin', columns='agency', values='id_value')
ExtendedSecurityRatingTablePivot.columns = pd.MultiIndex.from_tuples([('Эмиссия', i) for i in ExtendedSecurityRatingTablePivot.columns])

In [18]:
TransformedFintoolReferenceData = FintoolReferenceDataDF.copy()[['isincode', 'nickname', 'fintooltype', 'country', 'faceftname', 'fintoolid',
                   'issuername', 'issuercountry', 'issuerinn', 'issueruid',
                   'borrowername', 'borrowercountry', 'borrowerinn', 'borroweruid',
                   'isguaranteed', 'guaranteetype', 'guaranteeamount', 'guarantval',
                   ]].drop_duplicates(subset=['isincode'])
TransformedFintoolReferenceData[['fintoolid', 'issueruid', 'borroweruid']] = TransformedFintoolReferenceData[['fintoolid', 'issueruid', 'borroweruid']].fillna(0).astype('int')
TransformedFintoolReferenceData = TransformedFintoolReferenceData.merge(OfferorsGuarantsDF[['fintoolId','fininstid_guarant']], how='left', left_on='fintoolid', right_on='fintoolId')
ids = list(TransformedFintoolReferenceData.loc[~TransformedFintoolReferenceData['fininstid_guarant'].isna(),'fininstid_guarant'].astype('int'))
TransformedEmitents = EmitentsDF[EmitentsDF.fininstid.isin(ids)][['shortname_rus','country','inn','fininstid']]
TransformedEmitents.columns = ['name_guarant','country_guarant','inn_guarant','fininstid']
TransformedFintoolReferenceData = TransformedFintoolReferenceData.merge(TransformedEmitents, how='left', left_on='fininstid_guarant', right_on='fininstid')
TransformedFintoolReferenceData = TransformedFintoolReferenceData.drop(columns=['fintoolId', 'fininstid'])
TransformedFintoolReferenceData = TransformedFintoolReferenceData.set_index('isincode').rename_axis('ISIN')
TransformedFintoolReferenceData = TransformedFintoolReferenceData.rename(
    columns={
        'nickname': ('Эмиссия','Название'),
        'fintooltype': ('Эмиссия','Тип'),
        'country': ('Эмиссия','Страна'), 
        'faceftname': ('Эмиссия','Валюта'), 
        'fintoolid': ('Эмиссия','Id RuData'),
        'issuername': ('Эмитент','Название'), 
        'issuercountry': ('Эмитент','Страна'), 
        'issuerinn': ('Эмитент','ИНН'), 
        'issueruid': ('Эмитент','Id RuData'), 
        'borrowername': ('Заемщик','Название'),
        'borrowercountry': ('Заемщик','Страна'), 
        'borrowerinn': ('Заемщик','ИНН'), 
        'borroweruid': ('Заемщик','Id RuData'), 
        'isguaranteed': ('Гарант','Есть гарантия'),
        'guaranteetype': ('Гарант','Вид гарантии'), 
        'guaranteeamount': ('Гарант','Полнота гарантии'), 
        'guarantval': ('Гарант','Гарантированная сумма'), 
        'fininstid_guarant': ('Гарант','Id RuData'),
        'name_guarant': ('Гарант','Название'), 
        'country_guarant': ('Гарант','Страна'), 
        'inn_guarant': ('Гарант','ИНН')
    }
)
TransformedFintoolReferenceData.columns = pd.MultiIndex.from_tuples(TransformedFintoolReferenceData.columns)

In [19]:
ExtendedFintoolReferenceData = TransformedFintoolReferenceData.join(ExtendedSecurityRatingTablePivot)
new_cols = ExtendedFintoolReferenceData.columns.reindex(['Эмиссия','Эмитент','Заемщик','Гарант'], level=0)
ExtendedFintoolReferenceData = ExtendedFintoolReferenceData.reindex(columns=new_cols[0])

In [20]:
ExtendedCompanyRatingsTable = CompanyRatingsTableDF.merge(ListRatingsDF[['id','agency','official_name','term_type_name','scale_type_name','scale_id']], how='left', left_on='id_rating', right_on='id')
##добавляем уровень рейтинг
ExtendedCompanyRatingsTable = ExtendedCompanyRatingsTable.merge(ListScaleValuesDF, how='left', left_on=['scale_id', 'last'], right_on=['scale_id', 'rating_value'])

In [21]:
ExtendedCompanyRatingsTable = ExtendedCompanyRatingsTable[['name_ra', 'dt', 'last', 'last_dt', 'change', 'forecast', 'advanced',
           'prev', 'prev_dt', 'id_rating', 'code', 'code_type', 'company_name',
           'id_x', 'agency', 'official_name', 'term_type_name', 'scale_type_name',
           'scale_id', 'aggregation_level', 'aggregation_type']].rename(columns={'id_x': 'id', 'aggregation_level': 'level', 'aggregation_type': 'agg_type'})
ExtendedCompanyRatingsTable['id_rating'] = ExtendedCompanyRatingsTable['id_rating'].fillna(0)

In [22]:
ExtendedCompanyRatingsTable = ExtendedCompanyRatingsTable[ExtendedCompanyRatingsTable['agency'].isin(['АКРА','Эксперт РА','НКР','НРА','Мудис Интерфакс'])]
ExtendedCompanyRatingsTable = ExtendedCompanyRatingsTable[~ExtendedCompanyRatingsTable['last'].isin(['****','Приостановлен','Снят'])]
ExtendedCompanyRatingsTable = ExtendedCompanyRatingsTable[ExtendedCompanyRatingsTable['term_type_name'] != 'Краткосрочный']

In [23]:
akra_list = [
    'Старший необеспеченный рейтинг эмиссии',
    # 'Оценка собственной кредитоспособности, национальная шкала',
    # 'Оценка ESG',
    'Кредитный рейтинг Банков и Банковских групп по Национальной шкале',
    'Кредитный рейтинг Нефинансовых компаний по Национальной шкале',
    'Кредитный рейтинг Лизинговых компаний по Национальной шкале',
    'Кредитный рейтинг не Банковских Финансовых организаций по Национальной шкале',
    # 'Оценка собственной кредитоспособности, международная шкала',
    # 'Кредитный рейтинг Международных финансовых институтов по Национальной шкале',
    'Кредитный рейтинг международных финансовых институтов по Международной шкале',
    'Старший обеспеченный рейтинг эмиссии',
    'Кредитный рейтинг субъектов и муниципальных образований по Национальной шкале',
    'Кредитный рейтинг Страховых организаций по Национальной шкале',
    'Субординированный рейтинг эмиссии',
    'Кредитный рейтинг страны, долгосрочный, международная шкала, иностранная валюта',
    'Кредитный рейтинг страны, долгосрочный, международная шкала, национальная валюта',
    'Structured Finance Instrument Rating',
    'Кредитный рейтинг Микрофинансовых организаций по Национальной шкале',
    'Кредитный рейтинг Эмитентов Проектного финансирования по Национальной шкале',
    'Кредитный рейтинг Страховых организаций по Международной шкале',
    # 'Кредитный рейтинг Банков и Банковских групп по Международной шкале',
    # 'Рейтинг эмиссии, международная шкала',
]
expert_list = [
    'Кредитный рейтинг долговых инструментов',
    'Рейтинги кредитоспособности нефинансовых компаний',
    'Рейтинги кредитоспособности банков',
    'Рейтинги кредитоспособности финансовых компаний',
    'Рейтинги кредитоспособности лизинговых компаний',
    # 'Рейтинг ESG',
    # 'Оценка собственной кредитоспособности',
    # 'Рейтинги качества управления',
    'Рейтинги кредитоспособности холдинговых компаний',
    'Рейтинги кредитоспособности микрофинансовых организаций',
    # 'Рейтинги надежности и качества услуг управляющих компаний',
    'Рейтинги кредитоспособности факторинговых компаний',
    'Рейтинги кредитоспособности субъектов федерации и муниципальных образований',
    'Рейтинги финансовой надежности страховых компаний',
    # 'Рейтинг финансовой надежности страховым компаниям по международной шкале',
    # 'Оценка собственной финансовой надежности (ОСФН) по международной шкале',
    # 'Рейтинг кредитоспособности суверенных правительств',
    'Кредитные рейтинги обязательств структурированного финансирования',
    # 'Рейтинги финансовой надежности негосударственных пенсионных фондов',
    # 'Оценка собственной финансовой надежности (ОСФН)',
    # 'Рейтинги кредитоспособности банка Республики Беларусь',
    # 'Оценка собственной кредитоспособности, белорусская шкала',
    # 'Рейтинг кредитоспособности банка-нерезидента по нац. рейтинговой шкале РФ',
    # 'Рейтинги качества паевых инвестиционных фондов',
    # 'Рейтинги надежности облигационных займов',
    'Рейтинг кредитоспособности проектных компаний',
    'Рейтинги кредитоспособности депозитариев',
    # 'Рейтинги кредитоспособности нефинансовых компаний Республики Беларусь',
]
nkr_list = [
    # 'Оценка собственной кредитоспособности, национальная шкала',
    'Кредитный рейтинг НКР по Национальной шкале, Нефинансовые компании',
    # 'ESG-рейтинг',
    'Кредитный рейтинг НКР по Национальной шкале, Банки',
    # 'Кредитный рейтинг НКР по национальной шкале, финансовые компании',
    'Кредитный рейтинг долговых обязательств',
    # 'Кредитный рейтинг НКР по Национальной шкале, Страховые',
    # 'Кредитный рейтинг Холдинговых компаний по Национальной шкале',
]
nra_list = [
    # 'ESG рейтинг',
    'Кредитный рейтинг кредитных организаций',
    # 'Оценка собственной кредитоспособности',
    # 'Рейтинг кредитоспособности холдинговых и финансовых компаний',
    'Кредитный рейтинг нефинансовых компаний, national scale',
    # 'Рейтинг кредитоспособности предприятий Индивидуальный',
    # 'Рейтинг финансовой устойчивости страховых компаний Индивидуальный',
    # 'Рейтинги надежности и качества услуг ИК',
    # 'Кредитные рейтинги страховых компаний',
    # 'Рейтинг кредитоспособности банков Индивидуальный',
    # 'Рейтинг кредитоспособности лизинговых компаний Индивидуальный',
    # 'Рейтинг кредитоспособности микрофинансовых компаний Индивидуальный',
    # 'Кредитный рейтинг лизинговых компаний',
    # 'Рейтинги надежности и качества услуг НПФ',
    # 'Кредитный рейтинг отдельных выпусков облигаций',
    # 'Рейтинг кредитоспособности выпусков облигаций Индивидуальный',
    # 'Рейтинг кредитоспособности инвестиционных компаний Индивидуальный',
    # 'Рейтинг финансовой надежности управляющих компаний Индивидуальный',
    # 'Рейтинги надежности и качества услуг УК',
    # 'Рейтинг финансовой устойчивости компаний по страхованию жизни Индивидуальный',
    # 'Рейтинг кредитоспособности ипотечных компаний Индивидуальный',
    # 'Рейтинг надежности и качества услуг НПФ',
    # 'Рейтинг надежности инвестиционных компаний Индивидуальный',
    # 'Рейтинг надежности регистраторов Индивидуальный',
    # 'Рейтинги надежности и качества услуг регистраторов',
    # 'Рейтинг ESG',
]
moodys_list = [
    # 'NSR Senior Unsecured (Domestic)'
]

ExtendedCompanyRatingsTable = ExtendedCompanyRatingsTable[
((ExtendedCompanyRatingsTable['agency']=='АКРА') & (ExtendedCompanyRatingsTable['official_name'].isin(akra_list))) |
((ExtendedCompanyRatingsTable['agency']=='Эксперт РА') & (ExtendedCompanyRatingsTable['official_name'].isin(expert_list))) |
((ExtendedCompanyRatingsTable['agency']=='НКР') & (ExtendedCompanyRatingsTable['official_name'].isin(nkr_list))) |
((ExtendedCompanyRatingsTable['agency']=='НРА') & (ExtendedCompanyRatingsTable['official_name'].isin(nra_list))) |
((ExtendedCompanyRatingsTable['agency']=='Мудис Интерфакс') & (ExtendedCompanyRatingsTable['official_name'].isin(moodys_list)))
]

In [24]:
ExtendedCompanyRatingsTable.sort_values(by=['agency', 'code', 'dt'], ascending=True, inplace=True)
ExtendedCompanyRatingsTable = ExtendedCompanyRatingsTable.groupby(['agency', 'code']).last().reset_index()
ExtendedCompanyRatingsTable = ExtendedCompanyRatingsTable.dropna(subset=['code'])
ExtendedCompanyRatingsTable['code'] = ExtendedCompanyRatingsTable['code'].astype(int)

In [25]:
ExtendedCompanyRatingsPivot = ExtendedCompanyRatingsTable.pivot(index='code', columns='agency', values='last')
df1 = ExtendedFintoolReferenceData.copy()
df1.columns =df1.columns.to_flat_index()
for k in ['Эмитент','Заемщик','Гарант']:
    df2 = ExtendedCompanyRatingsPivot.copy()
    df2.columns = [(k, i) for i in df2.columns]
    df1 = df1.merge(df2, how='left', left_on=[(k, 'Id RuData')], right_index=True)
df1.columns = pd.MultiIndex.from_tuples(df1.columns)
new_cols = df1.columns.reindex(['Эмиссия', 'Эмитент', 'Заемщик', 'Гарант'], level=0)
df1 = df1.reindex(columns=new_cols[0])
ExtendedFintoolReferenceData = df1

#### Шаг 3. Рейтинги облигаций из фактовой таблицы бумаг FintoolReferenceData. Рейтинги облигаций из фактовой таблицы компаний CompanyRatingsTable

In [26]:
BondRatings = ExtendedFintoolReferenceData['Эмиссия'].reset_index()
id_vars = BondRatings.columns[:6]
value_vars = BondRatings.columns[6:]
meltBonds = pd.melt(BondRatings, id_vars=id_vars, value_vars=value_vars, var_name='agency', value_name='rate')
meltBonds = meltBonds[~meltBonds.rate.isna()].sort_values('Id RuData')
meltBonds = meltBonds[meltBonds["Тип"] == 'Облигация']

In [27]:
df = EmitentsDF[EmitentsDF['fininstid'].isin(ExtendedCompanyRatingsPivot.index)]
CompanyRatings = df.merge(ExtendedCompanyRatingsPivot, left_on='fininstid', right_index=True, how='left')
CompanyRatings = pd.concat([
    CompanyRatings[["id_emitent", "shortname_rus", "inn", "update_date", "country_oksm", "have_rating", "have_risk", "tin", "fininstid", "reg_code", "lei_code"]]
    , CompanyRatings.iloc[:, CompanyRatings.columns.get_loc('rn')+1:]
], axis=1)
id_vars = CompanyRatings.columns[:11]
value_vars = CompanyRatings.columns[11:]
meltCompanies = pd.melt(CompanyRatings, id_vars=id_vars, value_vars=value_vars, var_name='agency', value_name='rate')
meltCompanies = meltCompanies[meltCompanies['rate'].notnull()].sort_values('id_emitent')
meltCompanies['inn'] = np.where(meltCompanies['country_oksm'] == 643, meltCompanies['inn'], meltCompanies['tin'] )
meltCompanies['country_oksm'] = meltCompanies['country_oksm'].astype(np.int32)
meltCompanies['type'] = "ЮЛ"

In [28]:
meltBonds.rename(columns={
    "Id RuData": "id_emitent",
    "Название": "company_name", 
    "Тип": "rate_type",
    "ISIN": "inn/isin",
    "Страна": "country"
    }, inplace=True)
meltCompanies.rename(columns={
    "id_rudata": "id_emitent",
    "shortname_rus": "company_name", 
    "type": "rate_type",
    "inn": "inn/isin",
    "country_oksm": "country_code"
    }, inplace=True)
meltBonds["fininstid"] = np.nan
meltBonds["reg_code"] = np.nan
meltBonds["lei_code"] = np.nan
meltBonds["report_date"] = pd.to_datetime(REPORT_DATE)
meltCompanies["report_date"] = pd.to_datetime(REPORT_DATE)

Справочник кодов стран ОКСМ

In [29]:
countries = client.query_df(
    """
    SELECT DISTINCT country, alpha2
    FROM countries
    """)
countries["country"] = countries["country"].astype(np.int32)
co = countries.set_index("alpha2").country.to_dict()
meltBonds["country_code"] = meltBonds["country"].map(co)

#### Шаг 4. Получаем результирующий результат по рейтингам облигаций и компаний и экспорт в excel

In [30]:
meltBonds = meltBonds[["id_emitent", "fininstid", "company_name", "inn/isin", "country_code", "agency", "rate", "report_date", "rate_type", "reg_code", "lei_code"]]
meltCompanies = meltCompanies[["id_emitent", "fininstid", "company_name", "inn/isin", "country_code", "agency", "rate", "report_date", "rate_type", "reg_code", "lei_code"]]
ResultRatings = pd.concat([meltBonds, meltCompanies], axis=0)
ResultRatings['id_emitent'] = ResultRatings['id_emitent'].fillna(0).astype(int)
ResultRatings['fininstid'] = ResultRatings['fininstid'].fillna(0).astype(int)
ResultRatings['reg_code'] = ResultRatings['reg_code'].astype(str).replace('None', '').replace('<NA>', '').fillna('')
ResultRatings['lei_code'] = ResultRatings['lei_code'].astype(str).replace('None', '').replace('<NA>', '').fillna('')

/var/folders/g4/mpm4njl93p547kbhxbvqlm480000gn/T/ipykernel_85637/1795824870.py:3: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ResultRatings = pd.concat([meltBonds, meltCompanies], axis=0)

In [31]:
ResultRatings.to_csv('./data/output/ratings.csv', index=False, sep='\t', header=True)
ResultRatings.to_excel('./data/output/ratings.xlsx', index=False)

In [32]:
from src.utils.send_email import main
main("ratings.csv", 'ratings.xlsx')

In [ ]:
ExtendedCompanyRatingsPivot = ExtendedCompanyRatingsTable.pivot(index='code', columns='agency', values='last')
df1 = ExtendedFintoolReferenceData.copy()
df1.columns =df1.columns.to_flat_index()
for k in ['Эмитент','Заемщик','Гарант']:
    df2 = ExtendedCompanyRatingsPivot.copy()
    df2.columns = [(k, i) for i in df2.columns]
    df1 = df1.merge(df2, how='left', left_on=[(k, 'Id RuData')], right_index=True)
df1.columns = pd.MultiIndex.from_tuples(df1.columns)
new_cols = df1.columns.reindex(['Эмиссия', 'Эмитент', 'Заемщик', 'Гарант'], level=0)
df1 = df1.reindex(columns=new_cols[0])
ExtendedFintoolReferenceData = df1

#### Шаг 3. Рейтинги облигаций из фактовой таблицы бумаг FintoolReferenceData. Рейтинги облигаций из фактовой таблицы компаний CompanyRatingsTable

In [ ]:
BondRatings = ExtendedFintoolReferenceData['Эмиссия'].reset_index()
id_vars = BondRatings.columns[:6]
value_vars = BondRatings.columns[6:]
meltBonds = pd.melt(BondRatings, id_vars=id_vars, value_vars=value_vars, var_name='agency', value_name='rate')
meltBonds = meltBonds[~meltBonds.rate.isna()].sort_values('Id RuData')
meltBonds = meltBonds[meltBonds["Тип"] == 'Облигация']

In [ ]:
df = EmitentsDF[EmitentsDF['fininstid'].isin(ExtendedCompanyRatingsPivot.index)]
CompanyRatings = df.merge(ExtendedCompanyRatingsPivot, left_on='fininstid', right_index=True, how='left')
CompanyRatings = pd.concat([
    CompanyRatings[["id_emitent", "shortname_rus", "inn", "update_date", "country_oksm", "have_rating", "have_risk", "tin", "fininstid", "reg_code", "lei_code"]]
    , CompanyRatings.iloc[:, CompanyRatings.columns.get_loc('rn')+1:]
], axis=1)
id_vars = CompanyRatings.columns[:11]
value_vars = CompanyRatings.columns[11:]
meltCompanies = pd.melt(CompanyRatings, id_vars=id_vars, value_vars=value_vars, var_name='agency', value_name='rate')
meltCompanies = meltCompanies[meltCompanies['rate'].notnull()].sort_values('id_emitent')
meltCompanies['inn'] = np.where(meltCompanies['country_oksm'] == 643, meltCompanies['inn'], meltCompanies['tin'] )
meltCompanies['country_oksm'] = meltCompanies['country_oksm'].astype(np.int32)
meltCompanies['type'] = "ЮЛ"

In [ ]:
meltBonds.rename(columns={
    "Id RuData": "id_emitent",
    "Название": "company_name", 
    "Тип": "rate_type",
    "ISIN": "inn/isin",
    "Страна": "country"
    }, inplace=True)
meltCompanies.rename(columns={
    "id_rudata": "id_emitent",
    "shortname_rus": "company_name", 
    "type": "rate_type",
    "inn": "inn/isin",
    "country_oksm": "country_code"
    }, inplace=True)
meltBonds["fininstid"] = np.nan
meltBonds["reg_code"] = np.nan
meltBonds["lei_code"] = np.nan
meltBonds["report_date"] = pd.to_datetime(REPORT_DATE)
meltCompanies["report_date"] = pd.to_datetime(REPORT_DATE)

Справочник кодов стран ОКСМ

In [ ]:
countries = client.query_df(
    """
    SELECT DISTINCT country, alpha2
    FROM countries
    """)
countries["country"] = countries["country"].astype(np.int32)
co = countries.set_index("alpha2").country.to_dict()
meltBonds["country_code"] = meltBonds["country"].map(co)

#### Шаг 4. Получаем результирующий результат по рейтингам облигаций и компаний и экспорт в excel

In [ ]:
meltBonds = meltBonds[["id_emitent", "fininstid", "company_name", "inn/isin", "country_code", "agency", "rate", "report_date", "rate_type", "reg_code", "lei_code"]]
meltCompanies = meltCompanies[["id_emitent", "fininstid", "company_name", "inn/isin", "country_code", "agency", "rate", "report_date", "rate_type", "reg_code", "lei_code"]]
ResultRatings = pd.concat([meltBonds, meltCompanies], axis=0)
ResultRatings['id_emitent'] = ResultRatings['id_emitent'].fillna(0).astype(int)
ResultRatings['fininstid'] = ResultRatings['fininstid'].fillna(0).astype(int)
ResultRatings['reg_code'] = ResultRatings['reg_code'].astype(str).replace('None', '').replace('<NA>', '').fillna('')
ResultRatings['lei_code'] = ResultRatings['lei_code'].astype(str).replace('None', '').replace('<NA>', '').fillna('')

In [ ]:
ResultRatings.to_csv('./data/output/ratings.csv', index=False, sep='\t', header=True)
ResultRatings.to_excel('./data/output/ratings.xlsx', index=False)

In [ ]:
from src.utils.send_email import main
main("ratings.csv", 'ratings.xlsx')