File: stocks.ipynb\
Author: alexkobz\
Date: 19-11-2024\
Modified: 31-01-2025 (DSRFU-351)\
Task: DSRFU-277

#### Шаг 0. Импорт и получение токена

In [1]:
import requests
import pandas as pd
import numpy as np
import nest_asyncio; nest_asyncio.apply()
from datetime import datetime as dt, date
from src.utils.get_date import last_day_month, last_day_month_str

# последний день месяца
REPORT_DATE = last_day_month
REPORT_DATE_STR = last_day_month_str
# увеличиваем количество столбцов и строк для просмотра
pd.set_option('display.max_rows', 200, 'display.max_columns', 200)

Unexpected Http Driver Exception

Error HTTPConnectionPool(host='host.docker.internal', port=8124): Max retries exceeded with url: /? (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x17c6bf400>: Failed to resolve 'host.docker.internal' ([Errno 8] nodename nor servname provided, or not known)")) executing HTTP request attempt 1 (http://host.docker.internal:8124)

In [2]:
from src.sources.rudata.RuDataMethod import Account, FintoolReferenceData, CalendarV2, AccruedInterestOnDate, FloaterData, ExchangeTree, Emitents, CurrencyRate
Acc = Account()

#### Шаг 1. Загрузка stage таблиц

[FintoolReferenceData](https://docs.efir-net.ru/dh2/#/Info/FintoolReferenceData?id=post-fintoolreferencedata) - Получить расширенный справочник по финансовым инструментам.

In [3]:
FintoolReferenceDataDF = FintoolReferenceData().df
FintoolReferenceDataDF.head()

,facevalue_m,faceftname_m,sumissuevol_m,summarketvol_m,numcoupons_m,nrdcode,regcode_m,regdate_m,regdistdate_m,begdistdate_m,enddistdate_m,endmtydate_m,daysall_m,fullname_nrd,rpregorg_nrd,rpstate_nrd,issuenumber,currentfacevalue_nrd,isqualified_nrd,bondseries,islombardcbr_nrd,numcoupons_nrd,facevalue_nrd,faceftname_nrd,summarketvol_nrd,regcode_nrd,regdate_nrd,regorg_nrd,begdistdate_nrd,daysall_nrd,enddistdate_nrd,endmtydate_nrd,regdistdate_nrd,sumissuevol_nrd,drqty,isincodebase_nrd,nrdcompcode,shqty,summarketvolorig_nrd,issuername_nrd,planmtydate_nrd,firstcoupondate_nrd,depositary_nrd,registrar_nrd,placeprice_nrd,micexlist_nrd,minlot_nrd,formarketbonds_nrd,registraracctype_nrd,registraracctypedate_nrd,facialacc_nrd,acc_open_date_nrd,fraction_nrd,specialized_depo_nrd,cmp_code_nsd_issuer_nrd,cmp_code_nsd_managing_nrd,ratetypenamerus_nrd,ratetypenameeng_nrd,coupontypename_nrd,base_month,base_year,basis_nrd,sectypenamerus_nrd,sectypenameeng_nrd,secformnamerus_nrd,secformnameeng_nrd,sectypenamebr_nrd,secstaterus_nrd,secstateeng_nrd,placementtype_nrd,share_category_name_nrd,share_category_name_en_nrd,dr_category_name_nrd,dr_category_name_en_nrd,company_state_name_nrd,rate_type_id,cp_type_id,coupon_period_base_id,sec_type_id,sec_form_id,sec_state_id,placement_type_id,share_category_id,dr_category_mn,company_state_mn,sector4212u,sna2008,fullname_en_nrd,seniorityname,fintoolid,moex_code,moex_name,fullname,isin144a,isincode,nickname,progfintoolid,regcode,regdate,regorg,amortisedmty,basis,bondstructuralpar,cfi,coupontype,fintooltype,guaranteeamount,guaranteetype,haveoffer,isconvertible,isguaranteed,maturitygroup,securitization,accruedintcalctype,country,couponperyear,faceftname,facevalue,guarantval,havedefault,numcoupons,status,sumissueval,sumissuevol,summarketval,summarketvol,borrowername,borrowerokpo,borrowersector,borroweruid,borrowerinn,borrowercountry,borrowerregionname,issuername,issuerokpo,issuersector,issueruid,issuerinn,issuercountry,issuerregionname,assetssector,numguarantors,begdistdate,begmtydate,daysall,enddistdate,endmtydate,privatedist,regdistdate,securitytype,securitykind,nominaltype,update_time,isregion,nsd_service,raterevisionsperyear,floatratename,issubordinated,note,listing_level,havecovenant,haverepayment,haveindexedfv,numdecimals,couponperiod,ismatched,firstcoupondate,couponrate,iscomplicated,available_for_unqualified,sec_type_br_code,original_country,qualified_test_id,qualified_test_id_tm,base_asset_fintoolid,isqualified,listing_level_spb,have_mm_moex,have_mm_spb,beg_book_date,seniority,tradesite,current_coupontype,profit_type,counter,rn
0,2.0,2.0,2.0,2.0,2.0,None,0.0,0.0,2.0,2.0,2.0,2.0,2.0,None,None,None,None,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None,None,None,NaN,None,None,None,NaN,NaN,None,None,NaN,NaN,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,520,S2,None,Старшие необеспеченные,226059,None,None,"Соединённые Штаты Америки, 5-летние ноты с пог...",None,US91282CGH88,США-2-280131-об,NaN,None,None,None,0.0,act/act,None,None,Постоянный,Облигация,None,Необеспеченные,0.0,0.0,0.0,Среднесрочные,None,1.0,US,2.0,USD,100.00,NaN,0.0,10.0,В обращении,4.400000e+10,4.400000e+08,4.300001e+10,4.300001e+08,Правительство США,None,Государственные,95111.0,None,US,None,Минфин США,None,Государственные,95112.0,None,US,None,None,0.0,2023-01-31T00:00:00,None,1826.0,2023-01-31T00:00:00,2028-01-31T00:00:00,0.0,2023-01-31T00:00:00,Гос,Классические,Постоянный,2025-08-15T10:20:36,NaN,Нет информации,2.0,None,NaN,None,NaN,False,False,False,2.0,184.0,True,2023-01-31T00:00:00,3.5,False,0,OTHER,US,1000,1000,NaN,False,NaN,0,0,None,416.0,NaN,Фиксированный,Постоянный,107094,90113
1,2.0,2.0,2.0,2.0,2.0,None,0.0,0.0,2.0,2.0,2.0,2.0,2.0,None,None,None,None,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None,None,None,NaN,None,None,None,NaN,NaN,None,None,NaN,NaN,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,520,S2,None,Старшие необеспеченные,226060,None,None,"Соединённые Штаты Америки, 7-летние ноты с пог...",None,US91282CGJ45,США-300131-об,NaN,None,None,None,0.0,act/act,None,None,Постоянный,Облигация,None,Необеспеченные,0.0,0.0,0.0,Среднесрочные,None,1.0,US,2.0,USD,100.00,NaN,0.0,14.0,В обращении,3.600000e+10,3.600000e+08,3.500001e+10,3.500001e+08,Правительство США,None,Государственные,95111.0,None,US,None,Минфин США,None,Государственные,95112.0,None,US,None,None,0.0,2023-01-31T00:00:00,None,2557.0,2023-01-31T00:00:00,2030-01-31T00:00:00,0.0,2023-01-31T00:00:00,Гос,Классические,Постоянный,2025-08-15T10:20:36,NaN,Нет информации,2.0,None,NaN,None,NaN,False,False,False,2.0,184.0,True,2023-01-31T00:00:00,3.5,False,0,OTHER,US,1000,1000,NaN,False,NaN,0,0,None,416.0,NaN,Фиксированный,Постоянный,107094,90114
2,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None,None,None,NaN,None,None,None,NaN,NaN,None,None,NaN,NaN,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,520,S2,None,Старшие необеспеченные,226061,None,None,"Германия, государственные облигации (Bubills) ...",None,DE000BU0E006,Германия-2-12-2023-об,NaN,None,None,None,0.0,act/360,None,None,Дисконтный,Облигация,None,Необеспеченные,0.0,0.0,0.0,Краткосрочные,None,1.0,DE,NaN,EUR,0.01,NaN,0.0,NaN,Погашен,1.300000e+10,1.300000e+12,1.300000e+10,1.300000e+12,Правительство Германии,None,Государственные,95093.0,None,DE,None,German Finance Agency,None,Государственные,95309.0,DE137223325,DE,None,None,0.0,2023-01-30T00:00:00,None,317.0,2023-01-30T00:00:00,2023-12-13T00:00:00,0.0,2023-01-30T00:00:00,Гос,Классические,Постоянный,2024-11-22T13:50:27,NaN,Нет информации,NaN,None,NaN,None,NaN,False,False,False,6.0,NaN,True,None,0.0,False,0,BON5,DE,1000,1000,NaN,False,NaN,0,0,None,416.0,NaN,None,Дисконтный,107094,90115
3,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None,None,None,NaN,None,None,None,NaN,NaN,None,None,NaN,NaN,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,S112,None,None,226062,None,None,"""Головной институт по проектированию предприят...",None,None,ГипроВТИ-1-ао,NaN,1-01-55176-D,2004-01-30T00:00:00,ФКЦБ,NaN,None,None,None,None,Акция,None,None,NaN,0.0,NaN,None,None,NaN,RU,NaN,RUB,10.00,NaN,NaN,NaN,В обращении,2.469297e+07,2.469297e+06,2.469297e+07,2.469297e+06,None,None,None,NaN,None,None,None,ГипроВТИ,27822049,Строительство,124634.0,1657028318,RU,Республика Татарстан,None,NaN,None,None,NaN,None,None,0.0,None,Обыкн-ая,Осн-ой,None,2023-01-21T00:25:00,NaN,Нет информации,NaN,None,NaN,None,NaN,None,None,None,NaN,NaN,None,None,NaN,None,0,SHS3,RU,1000,1000,NaN,None,NaN,0,0,None,NaN,NaN,None,None,107094,90116
4,2.0,2.0,NaN,NaN,NaN,None,2.0,2.0,2.0,0.0,0.0,NaN,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None,None,None,NaN,None,None,None,NaN,NaN,None,None,NaN,NaN,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,S112,None,None,226063,None,None,"""Рабочий"", ЗАО, акции обыкновенные бездокумент...",None,None,Рабочий-2-ао,NaN,1-02-55112-P,2005-04-19T00:00:00,ФСФР,NaN,None,None,None,None,Акция,None,None,NaN,0.0,NaN,None,None,NaN,RU,NaN,RUB,10.00,NaN,NaN,NaN,Погашен,2.456072e+07,2.456072e+06,NaN,NaN,None,None,None,NaN,None,None,None,Рабочий,00336548,Пищевая промышленность и с/х,124635.0,6167008311,RU,Ростовская область,None,NaN,None,None,NaN,None,2025-09-25T00:00:00,0.0,2005-07-15T00:00:00,Обыкн-ая,Осн-ой,None,2025-09-26T10:50:33,NaN,Нет информации,NaN,None,NaN,None,NaN,None,None,None,NaN,NaN,None,None,NaN,None,0,SHS3,RU,1000,1000,NaN,None,NaN,0,0,None,NaN,NaN,None,None,107094,90117

In [4]:
CalendarDF = CalendarV2().df
CalendarDF.head()

,action_id,fintool_rusbonds_type,issuer_rusbonds_type,original_country,update_date,securityType,privateDist,country,listing_level,type_convertation,literid_typeoperation,act_code,status,status_date,literid_status,pay_decision,unpayed_decision_reason,payed_details,fininstId,issuerName,id,isiNcode,regCode,nickname,nrDcode,finToolID,type,eventID,typeOperation,rateDate,beginPeriod,endPeriod,couponPeriod,couponRate,pay1Bond,moneyFlowVal,eventTotalVol,daysFromDist,execution,payDate,fixDate,mtyDate,mtyPart,offerDate,buyBackPrice,begOrder,endOrder,eventPeriod,convert2FinToolID,coefficient,beginConvDate,endConvDate,defaultID,defaultType,typeEvent,defaultDate,realPayDate,note,eventType,eventDate,beginEventPer,value,faceFTName,pay1Security,moneyFlowPlan,protocolDate,pay1Bond_frac,currencyFTName,paymentCurrencyFTName,revisedPay1Bond,recomendPay1Security,recomendRateDate,recomendFixDate,recomendPayDate,recomendPayDateNominee,fintoolType,dividend_currency,ex_dividend_date,declared_pay_date_nominee,counter,rn,couponRateDatePlan
0,275537,C,None,CH,2023-09-04T15:29:37,ЕвроКорп,False,GG,NaN,None,1098.0,INTR,None,None,NaN,None,None,None,97435.0,EFG International Finance,CH0434913882,CH0434913882,CH0434913882,EFG Internat-53-2021-евро,CH0434913882,146963,None,8.0,Прочий,None,2020-04-17T00:00:00,2020-07-16T00:00:00,90.0,12.0,30.0,300000.0,10000.0,630.0,E,2020-07-16T00:00:00,2020-07-15T00:00:00,None,NaN,None,NaN,None,None,90.0,None,NaN,None,None,NaN,None,None,None,None,None,CPN,2020-07-16T00:00:00,2020-04-17T00:00:00,12.0,USD,NaN,NaN,None,30.0,USD,USD,NaN,0.0,None,None,None,None,Облигация,None,None,None,957638,291285,None
1,458465,C,None,CH,2020-09-29T09:15:52,ЕвроКорп,False,GG,NaN,None,175.0,MCAL/BN,None,None,NaN,None,None,None,97435.0,EFG International Finance,CH0434913882,CH0434913882,CH0434913882,EFG Internat-53-2021-евро,CH0434913882,146963,None,6.0,C,None,None,None,NaN,NaN,1000.0,NaN,NaN,630.0,E,2020-07-16T00:00:00,None,None,NaN,2020-07-16T00:00:00,100.0,None,None,NaN,None,NaN,None,None,NaN,None,None,None,None,None,CALL,2020-07-16T00:00:00,None,100.0,USD,NaN,NaN,None,0.0,None,None,NaN,0.0,None,None,None,None,Облигация,None,None,None,957638,291343,None
2,458466,C,None,CH,2020-09-29T09:15:52,ЕвроКорп,False,GG,NaN,None,175.0,MCAL/BN,None,None,NaN,None,None,None,97435.0,EFG International Finance,CH0434913882,CH0434913882,CH0434913882,EFG Internat-53-2021-евро,CH0434913882,146963,None,7.0,C,None,None,None,NaN,NaN,1000.0,NaN,NaN,721.0,E,2020-10-15T00:00:00,None,None,NaN,2020-10-15T00:00:00,100.0,None,None,NaN,None,NaN,None,None,NaN,None,None,None,None,None,CALL,2020-10-15T00:00:00,None,100.0,USD,NaN,NaN,None,0.0,None,None,NaN,0.0,None,None,None,None,Облигация,None,None,None,957638,305697,None
3,285554,C,None,CH,2023-09-04T15:29:37,ЕвроКорп,False,GG,NaN,None,1098.0,INTR,None,None,NaN,None,None,None,97435.0,EFG International Finance,CH0434913882,CH0434913882,CH0434913882,EFG Internat-53-2021-евро,CH0434913882,146963,None,9.0,Прочий,None,2020-07-16T00:00:00,2020-10-15T00:00:00,89.0,12.0,30.0,300000.0,10000.0,721.0,E,2020-10-15T00:00:00,2020-10-14T00:00:00,None,NaN,None,NaN,None,None,89.0,None,NaN,None,None,NaN,None,None,None,None,None,CPN,2020-10-15T00:00:00,2020-07-16T00:00:00,12.0,USD,NaN,NaN,None,30.0,USD,USD,NaN,0.0,None,None,None,None,Облигация,None,None,None,957638,305939,None
4,303858,C,None,CH,2023-09-04T15:29:37,ЕвроКорп,False,GG,NaN,None,1098.0,INTR,None,None,NaN,None,None,None,97435.0,EFG International Finance,CH0434913882,CH0434913882,CH0434913882,EFG Internat-53-2021-евро,CH0434913882,146963,None,10.0,Прочий,None,2020-10-15T00:00:00,2021-01-15T00:00:00,90.0,12.0,30.0,300000.0,10000.0,813.0,E,None,None,None,NaN,None,NaN,None,None,90.0,None,NaN,None,None,NaN,None,None,None,None,None,CPN,2021-01-15T00:00:00,2020-10-15T00:00:00,12.0,USD,NaN,NaN,None,30.0,USD,USD,NaN,0.0,None,None,None,None,Облигация,None,None,None,957638,321231,None

In [5]:
AccruedInterestOnDateDF = AccruedInterestOnDate().df
AccruedInterestOnDateDF.head()

,fintoolId,shiftDays,shiftTypeSource,typeCurrency,date,accruedInterest,accruedInterestPct,currentFaceValue,currentFaceValuePct,calculationType,error,faceValueCurrency,accruedInterestCurrency,faceValueLastKnownDate
0,4000,0,Calendar,None,2025-10-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,None,RUB,RUB,2025-10-31T00:00:00
1,4001,0,Calendar,None,2025-10-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,None,RUB,RUB,2025-10-31T00:00:00
2,4002,0,Calendar,None,2025-10-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,None,RUB,RUB,2025-10-31T00:00:00
3,4003,0,Calendar,None,2025-10-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,None,RUB,RUB,2025-10-31T00:00:00
4,4004,0,Calendar,None,2025-10-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,None,RUB,RUB,2025-10-31T00:00:00

In [6]:
FloaterDataDF = FloaterData().df
FloaterDataDF.head()

,fintoolId,beg_period,end_period,start_point,model_type,date_pub_n,date_pub_type,date_fix_n,date_fix_type,bases
0,11193,2000-12-01T00:00:00,2050-12-01T00:00:00,E,single,NaN,None,10.0,W,"[{""base_no"": 1, ""calc_type"": ""FIX"", ""base_fint..."
1,30316,2025-09-18T00:00:00,2025-12-18T00:00:00,B,single,NaN,None,2.0,W,"[{""base_no"": 5, ""calc_type"": ""FIX"", ""base_fint..."
2,36325,2009-08-27T00:00:00,2028-09-15T00:00:00,B,single,NaN,None,1.0,W,"[{""base_no"": 1, ""calc_type"": ""FIX"", ""base_fint..."
3,57394,2011-11-21T00:00:00,2028-10-30T00:00:00,B,single,NaN,None,5.0,W,"[{""base_no"": 2, ""calc_type"": ""PER"", ""base_fint..."
4,59702,2013-12-11T00:00:00,2028-11-22T00:00:00,B,single,NaN,None,5.0,C,"[{""base_no"": 2, ""calc_type"": ""FIX"", ""base_fint..."

In [7]:
ExchangeTreeDF = ExchangeTree().df
ExchangeTreeDF.head()

,id,id_parent,shortname_rus,shortname_eng,fullname_rus,fullname_eng,sort_order,update_date,counter,rn
0,1,0,РТС,RTS,Московская Биржа - РТС,RTS,12,2020-12-28T17:03:09,242,17
1,2,1,РТС,RTS,РТС индексы,RTS indexes,2,2020-12-28T17:03:09,242,4
2,8,1,ФОРТС,FORTS,FORTS,FORTS,8,2020-12-28T17:03:09,242,11
3,9,0,"ПАО ""СПБ""",PJSC «SPB»,"ПАО ""СПБ""",PJSC «SPB»,20,2020-12-28T17:03:09,242,21
4,11,0,МБ,MX,Московская Биржа,Moscow Exchange,11,2020-12-28T17:03:09,242,16

In [8]:
EmitentsDF = Emitents().df
EmitentsDF.head()

,id_emitent,fininstid,shortname_rus,shortname_eng,inn,okpo,ogrn,code,sector,legal_address,phone,www,update_date,fullname_rus_nrd,fullname_eng_nrd,shortname_rus_nrd,shortname_eng_nrd,company_type_short_name,state_reg_num,state_reg_date,state_reg_name,egrul_date,egrul_organ_name,country,lei_code,bik,fax,e_mail,credit_cmp,is_bank_4_non_resident,swift,country_oksm,country_oksm_cbr,country_name_rus,country_name_eng,region_inn,region_soato,region_name,fullname_rus,sparkid,br_fcsm_reg_code,capital,capital_unit,okved,oecd_lvl,oktmo,okato,post_address,okopf,okogu,have_rating,have_risk,is_finorg,is_control_by_finorg,is_gov_or_cb,on_behalf_of_state,is_subjectrf,is_cis_reg,issuer_nrd,tin,kpp,state_reg_number,market_id_nrd,market_name_rus_nrd,market_name_eng_nrd,sp_rx_entity_id,sp_shortname,mds_shortname,mds_org_id,fch_id,fch_shortname,is_monopoly,is_strategic,ifo_list,isregion,sic,sector4212u,sna2008,reg_code,reg_date,reg_org,note,primary_reg_date,inn_fle,other_tin,other_tin_name,okfs_id,okfs_name,is_branch,counter,rn
0,24128,7962,Элара,ELARA,2129017646,24322961,1022101269123,ELAR,Машиностроение,"428017,Чувашская Республика - Чувашия, г. Чебо...",(903)3582649; (8352)425303; (8352)453650,www.elara.ru,2022-11-24T16:45:21.469925,None,None,None,None,НАО,None,None,None,None,None,RUS,None,None,None,audit@elara.ru,None,None,None,643.0,643.0,РОССИЯ,Russia,21,97,Чувашская Республика,"""Научно-производственный комплекс ""ЭЛАРА"" имен...",212225.0,55813-D,105368.0,RUB,26.51.1,7,97701000001,97401000000,"428017,Чувашская Республика - Чувашия, г. Чебо...",12267,4210008,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,213001001,None,NaN,None,None,None,None,None,None,None,None,0,1,None,0.0,3810,None,S112,1022101269123,2002-08-16T00:00:00,Администрация Московского Района Города Чебокс...,None,1992-05-13T00:00:00,None,None,ДопИНН,16,Частная собственность,0,43853,849
1,24129,66181,Элсиб,NPO ELSIB,5403102702,05757937,1025401300748,ELIB,Машиностроение,"630088,Новосибирская обл., г. Новосибирск, ул....",(383)2278150; (383)2278152; (383)2278153,http://www.elsib.ru/,2025-01-29T14:51:43,"Научно-производственное объединение ""ЭЛСИБ"" пу...",ELSIB,"НПО ""ЭЛСИБ"" ПАО",ELSIB,ПАО,ГР 1110,1994-05-11T00:00:00,Новосибирская городская регистрационная палата...,2002-09-12T00:00:00,Инспекция Министерства РФ по налогам и сборам ...,RUS,None,None,(383) 298-92-94,elsib@elsib.ru,0,0,None,643.0,643.0,РОССИЯ,Russia,54,50,Новосибирская область,"Научно-производственное объединение ""ЭЛСИБ"", ПАО",80607.0,10917-F,112000000.0,RUB,27.11.1,7,50701000001,50401374000,"630088,Новосибирская обл., г. Новосибирск, ул....",12247,4210008,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,ELIB,None,540301001,ГР 1110,2.0,Корпоративный,corporate,None,None,None,None,None,None,0,0,None,0.0,3510,None,S112,1025401300748,None,None,None,1992-12-25T00:00:00,None,None,ДопИНН,16,Частная собственность,0,43853,1217
2,24131,98136,Элпа НИИ,Elpa,7735064772,07628061,1027739098760,ELPA,Технологии,"124460, г. Москва, г. Зеленоград, проспект Пан...",(903)7114552; (495)5301302; (499)5351310,www.elpapiezo.ru,2025-01-29T14:51:44,"Акционерное общество ""Научно-исследовательский...","""Elpa"" Research institute and pilot line"" (joi...","АО ""НИИ ""Элпа""","""Elpa"" Research institute"" (jsc)",АО,None,None,None,2002-08-21T00:00:00,Межрайонная инспекция МНС России № 39 по г. Мо...,RUS,None,None,(499) 710-13-02,elpalaw@elpapiezo.ru,0,0,None,643.0,643.0,РОССИЯ,Russia,77,45,г.Москва,"""Научно-исследовательский институт ""Элпа"" с оп...",84848.0,02540-A,20543500.0,RUB,72.19,7,45331000000,45272562000,"124460, г. Москва, г. Зеленоград, проспект Пан...",12267,4210008,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,ELPA,None,773501001,None,2.0,Корпоративный,corporate,None,None,None,None,None,None,0,0,None,0.0,8730,None,S112,1027739098760,None,None,None,1993-06-10T00:00:00,None,None,ДопИНН,16,Частная собственность,0,43853,12257
3,24132,97866,Электропривод,Elektroprivod,7708012528,00216390,1027700022228,ELPD,Машиностроение,"107078, г. Москва, ул. Садовая-Спасская, д. 1 ...",(495)6082160; (495)6082181; (495)6082514,None,2025-07-02T13:25:22.980783,None,None,None,None,ПАО,None,None,None,None,None,RUS,None,None,None,gevorkyan@el-privod.ru,None,None,None,643.0,643.0,РОССИЯ,Russia,77,45,г.Москва,"""Электропривод"", ОАО",2825.0,04600-A,19728.0,RUB,None,7,45378000000,45286565000,"107078, г. Москва, ул. Садовая-Спасская, д. 1/...",12247,4210008,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,770801001,None,NaN,None,None,None,None,None,None,None,None,0,0,None,0.0,None,None,S112,1027700022228,None,None,None,1993-03-05T00:00:00,None,None,ДопИНН,16,Частная собственность,0,43853,11987
4,24133,92706,Электроприбор-ВоронежНПО,Elektropribor,3650000821,07515210,1023602241321,ELPV,Машиностроение,"394071,Воронежская обл., г. Воронеж, ул. 20-Ле...",(473)2578542; (473)2578501; (473)2578503,www.epribor.ru,2025-01-29T14:51:43,Акционерное общество Научно-производственное о...,Joint stock company Research and Production Co...,"АО НПО ""Электроприбор-Воронеж""","JSC ""Electropribor-Voronezh R&P Corp.""",АО,3664/112180,1996-11-21T00:00:00,Администрация г. Воронежа,2002-07-10T00:00:00,Инспекция Министерства РФ по налогам и сборам ...,RUS,None,None,None,amaideniukov@priborvrn.ru,0,0,None,643.0,643.0,РОССИЯ,Russia,36,20,Воронежская область,"Научно-производственное объединение ""Электропр...",83973.0,40057-A,20437740.0,RUB,26.51.1,7,20701000001,20401000000,"394071,Воронежская обл., г. Воронеж, ул. 20-Ле...",12267,4210008,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,ELPV,None,366401001,3664/112180,2.0,Корпоративный,corporate,None,None,None,None,None,None,0,0,None,0.0,3810,None,S112,1023602241321,2002-07-10T00:00:00,Инспекция МНС России по Ленинскому Району г. В...,"Прежнее наименование: ""Электроприбор"", АО",1993-06-23T00:00:00,None,None,ДопИНН,16,Частная собственность,0,43853,7417

In [9]:
CurrencyRateDF = CurrencyRate().df
CurrencyRateDF.head()

        rate  endOfDayRate error from   to
0  21.920700     22.049200  None  AED  RUB
1        NaN           NaN  None  AFN  RUB
2        NaN           NaN  None  ALL  RUB
3   0.210346      0.211618  None  AMD  RUB
4        NaN           NaN  None  ANG  RUB

### BONDS

#### Шаг 2. Предобработка таблиц

In [10]:
TransformedFintoolReferenceData = FintoolReferenceDataDF[FintoolReferenceDataDF['fintooltype']=='Облигация']\
.copy()[[
    'isincode', 'fintoolid', 'status', 'nickname', 'issuername', 'issuerinn', 'borrowername', 'borrowerinn',
    'fintooltype', 'facevalue', 'begdistdate', 'faceftname', 'nominaltype', 'coupontype', 'floatratename'
]]\
.drop_duplicates(subset=['isincode'])\
.rename(columns={
    'isincode': "isin",
    'fintoolid': "fintool",
    'status': "status",
    'nickname': "name",
    'issuername': "issuer",
    'issuerinn': "issuer_INN",
    'borrowername': "borrower",
    'borrowerinn': "borrower_INN",
    'fintooltype': "type",
    'facevalue': "face_value",
    'begdistdate': "issue_date",
    'faceftname': "currency",
    'nominaltype': "principal_type",
    'coupontype': "coupon_type",
    'floatratename': "rate"
})
TransformedFintoolReferenceData.set_index('isin', drop=True, inplace=True)
TransformedFintoolReferenceData['issue_date'] = pd.to_datetime(TransformedFintoolReferenceData['issue_date'], errors='coerce')

Для обновления индексируемого номинала

In [11]:
INDEX_TYPES = ['Инфляционно-Индексируемый', 'Индексируемый', 'Инфляц-Индекс+Амортизация', 
               'Индексация по активу', 'Индексац.(актив)+ Аморт.', 'Инфляционно-Индексируемый']
index_types_isins = TransformedFintoolReferenceData[TransformedFintoolReferenceData['principal_type'].isin(INDEX_TYPES)].index

In [12]:
TransformedAccruedInterestOnDate = AccruedInterestOnDateDF.copy().dropna(subset=["currentFaceValue"])
TransformedAccruedInterestOnDate = TransformedAccruedInterestOnDate\
.merge(FintoolReferenceDataDF[['fintoolid', "isincode"]], how='left', left_on='fintoolId', right_on='fintoolid')\
.drop(columns=['fintoolid'])\
.rename(columns={
    "isincode": "isin", 
    'currentFaceValue': 'face_value', 
    'faceValueCurrency': 'currency'
})
TransformedAccruedInterestOnDate = TransformedAccruedInterestOnDate[['isin', 'face_value', 'currency']].set_index('isin')

#Добавление загруженных данных в результирующий датафрейм
TransformedAccruedInterestOnDate = TransformedAccruedInterestOnDate[~TransformedAccruedInterestOnDate.index.duplicated()]
TransformedAccruedInterestOnDateIndexed = TransformedAccruedInterestOnDate[
    TransformedAccruedInterestOnDate.index.isin(index_types_isins)
]
TransformedFintoolReferenceData.update(TransformedAccruedInterestOnDateIndexed)

In [13]:
import json
TransformedFloaterData = FloaterDataDF.copy()
try:
    TransformedFloaterData = pd\
    .concat([TransformedFloaterData, pd.DataFrame([json.loads(base)[0] for base in FloaterDataDF.bases])], axis=1)\
    .drop(columns=['bases'])
except:
    pass
TransformedFloaterData = TransformedFloaterData\
.merge(FintoolReferenceDataDF[['fintoolid', "isincode"]], how='left', left_on='fintoolId', right_on='fintoolid')\
.drop(columns=['fintoolid'])\
.reset_index(drop=True)
TransformedFloaterData['beg_period'] = pd.to_datetime(TransformedFloaterData['beg_period'], errors='coerce')
TransformedFloaterData['end_period'] = pd.to_datetime(TransformedFloaterData['end_period'], errors='coerce')
TransformedFloaterData['premium_to_base'] /= 10000

In [14]:
TransformedCalendar = CalendarDF.copy()
TransformedCalendar.loc[TransformedCalendar['typeOperation'].isin(['O', 'N', 'P']), 'eventType'] = 'PUT'
TransformedCalendar['eventDate'] = pd.to_datetime(TransformedCalendar['eventDate'], errors='coerce')
# TransformedCalendar['rateDate'] = pd.to_datetime(TransformedCalendar['rateDate'])
TransformedCalendar = TransformedCalendar[~TransformedCalendar['eventDate'].isna()]
TransformedCalendar.loc[~TransformedCalendar['revisedPay1Bond'].isna(), 'pay1Bond'] = \
TransformedCalendar.loc[~TransformedCalendar['revisedPay1Bond'].isna(), 'revisedPay1Bond']
TransformedCalendar['Currency_temp'] = TransformedCalendar['faceFTName']
TransformedCalendar.loc[~TransformedCalendar['currencyFTName'].isna(), 'Currency_temp'] = \
TransformedCalendar.loc[~TransformedCalendar['currencyFTName'].isna(), 'currencyFTName']
TransformedCalendar.loc[(~TransformedCalendar['paymentCurrencyFTName'].isna())&(~TransformedCalendar['revisedPay1Bond'].isna()), 'Currency_temp'] = \
TransformedCalendar.loc[(~TransformedCalendar['paymentCurrencyFTName'].isna())&(~TransformedCalendar['revisedPay1Bond'].isna()), 'paymentCurrencyFTName']
TransformedCalendar = TransformedCalendar[TransformedCalendar['eventType'].isin(['CPN', 'MTY', 'PUT'])] # если нужны оферты колл, нужно аккуратно подойти к выбору typeOperation
TransformedCalendar['value'] /= 100

In [15]:
TransformedCalendar = TransformedCalendar.merge(CurrencyRateDF[["rate", "from", "to"]], how='left', left_on=['Currency_temp', 'faceFTName'], right_on=['from', 'to'])
TransformedCalendar['FX'] = TransformedCalendar['rate'].fillna(1)
TransformedCalendar['CF'] = TransformedCalendar['pay1Bond'] * TransformedCalendar['FX']
currencies = Acc.client.query_df("""
    SELECT DISTINCT num, currency
    FROM currencies""").set_index("currency")["num"]
TransformedCalendar['Currency'] = TransformedCalendar['faceFTName'].map(currencies).fillna(0).astype(np.int32)

In [16]:
TransformedCalendar = TransformedCalendar[[
    'isiNcode', 'finToolID', 'nickname', 'rateDate', 'eventDate', 'eventType', 
    'typeOperation', 'value', 'CF', 'faceFTName', 'note', 'eventTotalVol'
]].rename(columns={
    'isiNcode': "isin",
    'finToolID': "fintool",
    'nickname': "name",
    'rateDate': "rate_date", 
    'eventDate': "payment_date", 
    'eventType': "payment_type", 
    'typeOperation': 'operation_type',
    'value': "rate", 
    'CF': "payment_sum", 
    'faceFTName': "currency", 
    'note': "note",
    'eventTotalVol': 'event_total_vol'
})
TransformedCalendar.dropna(subset="isin", inplace=True)

#### Шаг 3. Корректировка потока

In [17]:
bonds = (
    TransformedCalendar
    .merge(
        TransformedFintoolReferenceData[["face_value", "principal_type", "coupon_type", "issue_date"]], 
        how='left', 
        left_on="isin", 
        right_index=True)
    .rename(columns={
        "face_value": "nominal"
    })
)
bonds["nominal"] = bonds["nominal"].fillna(0)
bonds["rate"] = bonds["rate"].fillna(0)
bonds["payment_sum"] = bonds["payment_sum"].fillna(0)
bonds['event_total_vol'] = bonds['event_total_vol'].fillna(0)
bonds["name"] = bonds["name"].str.replace('[\n\t\r;,]', '.', regex=True)
bonds["note"] = bonds["note"].str.replace('[\n\t\r;,]', '.', regex=True)
bonds["payment_type_NUM"] = bonds["payment_type"].map({"CPN": 1, "MTY": 2, "PUT": 3})
bonds.sort_values(['isin', 'payment_date', 'payment_type_NUM'], inplace=True)

Обнуляем ставки по плавающим купонам, оцененных после отчетной даты

In [18]:
bonds.loc[(bonds['rate_date']>REPORT_DATE_STR) & (bonds['payment_type']=='CPN') & (bonds['operation_type']=='Плавающий'), ['rate', 'payment_sum']] = np.nan

Заполняем пропущенные ставки купона последним известным

In [19]:
bonds.loc[bonds['payment_type']=='CPN', 'rate'] = np.where(
    bonds.loc[bonds['payment_type']=='CPN', 'rate']<1e-6, 
    np.nan, 
    bonds.loc[bonds['payment_type']=='CPN', 'rate']
)
bonds.loc[bonds['payment_type']=='CPN', 'rate'] = (
    bonds.loc[bonds['payment_type']=='CPN', ['isin', 'rate']]
    .groupby('isin')['rate']
    .ffill()
)

Запоминаем ставку предыдущего купона

In [20]:
bonds['prev_cpn'] = (
    bonds
    .groupby("isin")["rate"]
    .shift(1)
).combine_first(bonds['rate'])

Заполняем разницу между датами выплат

In [21]:
bonds['prev_date'] = (
    bonds
    .groupby('isin')['payment_date']
    .shift(1)
)
bonds['days_diff'] = (bonds['payment_date'] - bonds['prev_date']).dt.days

Заполняем погашенный и непогашенный номинал

In [22]:
bonds["MTY"] = np.where(bonds.payment_type=="MTY", bonds['rate'], 0)
bonds["paid_nominal"] = (
    bonds
    .groupby(["isin"])["MTY"]
    .cumsum()
)
bonds["remain_nominal_no_shift"] = bonds["nominal"]*(1 - bonds["paid_nominal"])
bonds["remain_nominal"] = (
    bonds
    .groupby("isin")["remain_nominal_no_shift"]
    .shift(1)
    .fillna(bonds['nominal'])
)

если у нас perpetual, то есть нет даты погашения, добавляем в конец прогнозных потоков погашение

In [23]:
last_type = (
    bonds
    .groupby('isin')
    .last()
    .reset_index()
)
last_noMTY_isins = last_type[last_type['payment_type']=='CPN']['isin']
last_noMTY = last_type[last_type['isin'].isin(last_noMTY_isins)]
last_noMTY['payment_type'] = 'MTY'
last_noMTY['payment_type_NUM'] = 2
last_noMTY['payment_sum'] = (
    last_noMTY["isin"].map(
        bonds
        .groupby('isin')
        .last()["remain_nominal"]
        .to_dict()
    )
)
bonds = pd.concat(
    [bonds, last_noMTY], axis=0)\
.sort_values(['isin', 'payment_date', 'payment_type_NUM'])\
.reset_index(drop=True)

/var/folders/g4/mpm4njl93p547kbhxbvqlm480000gn/T/ipykernel_6415/3382992906.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_noMTY['payment_type'] = 'MTY'
/var/folders/g4/mpm4njl93p547kbhxbvqlm480000gn/T/ipykernel_6415/3382992906.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_noMTY['payment_type_NUM'] = 2
/var/folders/g4/mpm4njl93p547kbhxbvqlm480000gn/T/ipykernel_6415/3382992906.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_noMTY['payment_sum'] = (

Корректируем поток для облигаций с индексируемым номиналом

In [24]:
indexed_bonds_isins = bonds[bonds['principal_type']=='Инфляционно-Индексируемый']['isin']
indexed_bonds = bonds[bonds['isin'].isin(indexed_bonds_isins)]
not_indexed_bonds = bonds[~bonds['isin'].isin(indexed_bonds_isins)]
cpn_pay_mask = indexed_bonds['payment_type']=='CPN'
mty_pay_mask = indexed_bonds['payment_type']=='MTY'
indexed_bonds.loc[cpn_pay_mask,'payment_sum'] = indexed_bonds.loc[cpn_pay_mask,'rate']*indexed_bonds.loc[cpn_pay_mask,'nominal']*indexed_bonds.loc[cpn_pay_mask,'days_diff']/365
indexed_bonds.loc[mty_pay_mask,'payment_sum'] = indexed_bonds.loc[mty_pay_mask,'remain_nominal']
bonds = pd.concat([indexed_bonds, not_indexed_bonds], axis=0).sort_values(['isin', 'payment_date', 'payment_type_NUM']).reset_index(drop=True)

оставляем только будущие потоки

In [25]:
bonds = bonds[bonds['payment_date']>REPORT_DATE_STR]

обновляем погащение для индексируемого номинала

In [26]:
bonds.loc[bonds['isin'].isin(index_types_isins), "remain_nominal_no_shift"] = \
bonds.loc[bonds['isin'].isin(index_types_isins), "nominal"]*(1 - bonds.loc[bonds['isin'].isin(index_types_isins), "paid_nominal"])
bonds.loc[bonds['isin'].isin(index_types_isins), "remain_nominal"] = (
    bonds.loc[bonds['isin'].isin(index_types_isins), ['isin', "remain_nominal_no_shift"]]
    .groupby("isin")
    .shift(1)
    .fillna(bonds.loc[bonds['isin'].isin(index_types_isins), 'nominal'])
)
# индексируемый номинал уже обновлен
bonds.loc[bonds['isin'].isin(index_types_isins), "remain_nominal"] = \
bonds.loc[bonds['isin'].isin(index_types_isins), "nominal"]

обрезаем потоки по первую дату оферты

In [27]:
bonds['put'] = (
    bonds['payment_type']
    .eq('PUT')
    .groupby(bonds['isin'])
    .cumsum()
    .groupby(bonds['isin'])
    .shift(1)
    .fillna(0)
)
bonds = bonds[bonds['put']==0]

Удаляем погашенные потоки

In [28]:
bonds = bonds[bonds['remain_nominal']>1e-6]

Деление на флоатеры и обычные облигации

In [29]:
Bonds = bonds[~bonds['fintool'].isin(FloaterDataDF["fintoolId"])]
floaters = bonds[bonds['fintool'].isin(FloaterDataDF["fintoolId"])]

Флоатеры

Джойн лучше сделать в sql

In [30]:
import sqlite3

conn = sqlite3.connect(":memory:") 
TransformedFloaterData.to_sql("TransformedFloaterData", conn, index=False)
floaters.to_sql("floaters", conn, index=False)
Floaters = pd.read_sql_query("""
    SELECT 
        b.*
        , fl.beg_period
        , fl.end_period
        , fl.premium_to_base
        , fl.start_point
    FROM floaters b
    LEFT OUTER JOIN TransformedFloaterData fl ON b.fintool = fl.fintoolId AND b.payment_date >= fl.beg_period AND b.payment_date < fl.end_period
    """
    , conn
)
Floaters['payment_date'] = pd.to_datetime(Floaters['payment_date'])
Floaters.loc[Floaters['rate_date'].isna(), 'rate_date'] = date(1970, 1, 1)
Floaters['rate_date'] = pd.to_datetime(Floaters['rate_date'], errors='coerce')

/var/folders/g4/mpm4njl93p547kbhxbvqlm480000gn/T/ipykernel_6415/2971738460.py:20: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Floaters['rate_date'] = pd.to_datetime(Floaters['rate_date'], errors='coerce')

Запоминаем фиксированный купон

In [31]:
floaters_fix = Floaters[(Floaters['payment_type']=='CPN') & (Floaters['operation_type']!='Плавающий')]
floaters_fixed_dict = floaters_fix.groupby('isin').first().to_dict()['rate']
floaters_fix['rate'] = floaters_fix['isin'].map(floaters_fixed_dict)
floaters_float = Floaters[(Floaters['payment_type']=='CPN') & (Floaters['operation_type']=='Плавающий')].reset_index()

/var/folders/g4/mpm4njl93p547kbhxbvqlm480000gn/T/ipykernel_6415/559201119.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  floaters_fix['rate'] = floaters_fix['isin'].map(floaters_fixed_dict)

Плавающие купоны

Если БЛИЖАЙШИЙ после расчетной даты будущий купон не пустой и дата rateDate больше расчетной даты, то делаем его пустым (с последующим заполнением предыдущим купоном)

In [32]:
floaters_float = Floaters[(Floaters['payment_type']=='CPN') & (Floaters['operation_type']=='Плавающий')]

In [33]:
floaters_float.loc[
            floaters_float['rate'].isna(), 'rate'
] = (
    floaters_float.loc[
            floaters_float['rate'].isna(), ['premium_to_base', 'prev_cpn']
    ].max(axis=1)
)

In [34]:
cpn_pay_nan_mask = (floaters_float['payment_sum']<1e-6) | (floaters_float['payment_sum'].isna())
floaters_float['days_diff'] = floaters_float['days_diff'].fillna(floaters_float.groupby('isin')['days_diff'].transform('mean'))
floaters_float.loc[cpn_pay_nan_mask, 'payment_sum'] = (
    floaters_float.loc[cpn_pay_nan_mask, 'rate']*
    floaters_float.loc[cpn_pay_nan_mask, 'remain_nominal']*
    floaters_float.loc[cpn_pay_nan_mask, 'days_diff']/365
)

/var/folders/g4/mpm4njl93p547kbhxbvqlm480000gn/T/ipykernel_6415/2330993031.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  floaters_float['days_diff'] = floaters_float['days_diff'].fillna(floaters_float.groupby('isin')['days_diff'].transform('mean'))

По той же формуле, где фиксированные купоны неизвестны

In [35]:
floaters_fix.loc[floaters_fix['payment_sum']<1e-6, 'payment_sum'] = (
    floaters_fix.loc[floaters_fix['payment_sum']<1e-6, 'rate']*
    floaters_fix.loc[floaters_fix['payment_sum']<1e-6, 'remain_nominal']*
    floaters_fix.loc[floaters_fix['payment_sum']<1e-6, 'days_diff']/365
)

Погашения

In [36]:
mty_floaters = Floaters[(Floaters['payment_type']!='CPN')]

Конкатенируем купоны и погашения

In [37]:
Floaters = (
    pd.concat(
        [floaters_fix, floaters_float, mty_floaters], axis=0
    ).sort_values(
        ['isin', 'payment_date', 'payment_type_NUM']
    )
)

#### Шаг 4. Объединение облигаций с постоянным и плавающим купоном в один датафрейм

In [38]:
Bonds["is_floater"] = False
Floaters["is_floater"] = True

/var/folders/g4/mpm4njl93p547kbhxbvqlm480000gn/T/ipykernel_6415/4080972275.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Bonds["is_floater"] = False

In [39]:
bonds = (
    pd.concat([Bonds, Floaters], axis=0)
    .sort_values(['isin', 'payment_date', 'payment_type_NUM'])
    .reset_index(drop=True)
)

In [40]:
bonds['id_payment'] = bonds.groupby(['isin']).cumcount() + 1
bonds["report_date"] = pd.to_datetime(REPORT_DATE)
bonds["payment_date"] = pd.to_datetime(bonds["payment_date"])

Мэппинг имен и кодов валют

In [41]:
bonds["currency"] = (
    bonds["currency"]
    .map(currencies)
    .fillna(0)
    .astype(np.int32)
)

Добавление времени выгрузки и выбор колонок

In [42]:
bonds = bonds[
    ["isin", "fintool", "name", "payment_date", "payment_type", "rate", "payment_sum", "currency", "report_date"]
]

In [43]:
bonds["export_timestamp"] = dt.now().strftime("%Y%m%d%H%M%S")
bonds = bonds.replace('None', '')
bonds.to_csv(f'./data/output/cash_flows.csv', index=False, sep='\t', header=True)

### SHARES

#### Шаг 5. Предобработка таблиц

In [44]:
shares = FintoolReferenceDataDF[FintoolReferenceDataDF['fintooltype'].isin(['Акция','Выпуск акции'])].copy()
shares = shares[~shares['isincode'].isna()]

In [45]:
not_dup = shares[~shares.duplicated(subset=['isincode'], keep=False)]
dup = shares[shares.duplicated(subset=['isincode'], keep=False)]
dup = dup[dup['securitykind']=='Осн-ой']
dup['count_not_null'] = dup[['summarketvol','issuerinn','issuercountry','tradesite']].count(axis=1)
dup = dup.sort_values(['isincode', 'count_not_null']).groupby('isincode').last().reset_index()
shares = pd.concat([not_dup, dup], axis=0)

In [46]:
shares = shares.merge(EmitentsDF[['fininstid','country_oksm']], how='left', left_on='issueruid', right_on='fininstid')

In [47]:
exch = ExchangeTreeDF[['id','fullname_rus']].set_index('id')
shares.loc[~(shares['tradesite'].isin(exch.index) | shares['tradesite'].isna()), 'tradesite'] = np.nan
shares.loc[shares['tradesite'].isna()==False, 'tradesite'] = \
shares.loc[shares['tradesite'].isna()==False, 'tradesite'].apply(lambda x: exch.loc[int(x)].values[0])
shares[['is_stock_netorg']] = 1
shares.loc[
    (shares['tradesite'].isna()==False) |
    (shares['listing_level'].isna()==False) |
    (shares['listing_level_spb'].isna()==False), 'is_stock_netorg'] = 0

/var/folders/g4/mpm4njl93p547kbhxbvqlm480000gn/T/ipykernel_6415/834400275.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['ПАО "СПБ" - иностр.' 'FSE Франкфурт' 'HongKong SE' ... 'FSE Франкфурт'
 'FSE Франкфурт' 'FSE Франкфурт']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  shares.loc[shares['tradesite'].isna()==False, 'tradesite'] = \

In [48]:
cal = CalendarDF[CalendarDF['eventType']=='CONV'].copy()
shares_ = pd.DataFrame().reindex(columns=shares.columns)
df_ = cal.loc[cal['literid_typeoperation'].isin([1074,1075]), ['finToolID','coefficient']].groupby('finToolID').prod(numeric_only=False)
cal = cal[['finToolID']].drop_duplicates().merge(df_, on='finToolID', how='left')
df = shares.merge(cal, how='left', left_on='fintoolid', right_on='finToolID')
df['report_date'] = REPORT_DATE
#если событий по бумаге не было, коэффициент конвертации 1
df.loc[~df['fintoolid'].isin(cal['finToolID'].values), 'coefficient'] = 1
#рассчитываем долю одной акции в капитале
df.loc[df['summarketvol'].isna(), 'summarketvol'] = df.loc[df['summarketvol'].isna(), 'sumissuevol']
df['summarketval'] = df['summarketvol']*df['facevalue']
df['capital_value'] = df.groupby('fininstid')['summarketval'].transform('sum')
df.loc[df['capital_value']==0, 'capital_value'] = np.nan
df['1_share_in_cap'] = (df['facevalue']/df['coefficient'])/df['capital_value']
#если по разным выпускам эмитента разная валюта, наш расчет неверный, обнуляем
df1 = df.groupby('fininstid')['faceftname'].nunique()
df1 = df1.loc[df1>1]
df.loc[df['fininstid'].isin(df1.index), ['summarketval','capital_value','1_share_in_cap']] = np.nan
shares = pd.concat([shares_, df], axis=0)
shares = shares[~(shares['tradesite'].isna() & shares['country_oksm'].isna() & shares['1_share_in_cap'].isna())]
shares = shares[[
    'fintoolid', 'isincode', 'faceftname', 'facevalue', 'summarketvol', 'issuername',
    'issueruid', 'issuerinn', 'issuercountry', 'securitytype', 'listing_level', 'listing_level_spb',	
    'tradesite', 'country_oksm', 'is_stock_netorg', 'coefficient', 'report_date', 'summarketval', 
    'capital_value', '1_share_in_cap']].reset_index(drop=True)

/var/folders/g4/mpm4njl93p547kbhxbvqlm480000gn/T/ipykernel_6415/1811845522.py:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  shares = pd.concat([shares_, df], axis=0)

In [49]:
shares["export_timestamp"] = dt.now().strftime("%Y%m%d%H%M%S")
shares["report_date"] = pd.to_datetime(last_day_month)
shares['fintoolid'] = shares['fintoolid'].fillna(0).astype(int)
shares['issueruid'] = shares['issueruid'].fillna(0).astype(int)
shares['listing_level'] = shares['listing_level'].fillna(0).astype(int)
shares['listing_level_spb'] = shares['listing_level_spb'].fillna(0).astype(int)
shares['country_oksm'] = shares['country_oksm'].fillna(0).astype(int)
shares['is_stock_netorg'] = shares['is_stock_netorg'].fillna(0).astype(int)
shares = shares.replace('None', '')

In [59]:
shares.to_csv(f'./data/output/stocks_data.csv', index=False, sep='\t', header=True)

In [60]:
from src.utils.send_email import main
main("cash_flows.csv", "stocks_data.csv")