File: prices.ipynb\
Author: alexkobz\
Date: 08-10-2024\
Task: DSRFU-298

#### Шаг 0. Импорт и получение токена

In [1]:
import requests
import pandas as pd
import numpy as np
import nest_asyncio; nest_asyncio.apply()
from datetime import datetime as dt
from math import ceil
from src.utils.get_date import last_day_month, last_day_month_str, last_work_date_month, last_work_date_month_str

# последний день месяца
REPORT_DATE = last_day_month
REPORT_DATE_STR = last_day_month_str
# увеличиваем количество столбцов и строк для просмотра
pd.set_option('display.max_rows', 200, 'display.max_columns', 200)
REPORT_DATE

Unexpected Http Driver Exception

Error HTTPConnectionPool(host='host.docker.internal', port=8124): Max retries exceeded with url: /? (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x1685679a0>: Failed to resolve 'host.docker.internal' ([Errno 8] nodename nor servname provided, or not known)")) executing HTTP request attempt 1 (http://host.docker.internal:8124)

datetime.date(2025, 10, 31)

In [2]:
from src.sources.rudata.RuDataMethod import Account, FintoolReferenceData, EndOfDay, AccruedInterestOnDate, FloaterData, FloatersOnPeriod, RUPriceHistory, ExchangeTree, MoexSecurities, CurrencyRate, HistoryStockBonds, HistoryStockShares, HistoryStockNdm, HistoryStockCcp
Acc = Account()

#### Шаг 1. RuData

##### Шаг 1.0. RuData stage

In [3]:
FintoolReferenceDataDF = FintoolReferenceData().df
FintoolReferenceDataDF.head()

,facevalue_m,faceftname_m,sumissuevol_m,summarketvol_m,numcoupons_m,nrdcode,regcode_m,regdate_m,regdistdate_m,begdistdate_m,enddistdate_m,endmtydate_m,daysall_m,fullname_nrd,rpregorg_nrd,rpstate_nrd,issuenumber,currentfacevalue_nrd,isqualified_nrd,bondseries,islombardcbr_nrd,numcoupons_nrd,facevalue_nrd,faceftname_nrd,summarketvol_nrd,regcode_nrd,regdate_nrd,regorg_nrd,begdistdate_nrd,daysall_nrd,enddistdate_nrd,endmtydate_nrd,regdistdate_nrd,sumissuevol_nrd,drqty,isincodebase_nrd,nrdcompcode,shqty,summarketvolorig_nrd,issuername_nrd,planmtydate_nrd,firstcoupondate_nrd,depositary_nrd,registrar_nrd,placeprice_nrd,micexlist_nrd,minlot_nrd,formarketbonds_nrd,registraracctype_nrd,registraracctypedate_nrd,facialacc_nrd,acc_open_date_nrd,fraction_nrd,specialized_depo_nrd,cmp_code_nsd_issuer_nrd,cmp_code_nsd_managing_nrd,ratetypenamerus_nrd,ratetypenameeng_nrd,coupontypename_nrd,base_month,base_year,basis_nrd,sectypenamerus_nrd,sectypenameeng_nrd,secformnamerus_nrd,secformnameeng_nrd,sectypenamebr_nrd,secstaterus_nrd,secstateeng_nrd,placementtype_nrd,share_category_name_nrd,share_category_name_en_nrd,dr_category_name_nrd,dr_category_name_en_nrd,company_state_name_nrd,rate_type_id,cp_type_id,coupon_period_base_id,sec_type_id,sec_form_id,sec_state_id,placement_type_id,share_category_id,dr_category_mn,company_state_mn,sector4212u,sna2008,fullname_en_nrd,seniorityname,fintoolid,moex_code,moex_name,fullname,isin144a,isincode,nickname,progfintoolid,regcode,regdate,regorg,amortisedmty,basis,bondstructuralpar,cfi,coupontype,fintooltype,guaranteeamount,guaranteetype,haveoffer,isconvertible,isguaranteed,maturitygroup,securitization,accruedintcalctype,country,couponperyear,faceftname,facevalue,guarantval,havedefault,numcoupons,status,sumissueval,sumissuevol,summarketval,summarketvol,borrowername,borrowerokpo,borrowersector,borroweruid,borrowerinn,borrowercountry,borrowerregionname,issuername,issuerokpo,issuersector,issueruid,issuerinn,issuercountry,issuerregionname,assetssector,numguarantors,begdistdate,begmtydate,daysall,enddistdate,endmtydate,privatedist,regdistdate,securitytype,securitykind,nominaltype,update_time,isregion,nsd_service,raterevisionsperyear,floatratename,issubordinated,note,listing_level,havecovenant,haverepayment,haveindexedfv,numdecimals,couponperiod,ismatched,firstcoupondate,couponrate,iscomplicated,available_for_unqualified,sec_type_br_code,original_country,qualified_test_id,qualified_test_id_tm,base_asset_fintoolid,isqualified,listing_level_spb,have_mm_moex,have_mm_spb,beg_book_date,seniority,tradesite,current_coupontype,profit_type,counter,rn
0,2.0,2.0,2.0,2.0,2.0,None,0.0,0.0,2.0,2.0,2.0,2.0,2.0,None,None,None,None,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None,None,None,NaN,None,None,None,NaN,NaN,None,None,NaN,NaN,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,520,S2,None,Старшие необеспеченные,226059,None,None,"Соединённые Штаты Америки, 5-летние ноты с пог...",None,US91282CGH88,США-2-280131-об,NaN,None,None,None,0.0,act/act,None,None,Постоянный,Облигация,None,Необеспеченные,0.0,0.0,0.0,Среднесрочные,None,1.0,US,2.0,USD,100.00,NaN,0.0,10.0,В обращении,4.400000e+10,4.400000e+08,4.300001e+10,4.300001e+08,Правительство США,None,Государственные,95111.0,None,US,None,Минфин США,None,Государственные,95112.0,None,US,None,None,0.0,2023-01-31T00:00:00,None,1826.0,2023-01-31T00:00:00,2028-01-31T00:00:00,0.0,2023-01-31T00:00:00,Гос,Классические,Постоянный,2025-08-15T10:20:36,NaN,Нет информации,2.0,None,NaN,None,NaN,False,False,False,2.0,184.0,True,2023-01-31T00:00:00,3.5,False,0,OTHER,US,1000,1000,NaN,False,NaN,0,0,None,416.0,NaN,Фиксированный,Постоянный,107094,90113
1,2.0,2.0,2.0,2.0,2.0,None,0.0,0.0,2.0,2.0,2.0,2.0,2.0,None,None,None,None,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None,None,None,NaN,None,None,None,NaN,NaN,None,None,NaN,NaN,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,520,S2,None,Старшие необеспеченные,226060,None,None,"Соединённые Штаты Америки, 7-летние ноты с пог...",None,US91282CGJ45,США-300131-об,NaN,None,None,None,0.0,act/act,None,None,Постоянный,Облигация,None,Необеспеченные,0.0,0.0,0.0,Среднесрочные,None,1.0,US,2.0,USD,100.00,NaN,0.0,14.0,В обращении,3.600000e+10,3.600000e+08,3.500001e+10,3.500001e+08,Правительство США,None,Государственные,95111.0,None,US,None,Минфин США,None,Государственные,95112.0,None,US,None,None,0.0,2023-01-31T00:00:00,None,2557.0,2023-01-31T00:00:00,2030-01-31T00:00:00,0.0,2023-01-31T00:00:00,Гос,Классические,Постоянный,2025-08-15T10:20:36,NaN,Нет информации,2.0,None,NaN,None,NaN,False,False,False,2.0,184.0,True,2023-01-31T00:00:00,3.5,False,0,OTHER,US,1000,1000,NaN,False,NaN,0,0,None,416.0,NaN,Фиксированный,Постоянный,107094,90114
2,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None,None,None,NaN,None,None,None,NaN,NaN,None,None,NaN,NaN,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,520,S2,None,Старшие необеспеченные,226061,None,None,"Германия, государственные облигации (Bubills) ...",None,DE000BU0E006,Германия-2-12-2023-об,NaN,None,None,None,0.0,act/360,None,None,Дисконтный,Облигация,None,Необеспеченные,0.0,0.0,0.0,Краткосрочные,None,1.0,DE,NaN,EUR,0.01,NaN,0.0,NaN,Погашен,1.300000e+10,1.300000e+12,1.300000e+10,1.300000e+12,Правительство Германии,None,Государственные,95093.0,None,DE,None,German Finance Agency,None,Государственные,95309.0,DE137223325,DE,None,None,0.0,2023-01-30T00:00:00,None,317.0,2023-01-30T00:00:00,2023-12-13T00:00:00,0.0,2023-01-30T00:00:00,Гос,Классические,Постоянный,2024-11-22T13:50:27,NaN,Нет информации,NaN,None,NaN,None,NaN,False,False,False,6.0,NaN,True,None,0.0,False,0,BON5,DE,1000,1000,NaN,False,NaN,0,0,None,416.0,NaN,None,Дисконтный,107094,90115
3,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None,None,None,NaN,None,None,None,NaN,NaN,None,None,NaN,NaN,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,S112,None,None,226062,None,None,"""Головной институт по проектированию предприят...",None,None,ГипроВТИ-1-ао,NaN,1-01-55176-D,2004-01-30T00:00:00,ФКЦБ,NaN,None,None,None,None,Акция,None,None,NaN,0.0,NaN,None,None,NaN,RU,NaN,RUB,10.00,NaN,NaN,NaN,В обращении,2.469297e+07,2.469297e+06,2.469297e+07,2.469297e+06,None,None,None,NaN,None,None,None,ГипроВТИ,27822049,Строительство,124634.0,1657028318,RU,Республика Татарстан,None,NaN,None,None,NaN,None,None,0.0,None,Обыкн-ая,Осн-ой,None,2023-01-21T00:25:00,NaN,Нет информации,NaN,None,NaN,None,NaN,None,None,None,NaN,NaN,None,None,NaN,None,0,SHS3,RU,1000,1000,NaN,None,NaN,0,0,None,NaN,NaN,None,None,107094,90116
4,2.0,2.0,NaN,NaN,NaN,None,2.0,2.0,2.0,0.0,0.0,NaN,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None,None,None,NaN,None,None,None,NaN,NaN,None,None,NaN,NaN,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,S112,None,None,226063,None,None,"""Рабочий"", ЗАО, акции обыкновенные бездокумент...",None,None,Рабочий-2-ао,NaN,1-02-55112-P,2005-04-19T00:00:00,ФСФР,NaN,None,None,None,None,Акция,None,None,NaN,0.0,NaN,None,None,NaN,RU,NaN,RUB,10.00,NaN,NaN,NaN,Погашен,2.456072e+07,2.456072e+06,NaN,NaN,None,None,None,NaN,None,None,None,Рабочий,00336548,Пищевая промышленность и с/х,124635.0,6167008311,RU,Ростовская область,None,NaN,None,None,NaN,None,2025-09-25T00:00:00,0.0,2005-07-15T00:00:00,Обыкн-ая,Осн-ой,None,2025-09-26T10:50:33,NaN,Нет информации,NaN,None,NaN,None,NaN,None,None,None,NaN,NaN,None,None,NaN,None,0,SHS3,RU,1000,1000,NaN,None,NaN,0,0,None,NaN,NaN,None,None,107094,90117

In [4]:
EndOfDayDF = EndOfDay().df
EndOfDayDF.head()

,ask,avge_prce,bid,boardid,boardname,close,convexity,deal_acc,duration,exch,high,isin,last,last_time,last_yield,low,mat_date,mprice,name,open,pvbp,seccode,secname,spread,val,val_usd,vol,vol_lots,yield_agg,yield_ask,yield_average_o12m,yield_average_o2w,yield_bid,yield_swa,currency,fintoolId,id_iss,id_trade_site,add_date,update_date
0,50.45,50.610000,50.39,TQBR,T+ Акции и ДР,51.20,NaN,20526.0,NaN,MICEX,51.42,RU0009062285,50.45,2025-10-31T23:49:51.0004,NaN,50.12,None,50.59,AFLT.MICEX,51.18,NaN,AFLT,"Аэрофлот - российские авиалинии ОАО, АО - ФБ...",0.06,7.454605e+08,9260378.98,14728870.0,1472887.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4200,35154,170,2025-10-31T23:55:01,2025-10-31T23:55:01
1,9.21,9.120000,9.09,TQBR,T+ Акции и ДР,9.11,NaN,16.0,NaN,MICEX,9.21,RU0009100176,9.09,2025-10-31T21:37:11,NaN,9.09,None,9.08,BISVP.MICEX,9.12,NaN,BISVP,"Башинформсвязь ОАО, АП - ФБ ММВБ",0.12,4.470700e+04,555.36,4900.0,49.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4215,775000,170,2025-10-31T23:55:06,2025-10-31T23:55:06
2,1454.00,1461.842271,1448.00,TQBR,T+ Акции и ДР,1464.00,NaN,84.0,NaN,MICEX,1474.00,RU0009288658,1448.00,2025-10-31T23:31:38,NaN,1448.00,None,1466.00,BRZL.MICEX,1460.00,NaN,BRZL,"Бурятзолото ОАО, АО - ФБ ММВБ",6.00,4.634040e+05,5756.57,317.0,317.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4217,852973,170,2025-10-31T23:55:08,2025-10-31T23:55:08
3,76.60,75.700000,74.80,TQBR,T+ Акции и ДР,75.80,NaN,20.0,NaN,MICEX,76.80,RU0009082291,76.80,2025-10-31T23:42:40,NaN,74.80,None,75.80,CHGZ.MICEX,76.80,NaN,CHGZ,"Черногорнефть ОАО, АО - ФБ ММВБ",1.80,4.162600e+04,517.09,550.0,55.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4223,853518,170,2025-10-31T23:55:08,2025-10-31T23:55:08
4,853.20,858.500000,852.20,TQBR,T+ Акции и ДР,878.00,NaN,35482.0,NaN,MICEX,880.80,RU0009046510,853.40,2025-10-31T23:49:48,NaN,847.00,None,859.40,CHMF.MICEX,878.00,NaN,CHMF,"Северсталь ОАО, АО - ФБ ММВБ T+2",1.00,1.341439e+09,16663839.91,1562608.0,1562608.0,NaN,NaN,NaN,NaN,NaN,NaN,RUB,4226,1069768,170,2025-10-31T23:55:06,2025-10-31T23:55:06

In [5]:
AccruedInterestOnDateDF = AccruedInterestOnDate().df
AccruedInterestOnDateDF.head()

,fintoolId,shiftDays,shiftTypeSource,typeCurrency,date,accruedInterest,accruedInterestPct,currentFaceValue,currentFaceValuePct,calculationType,error,faceValueCurrency,accruedInterestCurrency,faceValueLastKnownDate
0,4000,0,Calendar,None,2025-10-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,None,RUB,RUB,2025-10-31T00:00:00
1,4001,0,Calendar,None,2025-10-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,None,RUB,RUB,2025-10-31T00:00:00
2,4002,0,Calendar,None,2025-10-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,None,RUB,RUB,2025-10-31T00:00:00
3,4003,0,Calendar,None,2025-10-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,None,RUB,RUB,2025-10-31T00:00:00
4,4004,0,Calendar,None,2025-10-31T00:00:00,NaN,NaN,1000.0,100.0,Typical,None,RUB,RUB,2025-10-31T00:00:00

In [6]:
FloaterDataDF = FloaterData().df
FloaterDataDF.head()

,fintoolId,beg_period,end_period,start_point,model_type,date_pub_n,date_pub_type,date_fix_n,date_fix_type,bases
0,11193,2000-12-01T00:00:00,2050-12-01T00:00:00,E,single,NaN,None,10.0,W,"[{""base_no"": 1, ""calc_type"": ""FIX"", ""base_fint..."
1,30316,2025-09-18T00:00:00,2025-12-18T00:00:00,B,single,NaN,None,2.0,W,"[{""base_no"": 5, ""calc_type"": ""FIX"", ""base_fint..."
2,36325,2009-08-27T00:00:00,2028-09-15T00:00:00,B,single,NaN,None,1.0,W,"[{""base_no"": 1, ""calc_type"": ""FIX"", ""base_fint..."
3,57394,2011-11-21T00:00:00,2028-10-30T00:00:00,B,single,NaN,None,5.0,W,"[{""base_no"": 2, ""calc_type"": ""PER"", ""base_fint..."
4,59702,2013-12-11T00:00:00,2028-11-22T00:00:00,B,single,NaN,None,5.0,C,"[{""base_no"": 2, ""calc_type"": ""FIX"", ""base_fint..."

In [7]:
FloatersOnPeriodDF = FloatersOnPeriod().df
FloatersOnPeriodDF.head()

,fintoolId,date,accruedInterest,accruedInterestPct,currentFaceValue,currentFaceValuePct,faceValueCurrency,addDate,counter
0,164245,2025-10-31T00:00:00,16.92,1.69,1000.0,100.0,RUB,2025-10-30T06:00:41,1
1,164245,2025-10-31T00:00:00,16.92,1.69,1000.0,100.0,RUB,2025-10-30T06:00:41,318
2,164245,2025-10-31T00:00:00,16.92,1.69,1000.0,100.0,RUB,2025-10-30T06:00:41,318
3,164245,2025-10-31T00:00:00,16.92,1.69,1000.0,100.0,RUB,2025-10-30T06:00:41,318
4,164245,2025-10-31T00:00:00,16.92,1.69,1000.0,100.0,RUB,2025-10-30T06:00:41,318

In [8]:
RUPriceHistoryDF = RUPriceHistory().df
RUPriceHistoryDF.head()

,nickname,fintoolid,fininstid,isincode,regcode,nrdcode,calcdate,val_date,current_fv,faceftname,date_agg,avge_prce,yield_agg,z_wa_mb,durmod_agg,i_wa_mb,method_no,vp_pct,vp_pc,vp_pc_l,vp_pc_h,vp_m1,y_agg_m1,deal_250d,q_m1,r_m1,vp_m2,y_agg_m2,i_vp_m2,sigma_m2,index,beta1_m2,beta0_m2,alpha_m2,gamma_m2,sigma_nu,rho_m2,r_m2,vp_m3,y_agg_m3,dur_agg_m3,z_vp_m3,r_m3,factor1,beta1_m3,factor2,beta2_m3,level_pd,coef_b,risk_b,beta3_m3,is_ontherun,beta4_m3,hhi,beta5_m3,ind_liq,beta6_m3,ind_unliq,beta7_m3,sector,phi_sector,version,valuation_currency,security_type,source,wa_duration,duration_mod,lbound1,ubound1,lbound2,ubound2,lbound3,ubound3,acc_int,wap_ext_zspread,mp3_ext_zspread,id,no_history_found,not_valid_code,calcDateTime,counter,rn
0,Россия-2030-11т,6043,7080,XS0114288789,SK-0-CM-128,XS0114288789,2025-10-01T00:00:00,2025-10-01T00:00:00,0.045,USD,2030-03-31T00:00:00,0.0,0.0,0.0,None,0.0,1.0,106.814128,0.048066,104.113751,109.514505,106.814128,4.594218,0.0,0.0,0.0,106.814128,4.594218,0.0,0.0,None,0.0,0.0,0.0,0.0,0.0,0.0,0.0,106.814128,4.594218,0.0,-0.0113,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Государственные,0.0,2,USD,euro_bond,3,0.0,2.214682,104.113751,109.514505,104.113751,109.514505,104.113751,109.514505,0.000009,0.0,0.0,6043,None,None,None,48281,8422
1,Россия-2030-11т,6043,7080,XS0114288789,SK-0-CM-128,XS0114288789,2025-10-02T00:00:00,2025-10-02T00:00:00,0.045,USD,2030-03-31T00:00:00,0.0,0.0,0.0,None,0.0,1.0,106.388362,0.047875,103.782564,108.994159,106.388362,4.771831,0.0,0.0,0.0,106.388362,4.771831,0.0,0.0,None,0.0,0.0,0.0,0.0,0.0,0.0,0.0,106.388362,4.771831,0.0,-0.2158,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Государственные,0.0,2,USD,euro_bond,3,0.0,2.205657,103.782564,108.994159,103.782564,108.994159,103.782564,108.994159,0.000019,0.0,0.0,6043,None,None,None,48281,8423
2,Россия-2030-11т,6043,7080,XS0114288789,SK-0-CM-128,XS0114288789,2025-10-03T00:00:00,2025-10-03T00:00:00,0.045,USD,2030-03-31T00:00:00,0.0,0.0,0.0,None,0.0,1.0,105.880154,0.047646,103.021527,108.738781,105.880154,4.986466,0.0,0.0,0.0,105.880154,4.986466,0.0,0.0,None,0.0,0.0,0.0,0.0,0.0,0.0,0.0,105.880154,4.986466,0.0,-0.2304,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Государственные,0.0,2,USD,euro_bond,3,0.0,2.195343,103.021527,108.738781,103.021527,108.738781,103.021527,108.738781,0.000028,0.0,0.0,6043,None,None,None,48281,8424
3,Россия-2030-11т,6043,7080,XS0114288789,SK-0-CM-128,XS0114288789,2025-10-06T00:00:00,2025-10-06T00:00:00,0.045,USD,2030-03-31T00:00:00,0.0,0.0,0.0,None,0.0,1.0,104.096731,0.046844,101.103983,107.089478,104.096731,5.758640,0.0,0.0,0.0,104.096731,5.758640,0.0,0.0,None,0.0,0.0,0.0,0.0,0.0,0.0,0.0,104.096731,5.758640,0.0,-0.2806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Государственные,0.0,2,USD,euro_bond,3,0.0,2.160196,101.103983,107.089478,101.103983,107.089478,101.103983,107.089478,0.000056,0.0,0.0,6043,None,None,None,48281,8425
4,Россия-2030-11т,6043,7080,XS0114288789,SK-0-CM-128,XS0114288789,2025-10-07T00:00:00,2025-10-07T00:00:00,0.045,USD,2030-03-31T00:00:00,0.0,0.0,0.0,None,0.0,1.0,104.878530,0.047195,100.695740,109.061319,104.878530,5.411286,0.0,0.0,0.0,104.878530,5.411286,0.0,0.0,None,0.0,0.0,0.0,0.0,0.0,0.0,0.0,104.878530,5.411286,0.0,-0.2592,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Государственные,0.0,2,USD,euro_bond,3,0.0,2.169823,100.695740,109.061319,100.695740,109.061319,100.695740,109.061319,0.000066,0.0,0.0,6043,None,None,None,48281,8426

In [9]:
ExchangeTreeDF = ExchangeTree().df
ExchangeTreeDF.head()

,id,id_parent,shortname_rus,shortname_eng,fullname_rus,fullname_eng,sort_order,update_date,counter,rn
0,1,0,РТС,RTS,Московская Биржа - РТС,RTS,12,2020-12-28T17:03:09,242,17
1,2,1,РТС,RTS,РТС индексы,RTS indexes,2,2020-12-28T17:03:09,242,4
2,8,1,ФОРТС,FORTS,FORTS,FORTS,8,2020-12-28T17:03:09,242,11
3,9,0,"ПАО ""СПБ""",PJSC «SPB»,"ПАО ""СПБ""",PJSC «SPB»,20,2020-12-28T17:03:09,242,21
4,11,0,МБ,MX,Московская Биржа,Moscow Exchange,11,2020-12-28T17:03:09,242,16

In [10]:
MoexSecuritiesDF = MoexSecurities().df
MoexSecuritiesDF.head()

,id_iss,secid,boardid,board_title,board_group,board_group_title,market,engine,short_name,isin,cfi_ifx,cfi_name,lot_size,expiration_date,currency,emitent_code,emitent_name,market_sector,min_price_increment,fintoolid,reg_code,update_date,counter,rn
0,3107707,A-RM,LIQB,Продажа обеспечения бирж.рынок - безадрес.,stock_mamc_liq,Безадресные сделки с ЦК,mamc,stock,None,US00846U1016,ESXXXX,Акции / обыкновенные,1,None,None,None,None,None,0.01,127649.0,None,2021-11-01T05:02:21.84541,234049,101899
1,3107886,A-RM,PSSD,РПС: Ин.Акции (USD) - адрес.,stock_foreignndm_usd,РПС: Ин.Акции (USD) - адрес.,foreignndm,stock,None,US00846U1016,ESXXXX,Акции / обыкновенные,1,None,RUB,None,None,None,0.01,127649.0,None,2022-12-22T09:56:16.326722,234049,102078
2,3107946,A-RM,FTEQ,РПС с ЦК: Ин.Акции и ДР - адрес.,stock_foreign_ccp,РПС с ЦК: Ин.Акции и ДР - адрес.,foreignndm,stock,None,US00846U1016,ESXXXX,Акции / обыкновенные,1,None,None,None,None,None,1.00,127649.0,None,2021-11-01T05:03:14.845768,234049,102138
3,3108028,A-RM,EQRE,РЕПО с ЦК 1 день (EUR) - безадрес.,stock_ccp_d_eur,РЕПО с ЦК 1 день (EUR) - безадрес.,ccp,stock,None,US00846U1016,ESXXXX,Акции / обыкновенные,1,None,None,None,None,None,0.01,127649.0,None,2021-11-01T05:03:33.845899,234049,102220
4,3108069,A-RM,LIQR,РЕПО с ЦК: Урегулирование - безадрес.,stock_ccp_liq,РЕПО с ЦК: Урегулирование - безадрес.,ccp,stock,None,US00846U1016,ESXXXX,Акции / обыкновенные,1,None,None,None,None,None,0.01,127649.0,None,2021-11-01T05:03:42.845958,234049,102261

In [11]:
CurrencyRateDF = CurrencyRate().df
CurrencyRateDF.head()

        rate  endOfDayRate error from   to
0  21.920700     22.049200  None  AED  RUB
1        NaN           NaN  None  AFN  RUB
2        NaN           NaN  None  ALL  RUB
3   0.210346      0.211618  None  AMD  RUB
4        NaN           NaN  None  ANG  RUB

##### Шаг 1.1. RuData MOEX stage

In [12]:
HistoryStockBondsDF = HistoryStockBonds().df
HistoryStockBondsDF.head()

,boardname,regnumber,isin,matdate,listname,facevalue,currencyid,volume,value,numtrades,prev,prevlegalcloseprice,openperiod,legalopenprice,legalcloseprice,closeperiod,waprice,trendclose,trendclspr,trendwap,trendwappr,openval,closeval,highbid,lowoffer,bid,offer,yieldatwap,yieldclose,accint,duration,marketprice,marketprice2,admittedquote,issuesize,mpvaltrd,mp2valtrd,admittedvalue,marketprice3,marketprice3tradesvalue,type,lastprice,iricpiclose,beiclose,couponpercent,couponvalue,buybackdate,lasttradedate,cbrclose,yieldtooffer,yieldlastcoupon,offerdate,faceunit,engine,market,boardid,decimals,high,low,open,close,secid,shortname,tradedate,tradingsession,counter
0,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,1087,88088050.63,25,97.6999,97.7000,NaN,None,97.7900,None,98.0987,-0.0495,-0.05,-0.7127,-0.72,80780.11,80667.43,98.7665,97.7833,97.6503,98.0273,9.01,9.31,1622.1800,NaN,None,98.1006,None,240419,0.0,87603480.49,None,98.1006,87603480.49,corporate_bond,97.6504,NaN,NaN,7.63,38.23,None,2025-10-01T00:00:00,None,NaN,NaN,None,USD,stock,bonds,TQCB,4,98.7643,97.6504,97.7868,97.6504,BYM000001818,РесБел 331,2025-10-01T00:00:00,3,NaN
1,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,277,22199267.51,36,97.6504,97.7900,NaN,None,98.6005,None,98.3374,1.2259,1.26,0.2387,0.24,79947.77,80580.92,99.1900,98.0993,98.0532,98.5388,8.85,8.49,1617.3745,NaN,None,98.3365,None,240419,0.0,22038776.39,None,98.3365,22038776.39,corporate_bond,98.8763,NaN,NaN,7.63,38.23,None,2025-10-02T00:00:00,None,NaN,NaN,None,USD,stock,bonds,TQCB,4,99.1900,98.0533,98.0994,98.8763,BYM000001818,РесБел 331,2025-10-02T00:00:00,3,NaN
2,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,132,10646499.64,48,98.8763,98.6005,NaN,None,100.2062,None,99.5640,0.1387,0.14,1.2266,1.25,80481.05,240631.70,100.2063,99.0150,99.0155,100.5451,8.04,8.41,1624.6089,NaN,None,99.5966,None,240419,0.0,9762485.64,None,99.5966,9762485.64,corporate_bond,99.0150,NaN,NaN,7.63,38.23,None,2025-10-03T00:00:00,None,NaN,NaN,None,USD,stock,bonds,TQCB,4,100.2063,99.0150,99.3489,99.0150,BYM000001818,РесБел 331,2025-10-03T00:00:00,3,NaN
3,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,136,11136091.81,43,99.0150,100.2062,NaN,None,100.6981,None,99.9831,0.7900,0.80,0.4191,0.42,79974.12,81737.20,100.5949,99.7781,99.1128,100.3565,7.77,7.89,1693.7513,NaN,None,100.0049,None,240419,0.0,9828110.44,None,100.0049,9828110.44,corporate_bond,99.8050,NaN,NaN,7.63,38.23,None,2025-10-06T00:00:00,None,NaN,NaN,None,USD,stock,bonds,TQCB,4,100.6981,97.6514,97.6522,99.8050,BYM000001818,РесБел 331,2025-10-06T00:00:00,3,NaN
4,Т+: Облигации - безадрес.,MF-LB-USD-0331,BYM000001818,2027-06-29T00:00:00,3,1000.0,SUR,832,68262019.08,32,99.8050,100.6981,NaN,None,98.8804,None,98.8502,-1.9845,-1.99,-1.1329,-1.13,20521335.00,81191.02,99.3501,98.0000,97.9300,98.4999,8.52,9.21,1733.9041,NaN,None,98.8602,None,240419,0.0,58914771.06,None,98.8602,58914771.06,corporate_bond,97.8205,NaN,NaN,7.63,38.23,None,2025-10-07T00:00:00,None,NaN,NaN,None,USD,stock,bonds,TQCB,4,99.3501,97.8205,98.8980,97.8205,BYM000001818,РесБел 331,2025-10-07T00:00:00,3,NaN

In [13]:
HistoryStockSharesDF = HistoryStockShares().df
HistoryStockSharesDF.head()

,boardname,regnumber,isin,listname,facevalue,currencyid,prevlegalcloseprice,prev,legalopenprice,openperiod,closeperiod,openval,closeval,legalcloseprice,trendclose,trendclspr,highbid,bid,offer,lowoffer,waprice,trendwap,trendwappr,volume,marketprice,marketprice2,mp2valtrd,mpvaltrd,value,numtrades,issuesize,admittedquote,admittedvalue,monthlycapitalization,dailycapitalization,marketprice3,marketprice3tradesvalue,type,closeauctionprice,waval,lastprice,engine,market,boardid,decimals,high,low,open,close,secid,shortname,tradedate,tradingsession,counter
0,Т+: Акции и ДР - безадрес.,1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,70.28,71.10,None,NaN,None,21336.0,6298.2,69.80,-1.12,-1.58,71.80,70.00,70.16,67.38,70.70,0.32,0.45,95790,None,70.68,4459788.8,0.0,6772351.0,1342,92645451,None,None,6.512975e+09,6.548180e+09,70.68,4459788.8,common_share,69.80,0.0,69.98,stock,shares,TQBR,2,71.88,69.80,71.12,69.98,ABIO,iАРТГЕН ао,2025-10-01T00:00:00,3,NaN
1,Т+: Акции и ДР - безадрес.,1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,69.80,69.98,None,NaN,None,702.8,1334.0,66.10,-3.28,-4.69,70.98,66.54,66.68,65.40,67.06,-3.64,-5.15,574150,None,66.90,32768764.2,0.0,38499836.0,10444,92645451,None,None,6.512975e+09,6.197981e+09,66.90,32768764.2,common_share,66.10,0.0,66.70,stock,shares,TQBR,2,70.52,65.82,70.28,66.70,ABIO,iАРТГЕН ао,2025-10-02T00:00:00,3,NaN
2,Т+: Акции и ДР - безадрес.,1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,66.10,66.70,None,NaN,None,2668.8,1968.0,65.86,-1.10,-1.65,68.94,65.46,65.60,63.44,66.22,-0.84,-1.25,187690,None,66.44,7341839.2,0.0,12429181.0,1706,92645451,None,None,6.512975e+09,6.155364e+09,66.44,7341839.2,common_share,65.86,0.0,65.60,stock,shares,TQBR,2,67.38,65.20,66.72,65.60,ABIO,iАРТГЕН ао,2025-10-03T00:00:00,3,NaN
3,Т+: Акции и ДР - безадрес.,1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,65.86,65.60,None,NaN,None,2645.6,1324.8,65.94,0.64,0.98,67.38,66.14,66.24,63.48,64.88,-1.34,-2.02,294760,None,65.44,8684608.4,0.0,19123224.2,2867,92645451,None,None,6.512975e+09,6.062718e+09,65.44,8684608.4,common_share,65.94,0.0,66.24,stock,shares,TQBR,2,66.50,63.48,66.14,66.24,ABIO,iАРТГЕН ао,2025-10-06T00:00:00,3,NaN
4,Т+: Акции и ДР - безадрес.,1-01-08902-A,RU000A0JNAB6,2,0.1,SUR,65.94,66.24,None,NaN,None,1978.8,27176.0,67.98,1.70,2.57,70.00,67.76,67.96,65.14,67.40,2.52,3.88,342310,None,67.54,20089384.4,0.0,23070522.8,2949,92645451,None,None,6.512975e+09,6.257274e+09,67.54,20089384.4,common_share,67.98,0.0,67.94,stock,shares,TQBR,2,68.70,65.50,65.96,67.94,ABIO,iАРТГЕН ао,2025-10-07T00:00:00,3,NaN

In [14]:
HistoryStockNdmDF = HistoryStockNdm().df
HistoryStockNdmDF.head()

,boardname,closeval,currencyid,facevalue,isin,issuesize,listname,matdate,numtrades,openval,prev,regnumber,trendclose,trendclspr,trendwap,trendwappr,type,value,volume,waprice,yieldatwap,yieldclose,lastprice,iricpiclose,beiclose,couponpercent,couponvalue,buybackdate,lasttradedate,cbrclose,yieldtooffer,yieldlastcoupon,offerdate,faceunit,engine,market,boardid,decimals,high,low,open,close,secid,shortname,tradedate,tradingsession,counter
0,РПС с ЦК: Акции и ДР - адрес.,38240551.2,SUR,0.09,RU000A0DQZE3,9650000000,1,None,1,38240551.2,13.831,1-05-01669-A,-0.703,NaN,-0.291,-2.17,common_share,38240551.2,2912900,13.108,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,None,NaN,NaN,None,None,stock,ndm,PTEQ,3,13.128,13.128,13.128,13.128,AFKS,Система ао,2025-10-02T00:00:00,3,NaN
1,РПС с ЦК: Акции и ДР - адрес.,42354720.0,SUR,0.09,RU000A0DQZE3,9650000000,1,None,1,42354720.0,13.128,1-05-01669-A,-0.264,NaN,-0.273,-2.08,common_share,42354720.0,3292500,12.835,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,None,NaN,NaN,None,None,stock,ndm,PTEQ,3,12.864,12.864,12.864,12.864,AFKS,Система ао,2025-10-03T00:00:00,3,NaN
2,РПС с ЦК: Акции и ДР - адрес.,50460000.0,SUR,0.09,RU000A0DQZE3,9650000000,1,None,3,5683050.0,12.864,1-05-01669-A,-0.249,NaN,-0.254,-1.97,common_share,87971075.6,6993800,12.668,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,None,NaN,NaN,None,None,stock,ndm,PTEQ,3,12.629,12.512,12.629,12.615,AFKS,Система ао,2025-10-08T00:00:00,3,NaN
3,РПС с ЦК: Акции и ДР - адрес.,6438361.8,SUR,0.09,RU000A0DQZE3,9650000000,1,None,1,6438361.8,12.615,1-05-01669-A,-0.013,NaN,0.699,5.70,common_share,6438361.8,510900,12.958,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,None,NaN,NaN,None,None,stock,ndm,PTEQ,3,12.602,12.602,12.602,12.602,AFKS,Система ао,2025-10-16T00:00:00,3,NaN
4,РПС с ЦК: Акции и ДР - адрес.,118980000.0,SUR,0.09,RU000A0DQZE3,9650000000,1,None,1,118980000.0,12.602,1-05-01669-A,0.618,NaN,0.497,3.84,common_share,118980000.0,9000000,13.455,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,None,NaN,NaN,None,None,stock,ndm,PTEQ,3,13.220,13.220,13.220,13.220,AFKS,Система ао,2025-10-17T00:00:00,3,NaN

In [15]:
HistoryStockCcpDF = HistoryStockCcp().df
HistoryStockCcpDF.head()

,accint,admittedquote,admittedvalue,bid,boardname,closeperiod,closeval,currencyid,duration,facevalue,highbid,isin,issuesize,legalcloseprice,legalopenprice,listname,lowoffer,marketprice,marketprice2,marketprice3,marketprice3tradesvalue,matdate,mp2valtrd,mpvaltrd,numtrades,offer,openperiod,openval,prev,prevlegalcloseprice,regnumber,trendclose,trendclspr,trendwap,trendwappr,type,value,volume,waprice,yieldatwap,yieldclose,engine,market,boardid,decimals,high,low,open,close,secid,shortname,tradedate,tradingsession,counter
0,NaN,None,None,None,РЕПО с ЦК 1 день - безадрес.,None,565485.76,SUR,None,0.1,NaN,RU000A0JNAB6,92645451,None,None,2,NaN,NaN,None,None,NaN,None,NaN,NaN,5,None,None,169538.42,-81.14,None,1-01-08902-A,-17.86,None,-25.67,NaN,common_share,1300670.89,24243,-84.66,None,None,stock,ccp,EQRP,4,11.01,-99.0,11.01,-99.00,ABIO,iАРТГЕН ао,2025-10-01T00:00:00,3,NaN
1,NaN,None,None,None,РЕПО с ЦК 1 день - безадрес.,None,465622.11,SUR,None,0.1,NaN,RU000A0JNAB6,92645451,None,None,2,NaN,NaN,None,None,NaN,None,NaN,NaN,3,None,None,268215.50,-99.00,None,1-01-08902-A,91.00,None,74.47,NaN,common_share,1026192.51,19130,-10.19,None,None,stock,ccp,EQRP,4,-8.00,-12.0,-12.00,-8.00,ABIO,iАРТГЕН ао,2025-10-02T00:00:00,3,NaN
2,NaN,None,None,None,РЕПО с ЦК 1 день - безадрес.,None,436800.17,SUR,None,0.1,NaN,RU000A0JNAB6,92645451,None,None,2,NaN,NaN,None,None,NaN,None,NaN,NaN,3,None,None,100997.46,-8.00,None,1-01-08902-A,-7.00,None,-4.32,NaN,common_share,1029952.66,20467,-14.51,None,None,stock,ccp,EQRP,4,-10.00,-15.0,-10.00,-15.00,ABIO,iАРТГЕН ао,2025-10-03T00:00:00,3,NaN
3,NaN,None,None,None,РЕПО с ЦК 1 день - безадрес.,None,100020.72,SUR,None,0.1,NaN,RU000A0JNAB6,92645451,None,None,2,NaN,NaN,None,None,NaN,None,NaN,NaN,4,None,None,556355.86,-15.00,None,1-01-08902-A,15.02,None,14.52,NaN,common_share,1091704.87,21775,0.01,None,None,stock,ccp,EQRP,4,0.02,NaN,NaN,0.02,ABIO,iАРТГЕН ао,2025-10-06T00:00:00,3,NaN
4,NaN,None,None,None,РЕПО с ЦК 1 день - безадрес.,None,434992.99,SUR,None,0.1,NaN,RU000A0JNAB6,92645451,None,None,2,NaN,NaN,None,None,NaN,None,NaN,NaN,3,None,None,526000.74,0.02,None,1-01-08902-A,-15.02,None,-7.74,NaN,common_share,1085277.44,21656,-7.73,None,None,stock,ccp,EQRP,4,NaN,-15.0,NaN,-15.00,ABIO,iАРТГЕН ао,2025-10-07T00:00:00,3,NaN

##### Шаг 2. RuData transform

In [17]:
Prices = FintoolReferenceDataDF[['isincode', 'nickname', 'fintooltype', 'fintoolid', 'faceftname']]\
.rename(columns={
    "isincode": "isin",
    "nickname": "name",
    "fintoolid": "fintool",
    "fintooltype": "type",
    "faceftname": "currency"
})
Prices = Prices[~(Prices["isin"].isna() | (Prices["isin"].isin(['None', ''])))]
InterestDF = AccruedInterestOnDateDF[['fintoolId', 'accruedInterest', 'currentFaceValue']].set_index('fintoolId')
InterestDF.update(FloatersOnPeriodDF.groupby('fintoolId').last())
Prices = Prices.merge(
    InterestDF, how="left", left_on="fintool", right_index=True)
Prices = Prices.rename(columns={
    'accruedInterest': 'interest',
    'currentFaceValue': 'principal'})
Prices = Prices.merge(
    CurrencyRateDF[CurrencyRateDF['to']=='RUB'][['from', 'rate']], how='left', left_on='currency', right_on='from'
).drop(columns=['from'])

###### Шаг 2.1.1. CBR

In [18]:
from src.sources.cbr.CBR_Soap import CBR_Soap

headers = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.6834.111 Safari/537.36',
           'Accept-Encoding': 'gzip, deflate',
           'Accept': '*/*',
           'Connection': 'keep-alive'}
cbr_disc = CBR_Soap()\
.get_discounts(date=last_work_date_month_str)[['ISIN', 'от 1 месяца до 180 дней_Beg']]\
.rename(columns={'от 1 месяца до 180 дней_Beg': 'cbr_discount_6d'})\
.groupby('ISIN')\
.last()\
.reset_index()

GET http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx?wsdl using urllib2 3.10
GET http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx?wsdl using urllib2 3.10
GET http://www.cbr.ru/secinfo/secinfo.asmx?wsdl using urllib2 3.10
GET http://www.cbr.ru/secinfo/secinfo.asmx?wsdl using urllib2 3.10

/Users/alexander/PycharmProjects/insurance_mine/src/sources/cbr/CBR_Soap.py:212: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  disc = pd.concat([disc, pd.DataFrame(index=[0], data=d)], axis=0)

In [19]:
Prices = Prices.merge(cbr_disc, how='left', left_on='isin', right_on='ISIN')
Prices['cbr_discount_6d'] = Prices['cbr_discount_6d'].fillna(1.0)

###### Шаг 2.1.2. nationalclearingcentre Рыночные риски

In [20]:
currMarketRatesResponse = requests.get(f'https://www.nationalclearingcentre.ru/api/v1/rates/fondMarketRates?action=xls&xls=1&lang=ru&date={last_work_date_month.strftime("%d.%m.%Y")}', headers=headers)
currMarketRates = pd.read_excel(currMarketRatesResponse.content,header=2)
currMarketRates = currMarketRates[(currMarketRates['Диапазон']==1)&(currMarketRates['Ставка риска падения цены,%']!=100)].reset_index(drop=True)
currMarketRates = currMarketRates\
.merge(MoexSecuritiesDF[['secid', 'isin']], how='left', left_on='Инструмент', right_on='secid')\
.groupby('isin')\
.last()\
.reset_index()
currMarketRates = currMarketRates[currMarketRates['isin'].str.match('([A-Z]{2})([A-Z0-9]{9})([0-9]{1})$')]
currMarketRates = currMarketRates[
    (currMarketRates['Диапазон']==1) & (currMarketRates['Ставка риска падения цены,%'] != 100)
]
currMarketRates = currMarketRates[['isin', 'Ставка риска падения цены,%']]\
.rename(columns={'Ставка риска падения цены,%': 'Risk rate'})
# Формула из п.12.1 Методики НКЦ определения риск-параметров
currMarketRates['discount_ncc'] = currMarketRates['Risk rate'].apply(lambda x: min(30, ceil(x/np.sqrt(2)))/100)

/var/folders/g4/mpm4njl93p547kbhxbvqlm480000gn/T/ipykernel_1718/3059006292.py:2: FutureWarning: Passing bytes to 'read_excel' is deprecated and will be removed in a future version. To read from a byte string, wrap it in a `BytesIO` object.
  currMarketRates = pd.read_excel(currMarketRatesResponse.content,header=2)

In [21]:
Prices = Prices.merge(currMarketRates[['isin', 'discount_ncc']], how='left', on='isin')
Prices['discount_ncc'] = Prices['discount_ncc'].fillna(1.0)

###### Шаг 2.1.3. nationalclearingcentre Параметры ценных бумаг

In [22]:
securInfoResponse = requests.get(f'https://www.nationalclearingcentre.ru/api/v1/rates/securInfo?action=xls&lang=ru&settleDate={last_work_date_month.strftime("%d.%m.%Y")}', headers=headers)
securInfo = pd.read_excel(securInfoResponse.content, header=2)[['ISIN ЦБ', 'Принимается в обеспеч.']]\
.rename(columns={
    'ISIN ЦБ': 'isin',
    'Принимается в обеспеч.': 'ncc_collateral'
})\
.dropna()\
.groupby('isin')\
.last()\
.reset_index()
securInfo = securInfo[securInfo['ncc_collateral']=='Да']

/var/folders/g4/mpm4njl93p547kbhxbvqlm480000gn/T/ipykernel_1718/435643160.py:2: FutureWarning: Passing bytes to 'read_excel' is deprecated and will be removed in a future version. To read from a byte string, wrap it in a `BytesIO` object.
  securInfo = pd.read_excel(securInfoResponse.content, header=2)[['ISIN ЦБ', 'Принимается в обеспеч.']]\

In [23]:
Prices = Prices.merge(securInfo, how='left', on='isin')
Prices['ncc_collateral'] = Prices['ncc_collateral'].fillna('Нет')

##### Шаг 2.2. RuData transform

In [24]:
RUPriceHistoryLast = RUPriceHistoryDF.groupby('isincode').last().rename(columns={
    'vp_pct': 'clean_price_pct',
    'vp_pc': 'clean_price',
    'acc_int': 'InterestHistory'
}).reset_index()
ru_price = RUPriceHistoryLast[['isincode', 'clean_price_pct', 'clean_price', 'InterestHistory']].merge(
    Prices[['isin', 'type', 'interest']], left_on='isincode', right_on='isin')
ccnrd_bonds_idx = ru_price["type"]=='Облигация'
ru_price.loc[ccnrd_bonds_idx, "InterestHistory"] = ru_price.loc[ccnrd_bonds_idx, "InterestHistory"].combine_first(ru_price.loc[ccnrd_bonds_idx, "interest"])
ru_price.loc[ccnrd_bonds_idx, "price"] = ru_price.loc[ccnrd_bonds_idx, "clean_price"] + ru_price.loc[ccnrd_bonds_idx, "InterestHistory"].fillna(0)
ru_price.loc[~ccnrd_bonds_idx, "price"] = ru_price.loc[~ccnrd_bonds_idx, "clean_price"]
ru_price["source"] = 'RU Data (ЦЦ НРД)'

In [25]:
exch_prices = EndOfDayDF.merge(
    ExchangeTreeDF[['id', 'fullname_rus']], how='left', left_on='id_trade_site', right_on='id')[['fintoolId', 'last', 'fullname_rus']]
exch_prices["source"] = exch_prices['fullname_rus'].apply(lambda x: 'RU Data (' + str(x) + ')')
exch_prices = exch_prices\
.rename(columns={
    'fintoolId': 'fintool',
    'last': 'PriceEX'
})
exch_prices = exch_prices.merge(Prices[["fintool", "isin", "type", "principal", "interest"]], how='inner')
exch_prices[['PriceEX', 'principal', 'interest']] = exch_prices[['PriceEX', 'principal', 'interest']].fillna(0)

exch_bonds = exch_prices['type']=='Облигация'
exch_prices.loc[exch_bonds, "clean_price_pct"] = exch_prices.loc[exch_bonds, "PriceEX"]
exch_prices.loc[exch_bonds, "clean_price"] = exch_prices.loc[exch_bonds, "clean_price_pct"]/100 * exch_prices.loc[exch_bonds, "principal"]
exch_prices.loc[exch_bonds, "price"] = exch_prices.loc[exch_bonds, "clean_price"] + exch_prices.loc[exch_bonds, "interest"]

exch_prices.loc[~exch_bonds, 'clean_price'] = exch_prices.loc[~exch_bonds, 'PriceEX']
exch_prices.loc[~exch_bonds, 'price'] = exch_prices.loc[~exch_bonds, 'PriceEX']

##### Шаг 3. Moex

In [26]:
TransformHistoryStockBonds = HistoryStockBondsDF.groupby("isin")['close'].last().rename("price").reset_index()
TransformHistoryStockShares = HistoryStockSharesDF.groupby("isin")['close'].last().rename("price").reset_index()
TransformHistoryStockNdm = HistoryStockNdmDF.groupby("isin")['close'].last().rename("price").reset_index()
TransformHistoryStockCcp = HistoryStockCcpDF.groupby("isin")['close'].last().rename("price").reset_index()
HistoryStock = pd.concat(
    [TransformHistoryStockBonds, TransformHistoryStockShares, TransformHistoryStockNdm, TransformHistoryStockCcp]
).groupby('isin').last().reset_index()
HistoryStock['source'] = 'RU Data (MOEX)'

#### Шаг 4. Finish

In [27]:
source_prices = pd.concat([
    ru_price[["isin", "clean_price_pct", "clean_price", "price", "source"]],
    exch_prices[["isin", "clean_price_pct", "clean_price", "price", "source"]],
    HistoryStock
])

In [39]:
result = Prices.merge(
    source_prices,
    how='inner',
    on='isin',
)
result['export_timestamp'] = dt.now().replace(microsecond=0)
result['report_date'] = pd.to_datetime(last_day_month)
result['source'] = result['source'].replace('nan', '').fillna('')
result['name'] = result['name'].replace('nan', '').fillna('')
result['type'] = result['type'].replace('nan', '').fillna('')
result['currency'] = result['currency'].replace('nan', '').fillna('')
result['fintool'] = result['fintool'].astype(int)
result = result.sort_values('isin')[["isin", "name", "type", "fintool", "currency", "interest", "principal", "rate", "cbr_discount_6d", "discount_ncc", "ncc_collateral", "clean_price_pct", "clean_price", "price", "source", "export_timestamp", "report_date"]]

##### Шаг 4.2. Write excel

In [33]:
result.to_csv('../data/Output/prices.csv', index=False)
result.to_excel('../data/Output/prices.xlsx', index=False)

In [34]:
from src.utils.send_email import main
main("prices.xlsx", "prices.csv")